# The app's texts in German: the same keys as English (en.psd1), which fills in any key missing here.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Kein Modem über USB gefunden.'
    'Reason.NoDriver'              = 'Der AT-Port des Modems hat keinen Treiber: Die App kann erst mit dem Modem kommunizieren, wenn er installiert ist.'
    'Reason.DeviceProblem'         = 'Windows meldet ein Problem mit dem AT-Port des Modems.'
    'Reason.PortInUse'             = 'Ein anderes Programm verwendet den AT-Port des Modems.'
    'Reason.PortFailed'            = 'Der AT-Port des Modems kann nicht geöffnet werden.'
    'Reason.SimUnknown'            = 'Die SIM wird gelesen.'
    'Reason.NoPin'                 = 'Die SIM wartet auf ihre PIN.'
    'Reason.PinForOtherSim'        = 'Die gespeicherte PIN gehört zu einer anderen SIM: Geben Sie die PIN dieser SIM ein.'
    'Reason.SimNotIdentified'      = 'Die SIM kann nicht identifiziert werden, daher wird ihr die gespeicherte PIN nicht gesendet.'
    'Reason.PinUnconfirmed'        = 'Die letzte PIN-Eingabe blieb ohne Antwort, und die App versucht es nie zweimal: Geben Sie die PIN erneut ein.'
    'Reason.LastAttempt'           = 'Es ist nur noch ein PIN-Versuch übrig, und die App verwendet ihn nicht: Entsperren Sie die SIM in einem Telefon.'
    'Reason.PukRequired'           = 'Die SIM ist gesperrt und benötigt ihre PUK: Entsperren Sie die SIM in einem Telefon. Die App gibt nie eine PUK ein.'
    'Reason.NoSim'                 = 'Keine SIM im Modem.'
    'Reason.SimFailure'            = 'Die SIM funktioniert nicht.'
    'Reason.SimOther'              = 'Die SIM wartet auf einen Code, den die App nicht verarbeitet.'
    'Reason.SimBusy'               = 'Die SIM ist beschäftigt; es wird auf sie gewartet.'
    'Reason.FccLocked'             = 'Das Modem ist vom Hersteller seines Laptops gesperrt (FCC-Sperre): Sein Funkteil bleibt ausgeschaltet.'
    'Reason.NotRegistered'         = 'Nicht in einem Netz registriert.'
    'Reason.NotSearching'          = 'Nicht registriert, und es wird kein Netz gesucht.'
    'Reason.Searching'             = 'Es wird ein Netz gesucht.'
    'Reason.Denied'                = 'Das Netz hat die Registrierung abgelehnt.'
    'Reason.Unknown'               = 'Nicht registriert; der Grund ist unbekannt.'
    'Reason.EmergencyOnly'         = 'Nur Notrufe.'
    'Reason.ContextUnknown'        = 'Die Datenverbindung wird gelesen.'
    'Reason.ApnPasswordUnreadable' = 'Das gespeicherte APN-Kennwort kann nicht gelesen werden: Geben Sie es erneut ein.'
    'Reason.ApnNeeded'             = 'Das Netz hat bei leerem APN keinen Internetzugang gewährt: Geben Sie den APN Ihres Netzbetreibers ein.'
    'Reason.NoAddress'             = 'Die Datenverbindung hat keine IPv4-Adresse.'
    'Reason.AdapterDisabled'       = 'Der Netzwerkadapter des Modems ist deaktiviert.'
    'Reason.NoAdapter'             = 'Der Netzwerkadapter des Modems fehlt.'
    'Reason.NotElevated'           = 'Der Netzwerkadapter kann nur mit Administratorrechten konfiguriert werden: Starten Sie die App als Administrator.'
    'Reason.DataPathFailed'        = 'Die Verbindung steht, aber es kommt kein Datenverkehr durch.'
    'Reason.DohServerUnresolved'   = 'Der Name des DNS-over-HTTPS-Servers ist noch nicht aufgelöst: Die App versucht es weiter und lässt den Netzwerkadapter bis dahin so, wie das Modem ihn eingerichtet hat.'
    'Reason.DohNeedsServers'       = 'Verschlüsseltes DNS benötigt DNS-Server Ihrer Wahl: Die des Netzbetreibers sprechen kein DNS over HTTPS. Bis dahin wird der Netzwerkadapter nicht konfiguriert.'
    'Reason.DohUnavailable'        = 'Dieses Windows kann DNS nicht für einen einzelnen Adapter verschlüsseln - DNS over HTTPS erfordert dafür Windows 11: Deaktivieren Sie verschlüsseltes DNS. Bis dahin wird der Netzwerkadapter nicht konfiguriert.'
    'Reason.DohTemplateMissing'    = 'Windows kennt keine DNS-over-HTTPS-Vorlage für einen DNS-Server aus den Einstellungen: Geben Sie eine an, oder wählen Sie Server, die Windows kennt. Bis dahin wird der Netzwerkadapter nicht konfiguriert.'
    'Reason.Connected'             = 'Verbunden.'
    'Reason.Other'                 = 'Nicht registriert ({0}).'
    'Reason.Working'               = 'Die App arbeitet an der Verbindung.'
    'Reason.NoNetworkForMode'      = 'Kein Netz mit {0} gefunden. Auch ein Zurücksetzen findet keines: Wählen Sie einen weiter gefassten Netzmodus.'
    'Reason.NoNetworkForModeBands' = 'Kein Netz mit {0} auf den gewählten LTE-Bändern gefunden. Auch ein Zurücksetzen findet keines: Wählen Sie einen weiter gefassten Netzmodus.'
    'Reason.Withheld'              = 'Die App beobachtet nur und führt daher den nächsten Schritt nicht aus: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Der AT-Port des Modems wird geöffnet.'
    'Action.Initialize'              = 'Warten auf die Antwort des Modems.'
    'Action.EnterPin'                = 'Die gespeicherte PIN wird eingegeben.'
    'Action.RadioOn'                 = 'Das Funkteil wird eingeschaltet.'
    'Action.AutoRegister'            = 'Das Netz wird automatisch ausgewählt.'
    'Action.DefineContext'           = 'Die Datenverbindung wird eingerichtet.'
    'Action.ActivateContext'         = 'Die Datenverbindung wird eingerichtet.'
    'Action.DeactivateContext'       = 'Die Datenverbindung wird eingerichtet.'
    'Action.ConfigureAdapter'        = 'Der Netzwerkadapter wird konfiguriert.'
    'Action.ApplyNetworkMode'        = 'Der Netzmodus wird festgelegt.'
    'ActionInline.OpenPort'          = 'Öffnen des AT-Ports des Modems.'
    'ActionInline.Initialize'        = 'Warten auf die Antwort des Modems.'
    'ActionInline.EnterPin'          = 'Eingabe der gespeicherten PIN.'
    'ActionInline.RadioOn'           = 'Einschalten des Funkteils.'
    'ActionInline.AutoRegister'      = 'automatische Auswahl des Netzes.'
    'ActionInline.DefineContext'     = 'Einrichten der Datenverbindung.'
    'ActionInline.ActivateContext'   = 'Einrichten der Datenverbindung.'
    'ActionInline.DeactivateContext' = 'Einrichten der Datenverbindung.'
    'ActionInline.ConfigureAdapter'  = 'Konfiguration des Netzwerkadapters.'
    'ActionInline.ApplyNetworkMode'  = 'Festlegen des Netzmodus.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Nur 4G'
    'Mode.NrOnly'                  = 'Nur 5G (SA)'
    'Mode.NotManaged'              = 'Wie im Modem eingestellt'
    'Mode.Other'                   = 'Modus {0}'
    'ModeProblem.NotKept'          = 'Das Modem behält den Netzmodus nicht so, wie er geschrieben wurde; die App schreibt ihn nicht erneut.'
    'ModeProblem.NoSupportedBand'  = 'Das Modem unterstützt keines der Bänder, die für eine seiner RATs gewählt wurden.'
    'ModeProblem.ModeUnsupported'  = 'Das Modem unterstützt diesen Netzmodus nicht.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Die Verbindung wird jetzt geprüft.'
    'Result.SaveSettings.Done'              = 'Einstellungen gespeichert.'
    'Result.SaveSimPin.Done'                = 'PIN gespeichert: Die App gibt sie einmal ein, wenn die SIM danach fragt.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Die SIM kann nicht identifiziert werden: Die PIN wurde nicht gespeichert.'
    'Result.ForgetSimPin.Done'              = 'Die gespeicherte PIN ist gelöscht.'
    'Result.DisableSimPin.Disabled'         = 'Die SIM fragt nicht mehr nach ihrer PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'Die PIN-Abfrage der SIM war bereits deaktiviert.'
    'Result.DisableSimPin.PinRejected'      = 'Falsche PIN: Die SIM fragt weiterhin danach.'
    'Result.DisableSimPin.LastAttempt'      = 'Es ist nur noch ein PIN-Versuch übrig: Es wurde nichts gesendet.'
    'Result.DisableSimPin.SimNotReady'      = 'Die SIM ist nicht bereit: Es wurde nichts gesendet.'
    'Result.DisableSimPin.Failed'           = 'Die PIN-Abfrage der SIM konnte nicht geändert werden.'
    'Result.UnlockFcc.Restarted'            = 'Entsperrung gesendet: Das Modem wird neu gestartet.'
    'Result.UnlockFcc.NotLocked'            = 'Das Modem ist nicht gesperrt: Es wurde nichts geschrieben.'
    'Result.UnlockFcc.Unknown'              = 'Die Sperre kann nicht gelesen werden: Es wurde nichts geschrieben.'
    'Result.UnlockFcc.Failed'               = 'Die Entsperrung wurde vor dem Neustart abgebrochen.'
    'Result.UnlockFcc.PortLost'             = 'Das Modem hat sich während der Entsperrung vom USB getrennt.'
    'Result.EnableAdapter.Done'             = 'Netzwerkadapter aktiviert.'
    'Result.SetNetworkMode.Applied'         = 'Netzmodus gesendet: Das Modem registriert sich erneut. Der Modus wird beibehalten, sobald das Modem damit ein Netz findet.'
    'Result.SetNetworkMode.Unchanged'       = 'Das Modem hat diesen Netzmodus bereits: Er wird beibehalten.'
    'Result.SetNetworkMode.Done'            = 'Die App verwaltet den Netzmodus nicht mehr: Das Modem behält den aktuellen.'
    'Result.SetNetworkMode.ModeUnsupported' = 'Das Modem unterstützt diesen Netzmodus nicht: Es wurde nichts geschrieben.'
    'Result.SetNetworkMode.NoSupportedBand' = 'Das Modem unterstützt keines der Bänder, die für eine seiner RATs gewählt wurden: Es wurde nichts geschrieben.'
    'Result.SetNetworkMode.Unknown'         = 'Der Netzmodus des Modems kann nicht gelesen werden: Es wurde nichts geschrieben.'
    'Result.CheckDriverPackage.Verified'    = 'Treiberpaket geprüft: eine Version, die die App kennt.'
    'Result.CheckDriverPackage.Signed'      = 'Treiberpaket geprüft: von Microsoft signiert, eine Version, die die App nicht kennt.'
    'Result.CheckDriverPackage.Refused'     = 'Das Treiberpaket kann nicht installiert werden: Der Grund steht auf der Registerkarte „Treiber“.'
    'Result.CheckDriverPackage.NoPackage'   = 'Es wurde kein Treiberpaket ausgewählt.'
    'Result.CheckDriverPackage.Failed'      = 'Das Treiberpaket kann nicht gelesen werden.'
    'Result.InstallDriver.Done'             = 'Treiber installiert: Die App öffnet den AT-Port des Modems, sobald Windows ihn startet.'
    'Result.InstallDriver.RestartNeeded'    = 'Treiber installiert: Windows muss zum Abschluss neu gestartet werden.'
    'Result.InstallDriver.NoDevice'         = 'Treiber zu Windows hinzugefügt, aber kein Gerät hat ihn übernommen: Er wird verwendet, wenn das Modem angeschlossen wird, sofern Windows keinen anderen Treiber höher einstuft.'
    'Result.InstallDriver.Unconfirmed'      = 'Nicht installiert: Eine Version, die die App nicht kennt, erfordert Ihre Bestätigung.'
    'Result.InstallDriver.NoPackage'        = 'Wählen Sie zuerst ein Treiberpaket aus.'
    'Result.InstallDriver.DriverWorking'    = 'Der AT-Port hat bereits einen funktionierenden Treiber: Es wurde nichts installiert.'
    'Result.InstallDriver.TimedOut'         = 'Windows hat die Installation des Treibers nicht rechtzeitig abgeschlossen: Der Vorgang wurde abgebrochen.'
    'Result.InstallDriver.Failed'           = 'Windows hat den Treiber nicht installiert.'
    'Result.UninstallDriver.Done'           = 'Treiber deinstalliert: Die App kann erst wieder mit dem Modem kommunizieren, wenn er erneut installiert ist.'
    'Result.UninstallDriver.RestartNeeded'  = 'Treiber deinstalliert: Windows muss zum Abschluss neu gestartet werden.'
    'Result.UninstallDriver.NoDriver'       = 'Der AT-Port hat keinen Treiber, den die App deinstallieren kann.'
    'Result.UninstallDriver.TrialOn'        = 'Nicht deinstalliert: Ein Netzmodus wird gerade getestet, und nur über den AT-Port kann er zurückgeschrieben werden.'
    'Result.UninstallDriver.TimedOut'       = 'Windows hat die Deinstallation des Treibers nicht rechtzeitig abgeschlossen: Der Vorgang wurde abgebrochen.'
    'Result.UninstallDriver.Failed'         = 'Windows hat den Treiber nicht deinstalliert.'
    'Result.NotElevated'                    = 'Dafür sind Administratorrechte erforderlich.'
    'Result.Refused'                        = 'Nicht verfügbar, solange die App nur beobachtet.'
    'Result.NoModem'                        = 'Das Modem ist nicht angeschlossen.'
    'Result.PortLost'                       = 'Das Modem hat sich während des Befehls vom USB getrennt.'
    'Result.Failed'                         = 'Das hat nicht funktioniert.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Verbleibende Versuche: {0}.'
    'Result.Restarting'                     = 'Die Überwachung wird neu gestartet: Versuchen Sie es gleich noch einmal.'

    # The headline.
    'Tone.Online'         = 'Online'
    'Tone.Working'        = 'Verbindungsaufbau'
    'Tone.Recovering'     = 'Wiederherstellung'
    'Tone.Attention'      = 'Aktion erforderlich'
    'Tone.Offline'        = 'Kein Modem'
    'Tone.Stopped'        = 'Keine Überwachung'
    'Title.ConnectionLost' = 'Verbindung verloren'
    'Title.NoNetwork'     = 'Kein Netz'
    'Title.NotConnected'  = 'Nicht verbunden'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'Das Modem ist nicht über USB verbunden.'
    'Check.H2'          = 'Das Modem antwortet nicht.'
    'Check.H3'          = 'Die SIM ist nicht bereit.'
    'Check.H4'          = 'Nicht in einem Netz registriert.'
    'Check.H5'          = 'Die Datenverbindung ist getrennt.'
    'Check.H6'          = 'Der Netzwerkadapter ist nicht konfiguriert.'
    'Check.H7'          = 'Es kommt kein Datenverkehr durch.'
    'Check.Other'       = 'Die Verbindung ist getrennt.'
    'Step.R1'           = 'Der Netzwerkadapter wird erneut konfiguriert.'
    'Step.R2'           = 'Die Datenverbindung wird neu gestartet.'
    'Step.R3'           = 'Das Modem wird erneut im Netz registriert.'
    'Step.R4'           = 'Das Funkteil wird aus- und wieder eingeschaltet.'
    'Step.R5'           = 'Das Modem wird neu gestartet.'
    'Step.R6'           = 'Das USB-Gerät des Modems wird neu gestartet.'
    'StepInline.R1'     = 'erneute Konfiguration des Netzwerkadapters.'
    'StepInline.R2'     = 'Neustart der Datenverbindung.'
    'StepInline.R3'     = 'erneute Registrierung im Netz.'
    'StepInline.R4'     = 'Aus- und Einschalten des Funkteils.'
    'StepInline.R5'     = 'Neustart des Modems.'
    'StepInline.R6'     = 'Neustart des USB-Geräts des Modems.'
    'Recovery.Waiting'  = '{0} Die Wiederherstellungsschritte haben nicht geholfen: Um {1} beginnen sie erneut.'
    'Recovery.Slow'     = '{0} Die Wiederherstellung ist {1}-mal fehlgeschlagen: Die App versucht es um {2} erneut.'
    'Recovery.Withheld' = '{0} Die App beobachtet nur und führt daher den Wiederherstellungsschritt nicht aus: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Öffnen'
    'Tray.CheckNow'       = 'Jetzt prüfen'
    'Tray.NetworkMode'    = 'Netzmodus'
    'Tray.NetworkModeNow' = 'Netzmodus: {0}'
    'Tray.Exit'           = 'Beenden'
    'Tray.Update'         = 'Version {0} ist verfügbar...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = '{0} verwenden, alle Bänder'
    'Blocker.SaveApn'       = 'APN speichern'
    'Blocker.SavePassword'  = 'Kennwort speichern'
    'Blocker.StorePin'      = 'PIN speichern'
    'Blocker.EnableAdapter' = 'Adapter aktivieren'
    'Blocker.Unlock'        = 'Entsperren...'
    'Blocker.InstallDriver' = 'Treiber installieren...'
    'Blocker.OpenSettings'  = 'Einstellungen öffnen'
    'Blocker.ObserveOnly'   = 'Die App beobachtet nur und ändert nichts.'
    'Blocker.NeedsAdmin'    = 'Zum Aktivieren sind Administratorrechte erforderlich.'
    'Blocker.UnlockNote'    = 'Das Entsperren schreibt in den nichtflüchtigen Speicher des Modems: Die App fragt vorher nach.'
    'Blocker.AttemptsLeft'  = 'Verbleibende Versuche: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Bereit'
    'Sim.PinRequired'    = 'Wartet auf ihre PIN'
    'Sim.PukRequired'    = 'Gesperrt: PUK erforderlich'
    'Sim.Absent'         = 'Keine SIM'
    'Sim.Busy'           = 'Beschäftigt'
    'Sim.Failure'        = 'Funktioniert nicht'
    'Sim.Other'          = 'Wartet auf einen anderen Code'
    'Sim.Unknown'        = 'Unbekannt'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - verbleibende PIN-Versuche: {1}'
    'Sim.RequestOn'      = 'PIN-Abfrage beim Einschalten: aktiviert'
    'Sim.RequestOff'     = 'PIN-Abfrage beim Einschalten: deaktiviert'
    'Sim.RequestUnknown' = 'PIN-Abfrage beim Einschalten: unbekannt'
    'Sim.Stored'         = 'Für diese SIM ist eine PIN gespeichert.'
    'Sim.NotStored'      = 'Es ist keine PIN gespeichert.'
    'Sim.Rejected'       = 'Die gespeicherte PIN wurde abgelehnt und gelöscht: Die App verwendet sie nie wieder.'

    # The network tab.
    'Bands.Every'       = 'alle Bänder'
    'Bands.EveryBut'    = 'alle Bänder außer {0}'
    'Bands.None'        = 'keine'
    'Network.Current'   = 'Das Modem jetzt: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'Der Netzmodus des Modems wurde noch nicht gelesen.'
    'Network.Trial'     = '{0} wird getestet: Findet das Modem damit bis {1} kein Netz, kehrt es zur vorherigen Einstellung zurück.'
    'Network.Reverted'  = 'Um {0} hatte das Modem mit {1} kein Netz gefunden: Es ist zur vorherigen Einstellung zurückgekehrt.'
    'Network.Kept'      = 'Um {0} hat sich das Modem mit {1} registriert: Diese Einstellung wird beibehalten.'
    'Network.Missing'   = 'Das Modem lässt {0} trotz Anforderung aus: Es verwendet die anderen gewählten Bänder.'
    'Network.ChooseBand' = 'Wählen Sie mindestens ein {0}-Band oder alle Bänder.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Verschlüsseltes DNS ist unter diesem Windows nicht verfügbar: DNS over HTTPS für einen einzelnen Adapter erfordert Windows 11.'
    'Dns.On'                   = 'Verschlüsseltes DNS ist aktiviert: {0}.'
    'Dns.Waiting'              = 'Verschlüsseltes DNS wartet auf die Adresse seines Servers: Bis dahin ist kein DNS-Server festgelegt.'
    'Dns.Off'                  = 'Verschlüsseltes DNS ist deaktiviert.'
    'Dns.Advertised'           = 'Das Netz gibt auch IPv6-DNS-Server vor ({0}), die Windows unverschlüsselt verwenden kann.'
    'Dns.LookupFailed'         = '{0} kann nicht aufgelöst werden; die App versucht es weiter.'
    'Dns.LookingUp'            = '{0} wird aufgelöst...'
    'Dns.LookedUp'             = 'Der Server {0} wurde um {1} aufgelöst.'
    'Dns.LookedUpNext'         = 'Der Server {0} wurde um {1} aufgelöst; erneut um {2}.'
    'Dns.LookedUpOperator'     = 'Der Server {0} wurde um {1} über das DNS des Netzbetreibers aufgelöst, unverschlüsselt.'
    'Dns.LookedUpOperatorNext' = 'Der Server {0} wurde um {1} über das DNS des Netzbetreibers aufgelöst, unverschlüsselt; erneut um {2}.'
    'Dns.NotAvailableHere'     = 'Verschlüsseltes DNS ist unter diesem Windows nicht verfügbar.'
    'Dns.NoTemplate'           = 'Windows kennt keine DNS-over-HTTPS-Vorlage für {0}: Geben Sie eine an.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; der Standardwert wird verwendet.'
    'Setting.Unknown'          = 'Die unbekannte Einstellung „{0}“ wird ignoriert.'
    'Setting.Unreadable'       = 'Die Einstellungsdatei kann nicht gelesen werden; die Standardwerte werden verwendet.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps erfordert DnsServers oder ein DohTemplate, das den Server nennt: Die Server des Netzbetreibers sprechen kein DoH, und bis dahin ist kein DNS-Server festgelegt.'
    'Setting.TemplateAddress'  = 'DohTemplate nennt die Adresse {0} und kann daher nur diesen Server bedienen; der Standardwert wird verwendet.'
    'Rule.Text'                = 'muss druckbares ASCII ohne doppelte Anführungszeichen oder umgebende Leerzeichen sein'
    'Rule.TextQuotes'          = 'muss druckbares ASCII ohne doppelte Anführungszeichen sein'
    'Rule.OneOf'               = 'muss einer der Werte {0} sein'
    'Rule.EmptyOrOneOf'        = 'muss leer oder einer der Werte {0} sein'
    'Rule.Addresses'           = 'muss eine Liste von IP-Adressen sein'
    'Rule.Number'              = 'muss eine ganze Zahl von {0} bis {1} sein'
    'Rule.Minutes'             = 'muss eine ganze Minutenzahl von {0} bis {1} sein'
    'Rule.Bool'                = 'muss true oder false sein'
    'Rule.Https'               = 'muss leer oder eine https-Adresse ohne Leerzeichen, Anführungszeichen oder Anmeldedaten sein'
    'Rule.Bands'               = 'muss eine Liste verschiedener Bandnummern von {0} bis {1} sein'
    'Rule.Gigabytes'           = 'muss eine Zahl von Gigabyte von {0} bis {1} sein, 0 für keine'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'es enthält keinen Treiber (keine INF-Datei)'
    'DriverProblem.NotForModem'  = 'keiner seiner Treiber ist für den AT-Port dieses Modems bestimmt'
    'DriverProblem.NoCatalog'    = 'sein Treiber hat keinen Signaturkatalog'
    'DriverProblem.NotWhql'      = 'sein Katalog ist nicht von Microsoft signiert (WHQL)'
    'DriverProblem.NotInCatalog' = 'seine INF-Datei ist nicht die, für die sein Katalog bürgt - sie wurde geändert oder ist beschädigt'
    'DriverProblem.NotTrusted'   = 'seine Signatur kann nicht überprüft werden'
    'Driver.Present'             = 'Der AT-Port des Modems hat seinen Treiber.'
    'Driver.PresentWhat'         = 'Der AT-Port des Modems hat seinen Treiber: {0}.'
    'Driver.NoDriver'            = 'Der AT-Port des Modems hat keinen Treiber: Die App kann nicht mit dem Modem kommunizieren.'
    'Driver.Problem'             = 'Windows meldet ein Problem mit dem AT-Port des Modems: Eine erneute Installation seines Treibers kann es beheben.'
    'Driver.Absent'              = 'Kein Modem über USB. Ein jetzt installierter Treiber wird verwendet, sobald das Modem angeschlossen wird.'
    'Driver.NotLooked'           = 'Der AT-Port des Modems wurde noch nicht geprüft.'
    'Driver.Source'              = 'Die App enthält den Treiber des Modems nicht, da sie keine Lizenz zu seiner Weitergabe hat. Laden Sie eine Kopie herunter, und wählen Sie sie hier aus: Die App prüft, ob Microsoft sie für dieses Modem signiert hat (WHQL), und führt nie ein Programm daraus aus.'
    'Driver.SourceCopy'          = 'Die App enthält den Treiber des Modems nicht, da sie keine Lizenz zu seiner Weitergabe hat. Eine Kopie des MediaTek-Treibers {0} wird von einem Dritten, {1}, als {2} veröffentlicht. Laden Sie sie herunter, und wählen Sie sie hier aus: Die App prüft, ob Microsoft sie für dieses Modem signiert hat (WHQL), und führt nie ein Programm daraus aus.'
    'Driver.Checking'            = 'Das Treiberpaket wird geprüft...'
    'Driver.Installing'          = 'Der Treiber wird installiert: Windows kann dafür eine Minute brauchen.'
    'Driver.Uninstalling'        = 'Der Treiber wird deinstalliert...'
    'Driver.Verified'            = '{0}: {1}, eine Version, die die App kennt, von Microsoft (WHQL) für dieses Modem signiert.'
    'Driver.Signed'              = '{0}: {1}, von Microsoft (WHQL) für dieses Modem signiert, aber keine Version, die die App kennt: Die App fragt vor der Installation nach.'
    'Driver.Refused'             = '{0} kann nicht installiert werden: {1}.'
    'Driver.ObserveOnly'         = 'Die App beobachtet nur und ändert nichts.'
    'Driver.NeedsAdmin'          = 'Zum Installieren oder Deinstallieren eines Treibers sind Administratorrechte erforderlich: Starten Sie die App als Administrator.'
    'Driver.Trial'               = 'Ein Netzmodus wird gerade getestet: Der Treiber kann deinstalliert werden, sobald der Test beendet ist.'
    'Driver.Install'             = 'Installieren'
    'Driver.InstallConfirm'      = 'Installieren...'
    'Driver.ChooseTitle'         = 'Heruntergeladenes Treiberpaket auswählen'
    'Driver.FileKind'            = 'Treiberpaket'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'Die Überwachung wurde beendet und wird neu gestartet. Die Verbindung bleibt unberührt.'
    'Window.NotResponding'   = 'Die Überwachung reagiert nicht. Die Verbindung bleibt unberührt.'
    'Window.Starting'        = 'Wird gestartet.'
    'Window.Simulated'       = 'Entwicklungsmodus: ein simuliertes Modem (Szenario {0}).'
    'Window.ObserveOnly'     = 'Die App beobachtet nur und ändert nichts am Modem oder am System.'
    'Window.SettingsPending' = 'Die Datenverbindung besteht mit anderen Einstellungen: Die neuen gelten ab der nächsten Verbindung.'
    'Window.SettingsFile'    = 'Einstellungsdatei: {0}'
    'Window.Modems'          = '{0} Modems gefunden: Die App verwendet das Modem an {1}.'
    'Window.Recovered'       = 'Um {0} wiederhergestellt: {1}'
    'Window.NrAvailable'     = '{0}, 5G verfügbar'
    'Window.NothingMeasured' = 'Keine Messwerte.'
    'Window.PasswordStored'  = 'Ein Kennwort ist gespeichert.'
    'Window.NoPassword'      = 'Es ist kein Kennwort gespeichert.'
    'Window.PinFirst'        = 'Geben Sie zuerst die PIN der SIM ein: Zum Entfernen wird die PIN benötigt.'
    'Cell.Serving'           = 'Versorgend'
    'Cell.Neighbour'         = 'Nachbar'
    'Carrier.Primary'        = 'Primär'
    'Carrier.Active'         = 'Aktiv'
    'Carrier.Inactive'       = 'Inaktiv'
    'Footer.Port'            = 'AT-Port {0}'
    'Footer.PortClosed'      = 'AT-Port geschlossen'
    'Footer.Updated'         = 'aktualisiert um {0}'
    'Footer.PathChecked'     = 'Datenpfad um {0} geprüft'
    'Footer.PathFailed'      = 'Datenpfad um {0} fehlgeschlagen'
    'Footer.PathPending'     = 'Datenpfad um {0} noch nicht geprüft'
    'Footer.NotElevated'     = 'keine Administratorrechte'
    'Footer.Version'         = 'Version {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Modem entsperren'
    'Confirm.Unlock'               = @'
Modem entsperren?

Dabei wird in den nichtflüchtigen Speicher des Modems geschrieben und eine Einschränkung aufgehoben, die der Hersteller des Laptops für die Funkzertifizierung festgelegt hat. Dies geschieht auf Ihre eigene Verantwortung und funktioniert möglicherweise nicht bei jedem Modul.

Das Modem wird anschließend neu gestartet.
'@
    'Confirm.DisablePinTitle'      = 'PIN von der SIM entfernen'
    'Confirm.DisablePin'           = @'
PIN von der SIM entfernen?

Dies ändert die SIM-Karte, nicht die App: Die SIM fragt nicht mehr nach ihrer PIN, weder in diesem Modem noch in einem Telefon. Eine falsche PIN verbraucht einen ihrer Versuche.
'@
    'Confirm.UnknownDriverTitle'   = 'Unbekannte Treiberversion installieren'
    'Confirm.UnknownDriver'        = @'
Eine Treiberversion installieren, die die App nicht kennt?

Microsoft hat dieses Paket (WHQL) für den AT-Port des Modems signiert, daher akzeptiert Windows es; es ist aber keine Version, die die App kennt.

Windows installiert es für jedes Gerät, zu dem es passt.
'@
    'Confirm.UninstallDriverTitle' = 'Treiber deinstallieren'
    'Confirm.UninstallDriver'      = @'
Den Treiber für den AT-Port des Modems deinstallieren?

Windows entfernt ihn von den seriellen Ports des Modems und aus dem Treiberspeicher. Die Datenverbindung bleibt bestehen, aber die App kann weder mit dem Modem kommunizieren noch die Verbindung überwachen, bis der Treiber erneut installiert ist.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Jetzt prüfen'
    'Xaml.SignalTab'         = 'Signal'
    'Xaml.Cells'             = 'Zellen'
    'Xaml.Cell'              = 'Zelle'
    'Xaml.Band'              = 'Band'
    'Xaml.Channel'           = 'Kanal'
    'Xaml.Bandwidth'         = 'Bandbreite'
    'Xaml.CarrierAggregation' = 'Carrier Aggregation'
    'Xaml.Carrier'           = 'Träger'
    'Xaml.State'             = 'Status'
    'Xaml.BandwidthDlUl'     = 'Bandbreite DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulation DL/UL'
    'Xaml.StorePin'          = 'PIN speichern'
    'Xaml.ForgetPin'         = 'Gespeicherte PIN löschen'
    'Xaml.DisablePin'        = 'PIN von der SIM entfernen...'
    'Xaml.PinNote'           = 'Eine gespeicherte PIN wird verschlüsselt für Ihr Windows-Benutzerkonto aufbewahrt, zusammen mit der SIM, zu der sie gehört. Die App gibt sie einmal ein, wenn diese SIM danach fragt - nie zweimal, nie bei nur einem verbleibenden Versuch und nie eine PUK.'
    'Xaml.NetworkTab'        = 'Netz'
    'Xaml.NetworkMode'       = 'Netzmodus'
    'Xaml.Apply'             = 'Übernehmen'
    'Xaml.Undo'              = 'Rückgängig'
    'Xaml.ModeNote'          = 'Das Modem behält seinen Netzmodus und seine Bänder, auch nachdem die App beendet wurde. Ein Modus wird zuerst getestet: Findet das Modem damit kein Netz, kehrt es zur vorherigen Einstellung zurück.'
    'Xaml.LteAll'            = 'LTE: alle Bänder'
    'Xaml.NrAll'             = 'NR: alle Bänder'
    'Xaml.ConnectionTab'     = 'Verbindung'
    'Xaml.ApnTip'            = 'Leer: der APN Ihres Mobilfunkvertrags.'
    'Xaml.PdpType'           = 'PDP-Typ'
    'Xaml.Authentication'    = 'Authentifizierung'
    'Xaml.AuthNone'          = 'Keine'
    'Xaml.User'              = 'Benutzer'
    'Xaml.Password'          = 'Kennwort'
    'Xaml.ClearPassword'     = 'Gespeichertes Kennwort löschen'
    'Xaml.DnsServers'        = 'DNS-Server'
    'Xaml.DnsTip'            = 'Durch Kommas getrennt. Leer: die des Netzbetreibers.'
    'Xaml.EncryptedDns'      = 'Verschlüsseltes DNS'
    'Xaml.Doh'               = 'DNS over HTTPS zu den obigen Servern oder zu denen der Vorlage - nie unverschlüsselt'
    'Xaml.DohTemplate'       = 'DoH-Vorlage'
    'Xaml.DohTemplateTip'    = 'Leer: die Vorlage, die Windows für jeden Server kennt. Andernfalls eine https-Adresse für alle; ohne DNS-Server ist ihr Name oder ihre Adresse der Server.'
    'Xaml.RefreshBefore'     = 'Server der Vorlage alle'
    'Xaml.RefreshAfter'      = 'Minuten auflösen, wenn kein DNS-Server angegeben ist: Der Name der Vorlage ist der Server.'
    'Xaml.Metric'            = 'Schnittstellenmetrik'
    'Xaml.MetricNote'        = '500 hält das Modem als Reserveverbindung bereit; ein niedriger Wert macht es zur bevorzugten Verbindung.'
    'Xaml.Updates'           = 'Updates'
    'Xaml.UpdateCheck'       = 'Bei jedem Start einmal nach einer neueren Version suchen'
    'Xaml.Save'              = 'Speichern'
    'Xaml.DriverTab'         = 'Treiber'
    'Xaml.OpenPage'          = 'Downloadseite öffnen'
    'Xaml.ChoosePackage'     = 'Heruntergeladenes Paket auswählen...'
    'Xaml.Install'           = 'Installieren'
    'Xaml.UninstallDriver'   = 'Treiber deinstallieren...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Autostart'
    'Xaml.StartAtLogon'               = 'App bei der Anmeldung an Windows im Infobereich starten'
    'Startup.NotInstalled'            = 'Nur die installierte App kann bei der Anmeldung an Windows starten.'
    'Startup.NeedsAdmin'              = 'Zum Ändern sind Administratorrechte erforderlich.'
    'Startup.ObserveOnly'             = 'Die App beobachtet nur und ändert nichts.'
    'Result.SetStartAtLogon.Enabled'  = 'Die App startet jetzt bei der Anmeldung an Windows.'
    'Result.SetStartAtLogon.Disabled' = 'Die App startet nicht mehr bei der Anmeldung an Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Nur die installierte App kann bei der Anmeldung an Windows starten: Es wurde nichts geändert.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Nachrichten'
    'Xaml.From'                     = 'Von'
    'Xaml.Time'                     = 'Zeit'
    'Xaml.Message'                  = 'Nachricht'
    'Xaml.DeleteMessage'            = 'Löschen...'
    'Xaml.NewMessage'               = 'Neue Nachricht'
    'Xaml.To'                       = 'An'
    'Xaml.Send'                     = 'Senden'
    'Xaml.SendNote'                 = 'Jeder Teil ist eine Nachricht, die der Betreiber berechnen kann. Ein fehlgeschlagener Teil wird nie von selbst erneut gesendet.'
    'Messages.TabNew'               = 'Nachrichten ({0})'
    'Messages.Storage'              = '{0} von {1} Plätzen auf der SIM belegt.'
    'Messages.Full'                 = 'Die SIM ist voll: Neue Nachrichten können erst gespeichert werden, wenn einige gelöscht sind.'
    'Messages.Empty'                = 'Keine Nachrichten auf der SIM.'
    'Messages.ObserveOnly'          = 'Solange die App nur beobachtet, werden keine Nachrichten gelesen: Das Lesen markiert sie auf dem Modem als gelesen.'
    'Messages.NoModem'              = 'Das Modem ist nicht angeschlossen.'
    'Messages.NotReady'             = 'Nachrichten werden gelesen, sobald die SIM bereit ist.'
    'Messages.Header'               = 'Von {0}, {1}'
    'Messages.Missing'              = 'Teile (noch) nicht empfangen: {0}.'
    'Messages.Binary'               = 'Diese Nachricht enthält Daten, keinen Text.'
    'Messages.Compressed'           = 'Diese Nachricht ist komprimiert: Die App kann sie nicht anzeigen.'
    'Messages.Malformed'            = 'Diese Nachricht kann nicht gelesen werden.'
    'Messages.NationalLanguage'     = 'Sie verwendet eine nationale Sprachtabelle, die die App nicht hat: Einige Zeichen können falsch sein.'
    'Messages.Silent'               = 'Eine stille Nachricht: Das Netz hat verlangt, dass sie nie angezeigt wird.'
    'Messages.SilentNote'           = 'Sie belegt einen Platz auf der SIM, bis sie gelöscht wird.'
    'Messages.Sending'              = 'Nachricht wird gesendet...'
    'Messages.Count'                = 'Zeichen: {0} - Teile: {1}'
    'Messages.CountUnicode'         = 'Zeichen: {0} - Teile: {1} (mit Sonderzeichen {2} pro Teil)'
    'Messages.TooLong'              = 'Zu lang: Eine Nachricht hat höchstens 255 Teile.'
    'Result.SendMessage.Sent'       = 'Nachricht gesendet.'
    'Result.SendMessage.Failed'     = 'Die Nachricht wurde nicht vollständig gesendet: {0} von {1} Teilen sind hinausgegangen.'
    'Result.SendMessage.Invalid'    = 'Geben Sie eine Telefonnummer und einen Text ein.'
    'Result.DeleteMessage.Done'     = 'Nachricht von der SIM gelöscht.'
    'Result.DeleteMessage.NotFound' = 'Die Nachricht ist nicht mehr auf der SIM.'
    'Result.DeleteMessage.Failed'   = 'Die Nachricht konnte nicht gelöscht werden.'
    'Result.NotReady'               = 'Die SIM ist nicht bereit.'
    'Confirm.DeleteMessageTitle'    = 'Nachricht löschen'
    'Confirm.DeleteMessage'         = @'
Diese Nachricht von der SIM löschen?

Das kann nicht rückgängig gemacht werden.
'@
    'Tray.NewMessage'               = 'Neue Nachricht'
    'Tray.NewMessages'              = '{0} neue Nachrichten'
    'Tray.MessageFrom'              = 'Von {0}'
    'Xaml.DataTab'                  = 'Daten'
    'Xaml.CycleDay'                 = 'Der Abrechnungszeitraum beginnt am Tag'
    'Xaml.Quota'                    = 'Datenkontingent (GB)'
    'Xaml.QuotaNote'                = '0: keines. Bei 80 % und bei 100 % meldet es der Infobereich, einmal pro Zeitraum; die Verbindung bleibt bestehen.'
    'Xaml.UsageNote'                = 'Gezählt am Netzwerkadapter des Modems: ein Schätzwert, der von der Zählung des Betreibers abweichen kann.'
    'Usage.Today'                   = 'Heute: {0} (empfangen {1}, gesendet {2})'
    'Usage.Cycle'                   = 'Dieser Zeitraum, vom {0} bis {1}: {2} (empfangen {3}, gesendet {4})'
    'Usage.Quota'                   = 'Kontingent: {0} von {1} verbraucht ({2} %)'
    'Usage.NoQuota'                 = 'Kein Kontingent festgelegt.'
    'Usage.NotCounted'              = 'Noch nichts gezählt: Der Netzwerkadapter des Modems wurde noch nicht gelesen.'
    'Tray.Usage'                    = 'Daten heute {0}, dieser Zeitraum {1}'
    'Tray.UsageQuota'               = 'Daten heute {0}, dieser Zeitraum {1} von {2}'
    'Tray.QuotaTitle'               = 'Datenkontingent'
    'Tray.Quota'                    = '{0} % des Kontingents in diesem Zeitraum verbraucht. Die Verbindung bleibt bestehen.'
}
