# The app's texts in English: every key the app uses, and the fallback of every other language.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'No modem found on USB.'
    'Reason.DeviceProblem'         = 'Windows reports a problem with the modem''s AT port.'
    'Reason.PortInUse'             = 'Another program is using the modem''s AT port.'
    'Reason.BindFailed'            = 'The modem''s AT port couldn''t be put on Windows'' own WinUSB driver: the app tries again at "Check now", or when the modem is plugged in again.'
    'Reason.BindNotElevated'       = 'Putting the modem''s AT port on Windows'' own WinUSB driver needs administrator rights: start the app as administrator.'
    'Reason.BindRestartNeeded'     = 'The modem''s AT port goes on Windows'' own WinUSB driver at the next restart of Windows.'
    'Reason.PortFailed'            = 'The modem''s AT port can''t be opened.'
    'Reason.SimUnknown'            = 'Reading the SIM.'
    'Reason.NoPin'                 = 'The SIM is waiting for its PIN.'
    'Reason.PinForOtherSim'        = 'The stored PIN belongs to another SIM: enter this SIM''s PIN.'
    'Reason.SimNotIdentified'      = 'The SIM can''t be identified, so the stored PIN is not sent to it.'
    'Reason.PinUnconfirmed'        = 'The last PIN entry got no answer, and the app never tries twice: enter the PIN again.'
    'Reason.LastAttempt'           = 'Only one PIN attempt is left, and the app won''t use it: unlock the SIM in a phone.'
    'Reason.PukRequired'           = 'The SIM is blocked and needs its PUK: unblock it in a phone. The app never enters a PUK.'
    'Reason.NoSim'                 = 'No SIM in the modem.'
    'Reason.SimFailure'            = 'The SIM is not working.'
    'Reason.SimOther'              = 'The SIM is waiting for a code the app doesn''t handle.'
    'Reason.NoProfile'             = 'The eSIM has no profile enabled.'
    'Reason.SimBusy'               = 'The SIM is busy; waiting for it.'
    'Reason.FccLocked'             = 'The modem is locked by its laptop''s maker (FCC lock): its radio stays off.'
    'Reason.NotRegistered'         = 'Not registered on a network.'
    'Reason.NotSearching'          = 'Not registered, and not searching for a network.'
    'Reason.Searching'             = 'Searching for a network.'
    'Reason.Denied'                = 'The network refused the registration.'
    'Reason.Unknown'               = 'Not registered; the reason is not known.'
    'Reason.EmergencyOnly'         = 'Emergency calls only.'
    'Reason.ContextUnknown'        = 'Reading the data connection.'
    'Reason.ApnPasswordUnreadable' = 'The stored APN password can''t be read: enter it again.'
    'Reason.ApnNeeded'             = 'The network gave no internet access to an empty APN: enter your operator''s APN.'
    'Reason.NoAddress'             = 'The data connection has no IPv4 address.'
    'Reason.AdapterDisabled'       = 'The modem''s network adapter is disabled.'
    'Reason.NoAdapter'             = 'The modem''s network adapter is missing.'
    'Reason.NotElevated'           = 'The network adapter can only be configured with administrator rights: start the app as administrator.'
    'Reason.DataPathFailed'        = 'The connection is up, but no traffic gets through.'
    'Reason.DohServerUnresolved'   = 'The DNS-over-HTTPS server''s name has not been looked up yet: the app keeps trying, and leaves the network adapter as the modem set it until then.'
    'Reason.DohNeedsServers'       = 'Encrypted DNS needs DNS servers of your choice: the operator''s don''t speak DNS over HTTPS. The network adapter is not configured until then.'
    'Reason.DohUnavailable'        = 'This Windows can''t encrypt DNS on one adapter - DNS over HTTPS needs Windows 11: turn encrypted DNS off. The network adapter is not configured until then.'
    'Reason.DohTemplateMissing'    = 'Windows knows no DNS-over-HTTPS template for a DNS server of the settings: give one, or choose servers it knows. The network adapter is not configured until then.'
    'Reason.Connected'             = 'Connected.'
    'Reason.Other'                 = 'Not registered ({0}).'
    'Reason.Working'               = 'Working on the connection.'
    'Reason.NoNetworkForMode'      = 'No network found with {0}. No reset finds one: choose a wider network mode.'
    'Reason.NoNetworkForModeBands' = 'No network found with {0} on the LTE bands chosen. No reset finds one: choose a wider network mode.'
    'Reason.Withheld'              = 'The app only observes, so it doesn''t take the next step: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Opening the modem''s AT port.'
    'Action.BindUsb'                 = 'Putting the modem''s AT port on Windows'' own WinUSB driver.'
    'Action.Initialize'              = 'Waiting for the modem to answer.'
    'Action.EnterPin'                = 'Entering the stored PIN.'
    'Action.RadioOn'                 = 'Turning the radio on.'
    'Action.AutoRegister'            = 'Selecting the network automatically.'
    'Action.DefineContext'           = 'Setting up the data connection.'
    'Action.ActivateContext'         = 'Setting up the data connection.'
    'Action.DeactivateContext'       = 'Setting up the data connection.'
    'Action.ConfigureAdapter'        = 'Configuring the network adapter.'
    'Action.ApplyNetworkMode'        = 'Setting the network mode.'
    'ActionInline.OpenPort'          = 'opening the modem''s AT port.'
    'ActionInline.BindUsb'           = 'putting the modem''s AT port on Windows'' own WinUSB driver.'
    'ActionInline.Initialize'        = 'waiting for the modem to answer.'
    'ActionInline.EnterPin'          = 'entering the stored PIN.'
    'ActionInline.RadioOn'           = 'turning the radio on.'
    'ActionInline.AutoRegister'      = 'selecting the network automatically.'
    'ActionInline.DefineContext'     = 'setting up the data connection.'
    'ActionInline.ActivateContext'   = 'setting up the data connection.'
    'ActionInline.DeactivateContext' = 'setting up the data connection.'
    'ActionInline.ConfigureAdapter'  = 'configuring the network adapter.'
    'ActionInline.ApplyNetworkMode'  = 'setting the network mode.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = '4G only'
    'Mode.NrOnly'                  = '5G only (SA)'
    'Mode.NotManaged'              = 'As the modem has it'
    'Mode.Other'                   = 'mode {0}'
    'ModeProblem.NotKept'          = 'The modem doesn''t keep the network mode as written; the app doesn''t write it again.'
    'ModeProblem.NoSupportedBand'  = 'The modem supports none of the bands chosen for one of its RATs.'
    'ModeProblem.ModeUnsupported'  = 'The modem doesn''t support this network mode.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Checking the connection now.'
    'Result.SaveSettings.Done'              = 'Settings saved.'
    'Result.SaveSettings.NoSim'             = 'No SIM is ready: the settings were not saved, as the APN settings belong to the SIM in use.'
    'Result.SaveSettings.SimChanged'        = 'The SIM in use has changed: the settings were not saved. Check its APN settings and save again.'
    'Result.SaveSimPin.Done'                = 'PIN stored: the app enters it once when the SIM asks for it.'
    'Result.SaveSimPin.SimNotIdentified'    = 'The SIM can''t be identified: the PIN was not stored.'
    'Result.ForgetSimPin.Done'              = 'The stored PIN is deleted.'
    'Result.DisableSimPin.Disabled'         = 'The SIM no longer asks for its PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'The SIM''s PIN request was already off.'
    'Result.DisableSimPin.PinRejected'      = 'Wrong PIN: the SIM still asks for it.'
    'Result.DisableSimPin.LastAttempt'      = 'Only one PIN attempt is left: nothing was sent.'
    'Result.DisableSimPin.SimNotReady'      = 'The SIM is not ready: nothing was sent.'
    'Result.DisableSimPin.Failed'           = 'The SIM''s PIN request could not be changed.'
    'Result.UnlockFcc.Restarted'            = 'Unlock sent: the modem is restarting.'
    'Result.UnlockFcc.NotLocked'            = 'The modem is not locked: nothing was written.'
    'Result.UnlockFcc.Unknown'              = 'The lock can''t be read: nothing was written.'
    'Result.UnlockFcc.Failed'               = 'The unlock stopped before the restart.'
    'Result.UnlockFcc.PortLost'             = 'The modem left USB during the unlock.'
    'Result.EnableAdapter.Done'             = 'Network adapter enabled.'
    'Result.SetNetworkMode.Applied'         = 'Network mode sent: the modem is registering again. It is kept once the modem finds a network with it.'
    'Result.SetNetworkMode.Unchanged'       = 'The modem already has this network mode: it is kept.'
    'Result.SetNetworkMode.Done'            = 'The app no longer manages the network mode: the modem keeps the one it has.'
    'Result.SetNetworkMode.ModeUnsupported' = 'The modem doesn''t support this network mode: nothing was written.'
    'Result.SetNetworkMode.NoSupportedBand' = 'The modem supports none of the bands chosen for one of its RATs: nothing was written.'
    'Result.SetNetworkMode.Unknown'         = 'The modem''s network mode can''t be read: nothing was written.'
    'Result.NotElevated'                    = 'That needs administrator rights.'
    'Result.Refused'                        = 'Not available while the app only observes.'
    'Result.NoModem'                        = 'The modem is not connected.'
    'Result.PortLost'                       = 'The modem left USB during the command.'
    'Result.Failed'                         = 'It didn''t work.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Attempts left: {0}.'
    'Result.Restarting'                     = 'The monitor is restarting: try again in a moment.'

    # The headline.
    'Tone.Online'         = 'Online'
    'Tone.Working'        = 'Connecting'
    'Tone.Recovering'     = 'Recovering'
    'Tone.Attention'      = 'Action needed'
    'Tone.Offline'        = 'No modem'
    'Tone.Stopped'        = 'Not monitoring'
    'Title.ConnectionLost' = 'Connection lost'
    'Title.NoNetwork'     = 'No network'
    'Title.NotConnected'  = 'Not connected'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'The modem is not on USB.'
    'Check.H2'          = 'The modem doesn''t answer.'
    'Check.H3'          = 'The SIM is not ready.'
    'Check.H4'          = 'Not registered on a network.'
    'Check.H5'          = 'The data connection is down.'
    'Check.H6'          = 'The network adapter is not configured.'
    'Check.H7'          = 'No traffic gets through.'
    'Check.Other'       = 'The connection is down.'
    'Step.R1'           = 'Configuring the network adapter again.'
    'Step.R2'           = 'Restarting the data connection.'
    'Step.R3'           = 'Registering on the network again.'
    'Step.R4'           = 'Turning the radio off and on.'
    'Step.R5'           = 'Restarting the modem.'
    'Step.R6'           = 'Restarting the modem''s USB device.'
    'StepInline.R1'     = 'configuring the network adapter again.'
    'StepInline.R2'     = 'restarting the data connection.'
    'StepInline.R3'     = 'registering on the network again.'
    'StepInline.R4'     = 'turning the radio off and on.'
    'StepInline.R5'     = 'restarting the modem.'
    'StepInline.R6'     = 'restarting the modem''s USB device.'
    'Recovery.Waiting'  = '{0} The recovery steps didn''t help: they start again at {1}.'
    'Recovery.Slow'     = '{0} Recovery failed {1} times: the app tries again at {2}.'
    'Recovery.Withheld' = '{0} The app only observes, so it doesn''t take the recovery step: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Open'
    'Tray.CheckNow'       = 'Check now'
    'Tray.NetworkMode'    = 'Network mode'
    'Tray.NetworkModeNow' = 'Network mode: {0}'
    'Tray.Exit'           = 'Exit'
    'Tray.Update'         = 'Version {0} is available...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Use {0}, every band'
    'Blocker.SaveApn'       = 'Save APN'
    'Blocker.SavePassword'  = 'Save password'
    'Blocker.StorePin'      = 'Store PIN'
    'Blocker.EnableAdapter' = 'Enable adapter'
    'Blocker.Unlock'        = 'Unlock...'
    'Blocker.OpenSettings'  = 'Open the settings'
    'Blocker.ObserveOnly'   = 'The app only observes: it changes nothing.'
    'Blocker.NeedsAdmin'    = 'Enabling it needs administrator rights.'
    'Blocker.UnlockNote'    = 'Unlocking writes the modem''s non-volatile memory: the app asks before it does.'
    'Blocker.AttemptsLeft'  = 'Attempts left: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Ready'
    'Sim.PinRequired'    = 'Waiting for its PIN'
    'Sim.PukRequired'    = 'Blocked: needs its PUK'
    'Sim.Absent'         = 'No SIM'
    'Sim.Busy'           = 'Busy'
    'Sim.Failure'        = 'Not working'
    'Sim.Other'          = 'Waiting for another code'
    'Sim.NoProfile'      = 'eSIM with no profile enabled'
    'Sim.Unknown'        = 'Not known'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - PIN attempts left: {1}'
    'Sim.RequestOn'      = 'PIN request at power-on: on'
    'Sim.RequestOff'     = 'PIN request at power-on: off'
    'Sim.RequestUnknown' = 'PIN request at power-on: not known'
    'Sim.Stored'         = 'A PIN is stored for this SIM.'
    'Sim.NotStored'      = 'No PIN is stored.'
    'Sim.Rejected'       = 'The stored PIN was rejected and deleted: the app never tries it again.'

    # The network tab.
    'Bands.Every'       = 'every band'
    'Bands.EveryBut'    = 'every band but {0}'
    'Bands.None'        = 'none'
    'Network.Current'   = 'The modem now: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'The modem''s network mode is not read yet.'
    'Network.Trial'     = 'Trying {0}: if the modem finds no network with it by {1}, it goes back to what it had.'
    'Network.Reverted'  = 'At {0} the modem had found no network with {1}: it went back to what it had.'
    'Network.Kept'      = 'At {0} the modem registered with {1}: it is kept.'
    'Network.Missing'   = 'The modem leaves out {0}, though asked: it uses the other bands chosen.'
    'Network.ChooseBand' = 'Choose at least one {0} band, or every band.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Encrypted DNS is not available on this Windows: DNS over HTTPS on one adapter needs Windows 11.'
    'Dns.On'                   = 'Encrypted DNS is on: {0}.'
    'Dns.Waiting'              = 'Encrypted DNS waits for its server''s address: no DNS server is set meanwhile.'
    'Dns.Off'                  = 'Encrypted DNS is off.'
    'Dns.Advertised'           = 'The network also gives IPv6 DNS servers ({0}), which Windows may use in the clear.'
    'Dns.LookupFailed'         = '{0} can''t be looked up; the app keeps trying.'
    'Dns.LookingUp'            = 'Looking up {0}...'
    'Dns.LookedUp'             = 'Its server, {0}, was looked up at {1}.'
    'Dns.LookedUpNext'         = 'Its server, {0}, was looked up at {1}; again at {2}.'
    'Dns.LookedUpOperator'     = 'Its server, {0}, was looked up at {1} through the operator''s DNS, in the clear.'
    'Dns.LookedUpOperatorNext' = 'Its server, {0}, was looked up at {1} through the operator''s DNS, in the clear; again at {2}.'
    'Dns.NotAvailableHere'     = 'Encrypted DNS is not available on this Windows.'
    'Dns.NoTemplate'           = 'Windows knows no DNS-over-HTTPS template for {0}: give one.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; the default is used.'
    'Setting.Unknown'          = 'Unknown setting ''{0}'' is ignored.'
    'Setting.Unreadable'       = 'The settings file can''t be read; the defaults are used.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps needs DnsServers, or a DohTemplate that names the server: the operator''s servers speak no DoH, and no DNS server is set until there is one.'
    'Setting.TemplateAddress'  = 'DohTemplate names the address {0}, so it can serve only that server; the default is used.'
    'Rule.Text'                = 'must be printable ASCII without double quotes or surrounding blanks'
    'Rule.TextQuotes'          = 'must be printable ASCII without double quotes'
    'Rule.OneOf'               = 'must be one of {0}'
    'Rule.EmptyOrOneOf'        = 'must be empty or one of {0}'
    'Rule.Addresses'           = 'must be a list of IP addresses'
    'Rule.Number'              = 'must be a whole number from {0} to {1}'
    'Rule.Minutes'             = 'must be a whole number of minutes from {0} to {1}'
    'Rule.Bool'                = 'must be true or false'
    'Rule.Https'               = 'must be empty or an https address without blanks, quotes or credentials'
    'Rule.Bands'               = 'must be a list of distinct band numbers from {0} to {1}'
    'Rule.Gigabytes'           = 'must be a number of gigabytes from {0} to {1}, 0 for none'

    # The USB tab.
    'Usb.Present'                 = 'The modem''s AT port is on Windows'' own WinUSB driver: there is no driver to install.'
    'Usb.Unbound'                 = 'The modem''s AT port is not on Windows'' own WinUSB driver yet: the app puts it there.'
    'Usb.NotLooked'               = 'The modem''s functions are not looked at yet.'
    'Usb.FunctionName'            = '{0} (MI_{1})'
    'Usb.FunctionLine'            = '{0}: {1}'
    'Usb.Function.MdAt'           = 'AT port'
    'Usb.Function.MdMeta'         = 'Modem META port'
    'Usb.Function.ApMeta'         = 'AP META port'
    'Usb.Function.ApLog'          = 'AP log port'
    'Usb.Function.ApGnss'         = 'GNSS port'
    'Usb.Function.Npt'            = 'NPT port'
    'Usb.Function.Debug'          = 'Debug port'
    'Usb.Function.Other'          = 'Function'
    'Usb.OnWinUsb'                = 'WinUSB'
    'Usb.OtherDriver'             = 'another driver'
    'Usb.NoDriver'                = 'no driver'
    'Usb.ProblemCode'             = '{0}, problem code {1}'
    'Usb.LastChange'              = 'Last change at {0}:'
    'Usb.Bound'                   = '{0}: put on WinUSB.'
    'Usb.Held'                    = '{0}: left on its driver, another program holds its port.'
    'Usb.Failed'                  = '{0}: not put on WinUSB ({1}).'
    'Usb.RestartNeeded'           = '{0}: on WinUSB at the next restart of Windows.'
    'Usb.ObserveOnly'             = 'The app only observes: it puts no function on WinUSB.'
    'Usb.NeedsAdmin'              = 'Putting the modem''s functions on WinUSB needs administrator rights: start the app as administrator.'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'The monitor stopped and is restarting. The connection is not touched.'
    'Window.NotResponding'   = 'The monitor is not responding. The connection is not touched.'
    'Window.Starting'        = 'Starting.'
    'Window.Simulated'       = 'Development mode: a simulated modem (scenario {0}).'
    'Window.ObserveOnly'     = 'The app only observes: it changes nothing on the modem or the system.'
    'Window.SettingsPending' = 'The data connection is up with other settings: the new ones apply at the next connection.'
    'Window.SettingsFile'    = 'Settings file: {0}'
    'Window.Modems'          = '{0} modems found: the app uses one of them, always the same.'
    'Window.Recovered'       = 'Recovered at {0}: {1}'
    'Window.NrAvailable'     = '{0}, 5G available'
    'Window.NothingMeasured' = 'Nothing measured.'
    'Window.PasswordStored'  = 'A password is stored.'
    'Window.NoPassword'      = 'No password is stored.'
    'Window.ApnPerSim'       = 'Each SIM keeps its own APN settings: these are the SIM in use''s.'
    'Window.ApnNoSim'        = 'Each SIM keeps its own APN settings: they can be changed once a SIM is ready.'
    'Window.PinFirst'        = 'Type the SIM''s PIN first: removing it needs the PIN.'
    'Cell.Serving'           = 'Serving'
    'Cell.Neighbour'         = 'Neighbour'
    'Carrier.Primary'        = 'Primary'
    'Carrier.Active'         = 'Active'
    'Carrier.Inactive'       = 'Inactive'
    'Footer.Port'            = 'AT port on {0}'
    'Footer.PortClosed'      = 'AT port closed'
    'Footer.Updated'         = 'updated {0}'
    'Footer.PathChecked'     = 'data path checked at {0}'
    'Footer.PathFailed'      = 'data path failed at {0}'
    'Footer.PathPending'     = 'data path not checked yet at {0}'
    'Footer.NotElevated'     = 'no administrator rights'
    'Footer.Version'         = 'version {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Unlock the modem'
    'Confirm.Unlock'               = @'
Unlock the modem?

This writes the modem's non-volatile memory and lifts a restriction that the laptop's maker set for its radio certification. It is done at your own responsibility, and it may not work on every module.

The modem restarts afterwards.
'@
    'Confirm.DisablePinTitle'      = 'Remove the PIN from the SIM'
    'Confirm.DisablePin'           = @'
Remove the PIN from the SIM?

This changes the SIM card, not the app: the SIM will no longer ask for its PIN, in this modem or in any phone. A wrong PIN uses up one of its attempts.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Check now'
    'Xaml.SignalTab'         = 'Signal'
    'Xaml.Cells'             = 'Cells'
    'Xaml.Cell'              = 'Cell'
    'Xaml.Band'              = 'Band'
    'Xaml.Channel'           = 'Channel'
    'Xaml.Bandwidth'         = 'Bandwidth'
    'Xaml.CarrierAggregation' = 'Carrier aggregation'
    'Xaml.Carrier'           = 'Carrier'
    'Xaml.State'             = 'State'
    'Xaml.BandwidthDlUl'     = 'Bandwidth DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulation DL/UL'
    'Xaml.StorePin'          = 'Store PIN'
    'Xaml.ForgetPin'         = 'Forget the stored PIN'
    'Xaml.DisablePin'        = 'Remove the PIN from the SIM...'
    'Xaml.PinNote'           = 'A stored PIN is kept encrypted for your Windows user, with the SIM it belongs to. The app enters it once when that SIM asks for it - never twice, never with one attempt left, and never a PUK.'
    'Xaml.NetworkTab'        = 'Network'
    'Xaml.NetworkMode'       = 'Network mode'
    'Xaml.Apply'             = 'Apply'
    'Xaml.Undo'              = 'Undo changes'
    'Xaml.ModeNote'          = 'The modem keeps its network mode and bands, after the app exits too. A mode is tried first: if the modem finds no network with it, it goes back to what it had.'
    'Xaml.LteAll'            = 'LTE: every band'
    'Xaml.NrAll'             = 'NR: every band'
    'Xaml.ConnectionTab'     = 'Connection'
    'Xaml.ApnTip'            = 'Empty: the one of your subscription.'
    'Xaml.PdpType'           = 'PDP type'
    'Xaml.Authentication'    = 'Authentication'
    'Xaml.AuthNone'          = 'None'
    'Xaml.User'              = 'User'
    'Xaml.Password'          = 'Password'
    'Xaml.ClearPassword'     = 'Delete the stored password'
    'Xaml.DnsServers'        = 'DNS servers'
    'Xaml.DnsTip'            = 'Separated by commas. Empty: the operator''s.'
    'Xaml.EncryptedDns'      = 'Encrypted DNS'
    'Xaml.Doh'               = 'DNS over HTTPS to the servers above, or to the template''s - never in the clear'
    'Xaml.DohTemplate'       = 'DoH template'
    'Xaml.DohTemplateTip'    = 'Empty: the template Windows knows for each server. Otherwise one https address for all of them; without DNS servers, its name or address is the server.'
    'Xaml.RefreshBefore'     = 'Look its server up every'
    'Xaml.RefreshAfter'      = 'minutes, when no DNS server is given: the template''s name is the server.'
    'Xaml.Metric'            = 'Interface metric'
    'Xaml.MetricNote'        = '500 keeps the modem a backup connection; a low value makes it the preferred one.'
    'Xaml.Updates'           = 'Updates'
    'Xaml.UpdateCheck'       = 'Look for a newer release once per start'
    'Xaml.Save'              = 'Save'
    'Xaml.UsbTab'            = 'USB'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Startup'
    'Xaml.StartAtLogon'               = 'Start the app in the tray when you sign in to Windows'
    'Startup.NotInstalled'            = 'Only the installed app can start when you sign in to Windows.'
    'Startup.NeedsAdmin'              = 'Changing it needs administrator rights.'
    'Startup.ObserveOnly'             = 'The app only observes: it changes nothing.'
    'Result.SetStartAtLogon.Enabled'  = 'The app now starts when you sign in to Windows.'
    'Result.SetStartAtLogon.Disabled' = 'The app no longer starts when you sign in to Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Only the installed app can start when you sign in to Windows: nothing was changed.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Messages'
    'Xaml.From'                     = 'From'
    'Xaml.Time'                     = 'Time'
    'Xaml.Message'                  = 'Message'
    'Xaml.DeleteMessage'            = 'Delete...'
    'Xaml.NewMessage'               = 'New message'
    'Xaml.To'                       = 'To'
    'Xaml.Send'                     = 'Send'
    'Xaml.SendNote'                 = 'Each part is a message, which the operator may charge for. A part that fails is never sent again by itself.'
    'Messages.TabNew'               = 'Messages ({0})'
    'Messages.Storage'              = '{0} of {1} places used on the SIM.'
    'Messages.Full'                 = 'The SIM is full: new messages can''t be stored until some are deleted.'
    'Messages.Empty'                = 'No messages on the SIM.'
    'Messages.Hidden'               = 'Messages that came in on another eSIM profile, shown when it is in use: {0}.'
    'Messages.ObserveOnly'          = 'Messages are not read while the app only observes: reading them marks them read on the modem.'
    'Messages.NoModem'              = 'The modem is not connected.'
    'Messages.NotReady'             = 'Messages are read once the SIM is ready.'
    'Messages.Header'               = 'From {0}, {1}'
    'Messages.Missing'              = 'Parts not received (yet): {0}.'
    'Messages.Binary'               = 'This message carries data, not text.'
    'Messages.Compressed'           = 'This message is compressed: the app can''t show it.'
    'Messages.Malformed'            = 'This message can''t be read.'
    'Messages.NationalLanguage'     = 'It uses a national language table the app doesn''t have: some characters may be wrong.'
    'Messages.Silent'               = 'A silent message: the network asked that it never be shown.'
    'Messages.SilentNote'           = 'It takes a place on the SIM until it is deleted.'
    'Messages.Sending'              = 'Sending the message...'
    'Messages.From'                 = 'A message goes out from the SIM in use: the modem uses one at a time. To send from the other one, put it in use from the SIM or eSIM tab.'
    'Messages.FromGoneProfile'      = 'It came in on the eSIM profile {0}, not in use now.'
    'Messages.FromOtherProfile'     = 'It came in on another eSIM profile, not in use now.'
    'Messages.FromOtherSim'         = 'It came in on another SIM, not in use now.'
    'Messages.Count'                = 'Characters: {0} - parts: {1}'
    'Messages.CountUnicode'         = 'Characters: {0} - parts: {1} (with special characters, {2} per part)'
    'Messages.TooLong'              = 'Too long: a message has at most 255 parts.'
    'Result.SendMessage.Sent'       = 'Message sent.'
    'Result.SendMessage.Failed'     = 'The message was not sent completely: {0} of {1} parts went out.'
    'Result.SendMessage.Invalid'    = 'Enter a phone number and a text.'
    'Result.DeleteMessage.Done'     = 'Message deleted from the SIM.'
    'Result.DeleteMessage.NotFound' = 'The message is no longer on the SIM.'
    'Result.DeleteMessage.Failed'   = 'The message could not be deleted.'
    'Result.NotReady'               = 'The SIM is not ready.'
    'Confirm.DeleteMessageTitle'    = 'Delete the message'
    'Confirm.DeleteMessage'         = @'
Delete this message from the SIM?

It can't be undone.
'@
    'Tray.NewMessage'               = 'New message'
    'Tray.NewMessages'              = '{0} new messages'
    'Tray.MessageFrom'              = 'From {0}'
    'Xaml.DataTab'                  = 'Data'
    'Xaml.CycleDay'                 = 'The billing cycle starts on day'
    'Xaml.Quota'                    = 'Data quota (GB)'
    'Xaml.QuotaNote'                = '0: none. At 80% and at 100% of it the tray says so, once per cycle; the connection stays on.'
    'Xaml.UsageNote'                = 'Counted from the modem''s network adapter: an estimate, which may differ from the operator''s count.'
    'Usage.Today'                   = 'Today: {0} (received {1}, sent {2})'
    'Usage.Cycle'                   = 'This cycle, from {0} to {1}: {2} (received {3}, sent {4})'
    'Usage.Quota'                   = 'Quota: {0} of {1} used ({2}%)'
    'Usage.NoQuota'                 = 'No quota set.'
    'Usage.NotCounted'              = 'Nothing counted yet: the modem''s network adapter has not been read.'
    'Tray.Usage'                    = 'Data today {0}, this cycle {1}'
    'Tray.UsageQuota'               = 'Data today {0}, this cycle {1} of {2}'
    'Tray.QuotaTitle'               = 'Data quota'
    'Tray.Quota'                    = '{0}% of the quota used in this cycle. The connection stays on.'

    # The eSIM tab and the SIM in use (M9).
    'Xaml.EsimTab'                              = 'eSIM'
    'Xaml.EsimProfiles'                         = 'Profiles'
    'Xaml.EsimName'                             = 'Name'
    'Xaml.EsimProvider'                         = 'Provider'
    'Xaml.EsimKind'                             = 'Kind'
    'Xaml.EsimNickname'                         = 'Nickname'
    'Xaml.EsimEnable'                           = 'Enable...'
    'Xaml.EsimDisable'                          = 'Disable...'
    'Xaml.EsimDelete'                           = 'Delete...'
    'Xaml.EsimRename'                           = 'Rename'
    'Xaml.EsimReadAgain'                        = 'Read again'
    'Xaml.EsimCopy'                             = 'Copy'
    'Xaml.EsimDownload'                         = 'Download a profile'
    'Xaml.EsimCode'                             = 'Activation code (LPA:1$...), as the provider gave it'
    'Xaml.EsimReadQr'                           = 'Read a QR code...'
    'Xaml.EsimConfirmation'                     = 'Confirmation code, if the provider gave one'
    'Xaml.EsimDownloadButton'                   = 'Download'
    'Xaml.EsimDownloadNote'                     = 'A download sends the eSIM''s EID to the provider''s server the code names. The profile is downloaded disabled: enable it to use it.'
    'SimInUse.Physical'                         = 'SIM in use: slot {0}, a physical SIM.'
    'SimInUse.Esim'                             = 'SIM in use: slot {0}, the eSIM - {1}.'
    'SimInUse.EsimEmpty'                        = 'SIM in use: slot {0}, the eSIM, no profile enabled.'
    'SimInUse.EsimUnread'                       = 'SIM in use: slot {0}, the eSIM.'
    'SimInUse.Slot'                             = 'SIM in use: slot {0}.'
    'Sim.UsePhysical'                           = 'Use the physical SIM (slot {0})...'
    'Sim.PhysicalInUse'                         = 'In use: the physical SIM (slot {0})'
    'Esim.UseEsim'                              = 'Use the eSIM (slot {0})...'
    'Esim.EsimInUse'                            = 'In use: the eSIM (slot {0})'
    'Sim.OneAtATime'                            = 'The modem uses one SIM at a time: the physical SIM (slot {0}) or the eSIM (slot {1}). The SIM tab puts the physical SIM in use, the eSIM tab the eSIM; the switch drops the connection for a moment.'
    'Esim.Unnamed'                              = '(no name)'
    'Esim.NoModem'                              = 'The modem is not connected.'
    'Esim.NoSlot'                               = 'The SIM slot in use has not been read yet.'
    'Esim.NotInUse'                             = 'The eSIM''s profiles can be managed only while its slot is in use.'
    'Esim.NoLpac'                               = 'lpac is not installed with the app: the eSIM''s profiles can''t be managed.'
    'Esim.ReadFailed'                           = 'The eSIM could not be read: {0}'
    'Esim.NotRead'                              = 'The eSIM has not been read yet.'
    'Esim.NoProfiles'                           = 'The eSIM holds no profile.'
    'Esim.ObserveOnly'                          = 'The app only observes: it changes nothing.'
    'Esim.Chip'                                 = 'eUICC: SGP.22 {0}, firmware {1}, {2} free.'
    'Esim.Notifications'                        = 'Notifications waiting for the providers'' servers: {0}. They are sent at the next read.'
    'Esim.Operation.ReadEsim'                   = 'Reading the eSIM...'
    'Esim.Operation.SelectSimSlot'              = 'Changing the SIM slot...'
    'Esim.Operation.EnableProfile'              = 'Enabling the profile...'
    'Esim.Operation.DisableProfile'             = 'Disabling the profile...'
    'Esim.Operation.SetProfileNickname'         = 'Saving the nickname...'
    'Esim.Operation.DeleteProfile'              = 'Deleting the profile...'
    'Esim.Operation.DownloadProfile'            = 'Downloading the profile: this can take a minute...'
    'Esim.State.Enabled'                        = 'Enabled'
    'Esim.State.Disabled'                       = 'Disabled'
    'Esim.State.Unknown'                        = 'Unknown'
    'Esim.Class.Operational'                    = 'Operator'
    'Esim.Class.Test'                           = 'Test'
    'Esim.Class.Provisioning'                   = 'Provisioning'
    'Esim.Class.Unknown'                        = 'Unknown'
    'Esim.QrTitle'                              = 'Choose the image of the QR code'
    'Esim.QrKind'                               = 'Images'
    'Esim.QrChosen'                             = 'QR code image: {0}. Its code is read when the download starts.'
    'Esim.QrMissing'                            = 'Reading QR codes is not installed with the app: type or paste the code.'
    'Esim.CodeFirst'                            = 'Type or paste the activation code, or choose the image of its QR code, first.'
    'Esim.NicknameInvalid'                      = 'A nickname takes 64 bytes at most - fewer with letters beyond A to Z - and no control characters.'
    'Esim.CopyFailed'                           = 'The EID could not be copied: select it and copy it with Ctrl+C.'
    'Blocker.OpenEsim'                          = 'Open eSIM'
    'Confirm.SelectSlotTitle'                   = 'Change the SIM slot'
    'Confirm.SelectSlot'                        = @'
Use SIM slot {0}?

The modem keeps this choice, after the app exits and across restarts. The connection drops while the SIM changes. If the slot holds the eSIM and none of its profiles is enabled, there is no network until you enable one.
'@
    'Confirm.EnableProfileTitle'                = 'Enable an eSIM profile'
    'Confirm.EnableProfile'                     = @'
Enable the profile "{0}"?

The SIM restarts with it: the connection drops for a few seconds, then the modem registers with the new profile. The profile enabled until now is disabled.
'@
    'Confirm.DisableProfileTitle'               = 'Disable an eSIM profile'
    'Confirm.DisableProfile'                    = @'
Disable the profile "{0}"?

The SIM restarts without it: with no profile enabled, there is no network until you enable one.
'@
    'Confirm.DeleteProfileTitle'                = 'Delete an eSIM profile'
    'Confirm.DeleteProfile'                     = @'
Delete the profile "{0}" from the eSIM?

This can't be undone: to have it back, the provider must give you a new activation code. Type the profile's name to confirm.
'@
    'Confirm.Delete'                            = 'Delete'
    'Confirm.Cancel'                            = 'Cancel'
    'Result.ReadEsim.Done'                      = 'eSIM read.'
    'Result.ReadEsim.Failed'                    = 'The eSIM could not be read.'
    'Result.SelectSimSlot.Done'                 = 'SIM slot changed: the modem keeps it.'
    'Result.SelectSimSlot.Unchanged'            = 'That slot is already in use.'
    'Result.SelectSimSlot.Failed'               = 'The SIM slot could not be changed.'
    'Result.EnableProfile.Done'                 = 'Profile enabled: the SIM restarts with it.'
    'Result.EnableProfile.Unchanged'            = 'That profile is already enabled.'
    'Result.EnableProfile.Failed'               = 'The profile could not be enabled.'
    'Result.DisableProfile.Done'                = 'Profile disabled: the SIM restarts without it.'
    'Result.DisableProfile.Unchanged'           = 'That profile is not enabled.'
    'Result.DisableProfile.Failed'              = 'The profile could not be disabled.'
    'Result.DeleteProfile.Done'                 = 'Profile deleted.'
    'Result.DeleteProfile.ProfileEnabled'       = 'An enabled profile can''t be deleted: disable it first.'
    'Result.DeleteProfile.Failed'               = 'The profile could not be deleted.'
    'Result.SetProfileNickname.Done'            = 'Nickname saved.'
    'Result.SetProfileNickname.Failed'          = 'The nickname could not be saved.'
    'Result.DownloadProfile.Done'               = 'Profile downloaded: enable it to use it.'
    'Result.DownloadProfile.Failed'             = 'The profile could not be downloaded.'
    'Result.DownloadProfile.ConfirmationNeeded' = 'This activation code asks for a confirmation code: the provider gives it with the code.'
    'Result.DownloadProfile.BadCode'            = 'This is not an eSIM activation code.'
    'Result.DownloadProfile.BadCode.Empty'      = 'Type or paste the activation code first.'
    'Result.DownloadProfile.BadCode.Format'     = 'This is not an eSIM activation code: one starts with LPA:1$.'
    'Result.DownloadProfile.BadCode.Address'    = 'The activation code names no valid server.'
    'Result.DownloadProfile.BadCode.MatchingId' = 'The activation code''s matching ID holds characters it can''t have.'
    'Result.DownloadProfile.NoQrCode'           = 'No activation code could be read from the image.'
    'Result.DownloadProfile.NoQrCode.NotImage'  = 'The file chosen is not an image the app can read.'
    'Result.DownloadProfile.NoQrCode.TooLarge'  = 'The image is too large: 20 MB and 50 megapixels at most.'
    'Result.DownloadProfile.NoQrCode.NoLibrary' = 'Reading QR codes is not installed with the app: type or paste the code.'
    'Result.DownloadProfile.NoQrCode.NoCode'    = 'No QR code found in the image.'
    'Result.NotEuicc'                           = 'The eSIM is not the SIM in use.'
    'Result.NoLpac'                             = 'lpac is not installed with the app.'
    'Result.UnknownProfile'                     = 'That profile is no longer on the eSIM.'
    'Result.TrialOn'                            = 'Not now: a network mode is on trial.'
    'Result.Timeout'                            = 'It took too long, and was stopped.'
}
