# The app's texts in English: every key the app uses, and the fallback of every other language.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'No modem found on USB.'
    'Reason.NoDriver'              = 'The modem''s AT port has no driver: the app can''t talk to the modem until it is installed.'
    'Reason.DeviceProblem'         = 'Windows reports a problem with the modem''s AT port.'
    'Reason.PortInUse'             = 'Another program is using the modem''s AT port.'
    'Reason.PortFailed'            = 'The modem''s AT port can''t be opened.'
    'Reason.SimUnknown'            = 'Reading the SIM.'
    'Reason.NoPin'                 = 'The SIM is waiting for its PIN.'
    'Reason.PinForOtherSim'        = 'The stored PIN belongs to another SIM: enter this SIM''s PIN.'
    'Reason.SimNotIdentified'      = 'The SIM can''t be identified, so the stored PIN is not sent to it.'
    'Reason.PinUnconfirmed'        = 'The last PIN entry got no answer, and the app never tries twice: enter the PIN again.'
    'Reason.LastAttempt'           = 'Only one PIN attempt is left, and the app won''t use it: unlock the SIM in a phone.'
    'Reason.PukRequired'           = 'The SIM is blocked and needs its PUK: unblock it in a phone. The app never enters a PUK.'
    'Reason.NoSim'                 = 'No SIM in the modem.'
    'Reason.SimFailure'            = 'The SIM is not working.'
    'Reason.SimOther'              = 'The SIM is waiting for a code the app doesn''t handle.'
    'Reason.SimBusy'               = 'The SIM is busy; waiting for it.'
    'Reason.FccLocked'             = 'The modem is locked by its laptop''s maker (FCC lock): its radio stays off.'
    'Reason.NotRegistered'         = 'Not registered on a network.'
    'Reason.NotSearching'          = 'Not registered, and not searching for a network.'
    'Reason.Searching'             = 'Searching for a network.'
    'Reason.Denied'                = 'The network refused the registration.'
    'Reason.Unknown'               = 'Not registered; the reason is not known.'
    'Reason.EmergencyOnly'         = 'Emergency calls only.'
    'Reason.ContextUnknown'        = 'Reading the data connection.'
    'Reason.ApnPasswordUnreadable' = 'The stored APN password can''t be read: enter it again.'
    'Reason.ApnNeeded'             = 'The network gave no internet access to an empty APN: enter your operator''s APN.'
    'Reason.NoAddress'             = 'The data connection has no IPv4 address.'
    'Reason.AdapterDisabled'       = 'The modem''s network adapter is disabled.'
    'Reason.NoAdapter'             = 'The modem''s network adapter is missing.'
    'Reason.NotElevated'           = 'The network adapter can only be configured with administrator rights: start the app as administrator.'
    'Reason.DataPathFailed'        = 'The connection is up, but no traffic gets through.'
    'Reason.DohServerUnresolved'   = 'The DNS-over-HTTPS server''s name has not been looked up yet: the app keeps trying, and leaves the network adapter as the modem set it until then.'
    'Reason.DohNeedsServers'       = 'Encrypted DNS needs DNS servers of your choice: the operator''s don''t speak DNS over HTTPS. The network adapter is not configured until then.'
    'Reason.DohUnavailable'        = 'This Windows can''t encrypt DNS on one adapter - DNS over HTTPS needs Windows 11: turn encrypted DNS off. The network adapter is not configured until then.'
    'Reason.DohTemplateMissing'    = 'Windows knows no DNS-over-HTTPS template for a DNS server of the settings: give one, or choose servers it knows. The network adapter is not configured until then.'
    'Reason.Connected'             = 'Connected.'
    'Reason.Other'                 = 'Not registered ({0}).'
    'Reason.Working'               = 'Working on the connection.'
    'Reason.NoNetworkForMode'      = 'No network found with {0}. No reset finds one: choose a wider network mode.'
    'Reason.NoNetworkForModeBands' = 'No network found with {0} on the LTE bands chosen. No reset finds one: choose a wider network mode.'
    'Reason.Withheld'              = 'The app only observes, so it doesn''t take the next step: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Opening the modem''s AT port.'
    'Action.Initialize'              = 'Waiting for the modem to answer.'
    'Action.EnterPin'                = 'Entering the stored PIN.'
    'Action.RadioOn'                 = 'Turning the radio on.'
    'Action.AutoRegister'            = 'Selecting the network automatically.'
    'Action.DefineContext'           = 'Setting up the data connection.'
    'Action.ActivateContext'         = 'Setting up the data connection.'
    'Action.DeactivateContext'       = 'Setting up the data connection.'
    'Action.ConfigureAdapter'        = 'Configuring the network adapter.'
    'Action.ApplyNetworkMode'        = 'Setting the network mode.'
    'ActionInline.OpenPort'          = 'opening the modem''s AT port.'
    'ActionInline.Initialize'        = 'waiting for the modem to answer.'
    'ActionInline.EnterPin'          = 'entering the stored PIN.'
    'ActionInline.RadioOn'           = 'turning the radio on.'
    'ActionInline.AutoRegister'      = 'selecting the network automatically.'
    'ActionInline.DefineContext'     = 'setting up the data connection.'
    'ActionInline.ActivateContext'   = 'setting up the data connection.'
    'ActionInline.DeactivateContext' = 'setting up the data connection.'
    'ActionInline.ConfigureAdapter'  = 'configuring the network adapter.'
    'ActionInline.ApplyNetworkMode'  = 'setting the network mode.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = '4G only'
    'Mode.NrOnly'                  = '5G only (SA)'
    'Mode.NotManaged'              = 'As the modem has it'
    'Mode.Other'                   = 'mode {0}'
    'ModeProblem.NotKept'          = 'The modem doesn''t keep the network mode as written; the app doesn''t write it again.'
    'ModeProblem.NoSupportedBand'  = 'The modem supports none of the bands chosen for one of its RATs.'
    'ModeProblem.ModeUnsupported'  = 'The modem doesn''t support this network mode.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Checking the connection now.'
    'Result.SaveSettings.Done'              = 'Settings saved.'
    'Result.SaveSimPin.Done'                = 'PIN stored: the app enters it once when the SIM asks for it.'
    'Result.SaveSimPin.SimNotIdentified'    = 'The SIM can''t be identified: the PIN was not stored.'
    'Result.ForgetSimPin.Done'              = 'The stored PIN is deleted.'
    'Result.DisableSimPin.Disabled'         = 'The SIM no longer asks for its PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'The SIM''s PIN request was already off.'
    'Result.DisableSimPin.PinRejected'      = 'Wrong PIN: the SIM still asks for it.'
    'Result.DisableSimPin.LastAttempt'      = 'Only one PIN attempt is left: nothing was sent.'
    'Result.DisableSimPin.SimNotReady'      = 'The SIM is not ready: nothing was sent.'
    'Result.DisableSimPin.Failed'           = 'The SIM''s PIN request could not be changed.'
    'Result.UnlockFcc.Restarted'            = 'Unlock sent: the modem is restarting.'
    'Result.UnlockFcc.NotLocked'            = 'The modem is not locked: nothing was written.'
    'Result.UnlockFcc.Unknown'              = 'The lock can''t be read: nothing was written.'
    'Result.UnlockFcc.Failed'               = 'The unlock stopped before the restart.'
    'Result.UnlockFcc.PortLost'             = 'The modem left USB during the unlock.'
    'Result.EnableAdapter.Done'             = 'Network adapter enabled.'
    'Result.SetNetworkMode.Applied'         = 'Network mode sent: the modem is registering again. It is kept once the modem finds a network with it.'
    'Result.SetNetworkMode.Unchanged'       = 'The modem already has this network mode: it is kept.'
    'Result.SetNetworkMode.Done'            = 'The app no longer manages the network mode: the modem keeps the one it has.'
    'Result.SetNetworkMode.ModeUnsupported' = 'The modem doesn''t support this network mode: nothing was written.'
    'Result.SetNetworkMode.NoSupportedBand' = 'The modem supports none of the bands chosen for one of its RATs: nothing was written.'
    'Result.SetNetworkMode.Unknown'         = 'The modem''s network mode can''t be read: nothing was written.'
    'Result.CheckDriverPackage.Verified'    = 'Driver package checked: a version the app knows.'
    'Result.CheckDriverPackage.Signed'      = 'Driver package checked: signed by Microsoft, a version the app doesn''t know.'
    'Result.CheckDriverPackage.Refused'     = 'The driver package can''t be installed: the Driver tab says why.'
    'Result.CheckDriverPackage.NoPackage'   = 'No driver package was chosen.'
    'Result.CheckDriverPackage.Failed'      = 'The driver package can''t be read.'
    'Result.InstallDriver.Done'             = 'Driver installed: the app opens the modem''s AT port as soon as Windows starts it.'
    'Result.InstallDriver.RestartNeeded'    = 'Driver installed: Windows needs a restart to finish.'
    'Result.InstallDriver.NoDevice'         = 'Driver added to Windows, but no device took it: it is used when the modem is plugged in, unless Windows ranks another driver higher.'
    'Result.InstallDriver.Unconfirmed'      = 'Not installed: a version the app doesn''t know needs your confirmation.'
    'Result.InstallDriver.NoPackage'        = 'Choose a driver package first.'
    'Result.InstallDriver.DriverWorking'    = 'The AT port already has a working driver: nothing was installed.'
    'Result.InstallDriver.TimedOut'         = 'Windows didn''t finish installing the driver in time: it was stopped.'
    'Result.InstallDriver.Failed'           = 'Windows didn''t install the driver.'
    'Result.UninstallDriver.Done'           = 'Driver uninstalled: the app can''t talk to the modem until it is installed again.'
    'Result.UninstallDriver.RestartNeeded'  = 'Driver uninstalled: Windows needs a restart to finish.'
    'Result.UninstallDriver.NoDriver'       = 'The AT port has no driver the app can uninstall.'
    'Result.UninstallDriver.TrialOn'        = 'Not uninstalled: a network mode is on trial, and only the AT port can write it back.'
    'Result.UninstallDriver.TimedOut'       = 'Windows didn''t finish uninstalling the driver in time: it was stopped.'
    'Result.UninstallDriver.Failed'         = 'Windows didn''t uninstall the driver.'
    'Result.NotElevated'                    = 'That needs administrator rights.'
    'Result.Refused'                        = 'Not available while the app only observes.'
    'Result.NoModem'                        = 'The modem is not connected.'
    'Result.PortLost'                       = 'The modem left USB during the command.'
    'Result.Failed'                         = 'It didn''t work.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Attempts left: {0}.'
    'Result.Restarting'                     = 'The monitor is restarting: try again in a moment.'

    # The headline.
    'Tone.Online'         = 'Online'
    'Tone.Working'        = 'Connecting'
    'Tone.Recovering'     = 'Recovering'
    'Tone.Attention'      = 'Action needed'
    'Tone.Offline'        = 'No modem'
    'Tone.Stopped'        = 'Not monitoring'
    'Title.ConnectionLost' = 'Connection lost'
    'Title.NoNetwork'     = 'No network'
    'Title.NotConnected'  = 'Not connected'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'The modem is not on USB.'
    'Check.H2'          = 'The modem doesn''t answer.'
    'Check.H3'          = 'The SIM is not ready.'
    'Check.H4'          = 'Not registered on a network.'
    'Check.H5'          = 'The data connection is down.'
    'Check.H6'          = 'The network adapter is not configured.'
    'Check.H7'          = 'No traffic gets through.'
    'Check.Other'       = 'The connection is down.'
    'Step.R1'           = 'Configuring the network adapter again.'
    'Step.R2'           = 'Restarting the data connection.'
    'Step.R3'           = 'Registering on the network again.'
    'Step.R4'           = 'Turning the radio off and on.'
    'Step.R5'           = 'Restarting the modem.'
    'Step.R6'           = 'Restarting the modem''s USB device.'
    'StepInline.R1'     = 'configuring the network adapter again.'
    'StepInline.R2'     = 'restarting the data connection.'
    'StepInline.R3'     = 'registering on the network again.'
    'StepInline.R4'     = 'turning the radio off and on.'
    'StepInline.R5'     = 'restarting the modem.'
    'StepInline.R6'     = 'restarting the modem''s USB device.'
    'Recovery.Waiting'  = '{0} The recovery steps didn''t help: they start again at {1}.'
    'Recovery.Slow'     = '{0} Recovery failed {1} times: the app tries again at {2}.'
    'Recovery.Withheld' = '{0} The app only observes, so it doesn''t take the recovery step: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Open'
    'Tray.CheckNow'       = 'Check now'
    'Tray.NetworkMode'    = 'Network mode'
    'Tray.NetworkModeNow' = 'Network mode: {0}'
    'Tray.Exit'           = 'Exit'
    'Tray.Update'         = 'Version {0} is available...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Use {0}, every band'
    'Blocker.SaveApn'       = 'Save APN'
    'Blocker.SavePassword'  = 'Save password'
    'Blocker.StorePin'      = 'Store PIN'
    'Blocker.EnableAdapter' = 'Enable adapter'
    'Blocker.Unlock'        = 'Unlock...'
    'Blocker.InstallDriver' = 'Install the driver...'
    'Blocker.OpenSettings'  = 'Open the settings'
    'Blocker.ObserveOnly'   = 'The app only observes: it changes nothing.'
    'Blocker.NeedsAdmin'    = 'Enabling it needs administrator rights.'
    'Blocker.UnlockNote'    = 'Unlocking writes the modem''s non-volatile memory: the app asks before it does.'
    'Blocker.AttemptsLeft'  = 'Attempts left: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Ready'
    'Sim.PinRequired'    = 'Waiting for its PIN'
    'Sim.PukRequired'    = 'Blocked: needs its PUK'
    'Sim.Absent'         = 'No SIM'
    'Sim.Busy'           = 'Busy'
    'Sim.Failure'        = 'Not working'
    'Sim.Other'          = 'Waiting for another code'
    'Sim.Unknown'        = 'Not known'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - PIN attempts left: {1}'
    'Sim.RequestOn'      = 'PIN request at power-on: on'
    'Sim.RequestOff'     = 'PIN request at power-on: off'
    'Sim.RequestUnknown' = 'PIN request at power-on: not known'
    'Sim.Stored'         = 'A PIN is stored for this SIM.'
    'Sim.NotStored'      = 'No PIN is stored.'
    'Sim.Rejected'       = 'The stored PIN was rejected and deleted: the app never tries it again.'

    # The network tab.
    'Bands.Every'       = 'every band'
    'Bands.EveryBut'    = 'every band but {0}'
    'Bands.None'        = 'none'
    'Network.Current'   = 'The modem now: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'The modem''s network mode is not read yet.'
    'Network.Trial'     = 'Trying {0}: if the modem finds no network with it by {1}, it goes back to what it had.'
    'Network.Reverted'  = 'At {0} the modem had found no network with {1}: it went back to what it had.'
    'Network.Kept'      = 'At {0} the modem registered with {1}: it is kept.'
    'Network.Missing'   = 'The modem leaves out {0}, though asked: it uses the other bands chosen.'
    'Network.ChooseBand' = 'Choose at least one {0} band, or every band.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Encrypted DNS is not available on this Windows: DNS over HTTPS on one adapter needs Windows 11.'
    'Dns.On'                   = 'Encrypted DNS is on: {0}.'
    'Dns.Waiting'              = 'Encrypted DNS waits for its server''s address: no DNS server is set meanwhile.'
    'Dns.Off'                  = 'Encrypted DNS is off.'
    'Dns.Advertised'           = 'The network also gives IPv6 DNS servers ({0}), which Windows may use in the clear.'
    'Dns.LookupFailed'         = '{0} can''t be looked up; the app keeps trying.'
    'Dns.LookingUp'            = 'Looking up {0}...'
    'Dns.LookedUp'             = 'Its server, {0}, was looked up at {1}.'
    'Dns.LookedUpNext'         = 'Its server, {0}, was looked up at {1}; again at {2}.'
    'Dns.LookedUpOperator'     = 'Its server, {0}, was looked up at {1} through the operator''s DNS, in the clear.'
    'Dns.LookedUpOperatorNext' = 'Its server, {0}, was looked up at {1} through the operator''s DNS, in the clear; again at {2}.'
    'Dns.NotAvailableHere'     = 'Encrypted DNS is not available on this Windows.'
    'Dns.NoTemplate'           = 'Windows knows no DNS-over-HTTPS template for {0}: give one.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; the default is used.'
    'Setting.Unknown'          = 'Unknown setting ''{0}'' is ignored.'
    'Setting.Unreadable'       = 'The settings file can''t be read; the defaults are used.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps needs DnsServers, or a DohTemplate that names the server: the operator''s servers speak no DoH, and no DNS server is set until there is one.'
    'Setting.TemplateAddress'  = 'DohTemplate names the address {0}, so it can serve only that server; the default is used.'
    'Rule.Text'                = 'must be printable ASCII without double quotes or surrounding blanks'
    'Rule.TextQuotes'          = 'must be printable ASCII without double quotes'
    'Rule.OneOf'               = 'must be one of {0}'
    'Rule.EmptyOrOneOf'        = 'must be empty or one of {0}'
    'Rule.Addresses'           = 'must be a list of IP addresses'
    'Rule.Number'              = 'must be a whole number from {0} to {1}'
    'Rule.Minutes'             = 'must be a whole number of minutes from {0} to {1}'
    'Rule.Bool'                = 'must be true or false'
    'Rule.Https'               = 'must be empty or an https address without blanks, quotes or credentials'
    'Rule.Bands'               = 'must be a list of distinct band numbers from {0} to {1}'
    'Rule.Gigabytes'           = 'must be a number of gigabytes from {0} to {1}, 0 for none'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'it holds no driver (no INF file)'
    'DriverProblem.NotForModem'  = 'none of its drivers is meant for this modem''s AT port'
    'DriverProblem.NoCatalog'    = 'its driver has no signature catalog'
    'DriverProblem.NotWhql'      = 'its catalog is not signed by Microsoft (WHQL)'
    'DriverProblem.NotInCatalog' = 'its INF file is not the one its catalog vouches for: it was changed, or is damaged'
    'DriverProblem.NotTrusted'   = 'its signature can''t be verified'
    'Driver.Present'             = 'The modem''s AT port has its driver.'
    'Driver.PresentWhat'         = 'The modem''s AT port has its driver: {0}.'
    'Driver.NoDriver'            = 'The modem''s AT port has no driver: the app can''t talk to the modem.'
    'Driver.Problem'             = 'Windows reports a problem with the modem''s AT port: installing its driver again may mend it.'
    'Driver.Absent'              = 'No modem on USB. A driver installed now is used as soon as the modem is plugged in.'
    'Driver.NotLooked'           = 'The modem''s AT port is not looked at yet.'
    'Driver.Source'              = 'The app doesn''t come with the modem''s driver: it has no license to redistribute it. Download a copy, then choose it here: the app checks that Microsoft signed it (WHQL) for this modem, and never runs a program from it.'
    'Driver.SourceCopy'          = 'The app doesn''t come with the modem''s driver: it has no license to redistribute it. A copy of MediaTek''s driver, {0}, is published by a third party, {1}, as {2}. Download it, then choose it here: the app checks that Microsoft signed it (WHQL) for this modem, and never runs a program from it.'
    'Driver.Checking'            = 'Checking the driver package...'
    'Driver.Installing'          = 'Installing the driver: Windows may take a minute.'
    'Driver.Uninstalling'        = 'Uninstalling the driver...'
    'Driver.Verified'            = '{0}: {1}, a version the app knows, signed by Microsoft (WHQL) for this modem.'
    'Driver.Signed'              = '{0}: {1}, signed by Microsoft (WHQL) for this modem, but not a version the app knows: it asks before installing it.'
    'Driver.Refused'             = '{0} can''t be installed: {1}.'
    'Driver.ObserveOnly'         = 'The app only observes: it changes nothing.'
    'Driver.NeedsAdmin'          = 'Installing or uninstalling a driver needs administrator rights: start the app as administrator.'
    'Driver.Trial'               = 'A network mode is on trial: the driver can be uninstalled once the trial ends.'
    'Driver.Install'             = 'Install'
    'Driver.InstallConfirm'      = 'Install...'
    'Driver.ChooseTitle'         = 'Choose the downloaded driver package'
    'Driver.FileKind'            = 'Driver package'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'The monitor stopped and is restarting. The connection is not touched.'
    'Window.NotResponding'   = 'The monitor is not responding. The connection is not touched.'
    'Window.Starting'        = 'Starting.'
    'Window.Simulated'       = 'Development mode: a simulated modem (scenario {0}).'
    'Window.ObserveOnly'     = 'The app only observes: it changes nothing on the modem or the system.'
    'Window.SettingsPending' = 'The data connection is up with other settings: the new ones apply at the next connection.'
    'Window.SettingsFile'    = 'Settings file: {0}'
    'Window.Modems'          = '{0} modems found: the app uses the one on {1}.'
    'Window.Recovered'       = 'Recovered at {0}: {1}'
    'Window.NrAvailable'     = '{0}, 5G available'
    'Window.NothingMeasured' = 'Nothing measured.'
    'Window.PasswordStored'  = 'A password is stored.'
    'Window.NoPassword'      = 'No password is stored.'
    'Window.PinFirst'        = 'Type the SIM''s PIN first: removing it needs the PIN.'
    'Cell.Serving'           = 'Serving'
    'Cell.Neighbour'         = 'Neighbour'
    'Carrier.Primary'        = 'Primary'
    'Carrier.Active'         = 'Active'
    'Carrier.Inactive'       = 'Inactive'
    'Footer.Port'            = 'AT port {0}'
    'Footer.PortClosed'      = 'AT port closed'
    'Footer.Updated'         = 'updated {0}'
    'Footer.PathChecked'     = 'data path checked at {0}'
    'Footer.PathFailed'      = 'data path failed at {0}'
    'Footer.PathPending'     = 'data path not checked yet at {0}'
    'Footer.NotElevated'     = 'no administrator rights'
    'Footer.Version'         = 'version {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Unlock the modem'
    'Confirm.Unlock'               = @'
Unlock the modem?

This writes the modem's non-volatile memory and lifts a restriction that the laptop's maker set for its radio certification. It is done at your own responsibility, and it may not work on every module.

The modem restarts afterwards.
'@
    'Confirm.DisablePinTitle'      = 'Remove the PIN from the SIM'
    'Confirm.DisablePin'           = @'
Remove the PIN from the SIM?

This changes the SIM card, not the app: the SIM will no longer ask for its PIN, in this modem or in any phone. A wrong PIN uses up one of its attempts.
'@
    'Confirm.UnknownDriverTitle'   = 'Install an unknown driver version'
    'Confirm.UnknownDriver'        = @'
Install a driver version the app doesn't know?

Microsoft signed this package (WHQL) for the modem's AT port, so Windows accepts it; but it is not a version the app knows.

Windows installs it for every device it fits.
'@
    'Confirm.UninstallDriverTitle' = 'Uninstall the driver'
    'Confirm.UninstallDriver'      = @'
Uninstall the modem's AT-port driver?

Windows removes it from the modem's serial ports and from its driver store. The data connection stays up, but the app can't talk to the modem, nor watch the connection, until the driver is installed again.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Check now'
    'Xaml.SignalTab'         = 'Signal'
    'Xaml.Cells'             = 'Cells'
    'Xaml.Cell'              = 'Cell'
    'Xaml.Band'              = 'Band'
    'Xaml.Channel'           = 'Channel'
    'Xaml.Bandwidth'         = 'Bandwidth'
    'Xaml.CarrierAggregation' = 'Carrier aggregation'
    'Xaml.Carrier'           = 'Carrier'
    'Xaml.State'             = 'State'
    'Xaml.BandwidthDlUl'     = 'Bandwidth DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulation DL/UL'
    'Xaml.StorePin'          = 'Store PIN'
    'Xaml.ForgetPin'         = 'Forget the stored PIN'
    'Xaml.DisablePin'        = 'Remove the PIN from the SIM...'
    'Xaml.PinNote'           = 'A stored PIN is kept encrypted for your Windows user, with the SIM it belongs to. The app enters it once when that SIM asks for it - never twice, never with one attempt left, and never a PUK.'
    'Xaml.NetworkTab'        = 'Network'
    'Xaml.NetworkMode'       = 'Network mode'
    'Xaml.Apply'             = 'Apply'
    'Xaml.Undo'              = 'Undo changes'
    'Xaml.ModeNote'          = 'The modem keeps its network mode and bands, after the app exits too. A mode is tried first: if the modem finds no network with it, it goes back to what it had.'
    'Xaml.LteAll'            = 'LTE: every band'
    'Xaml.NrAll'             = 'NR: every band'
    'Xaml.ConnectionTab'     = 'Connection'
    'Xaml.ApnTip'            = 'Empty: the one of your subscription.'
    'Xaml.PdpType'           = 'PDP type'
    'Xaml.Authentication'    = 'Authentication'
    'Xaml.AuthNone'          = 'None'
    'Xaml.User'              = 'User'
    'Xaml.Password'          = 'Password'
    'Xaml.ClearPassword'     = 'Delete the stored password'
    'Xaml.DnsServers'        = 'DNS servers'
    'Xaml.DnsTip'            = 'Separated by commas. Empty: the operator''s.'
    'Xaml.EncryptedDns'      = 'Encrypted DNS'
    'Xaml.Doh'               = 'DNS over HTTPS to the servers above, or to the template''s - never in the clear'
    'Xaml.DohTemplate'       = 'DoH template'
    'Xaml.DohTemplateTip'    = 'Empty: the template Windows knows for each server. Otherwise one https address for all of them; without DNS servers, its name or address is the server.'
    'Xaml.RefreshBefore'     = 'Look its server up every'
    'Xaml.RefreshAfter'      = 'minutes, when no DNS server is given: the template''s name is the server.'
    'Xaml.Metric'            = 'Interface metric'
    'Xaml.MetricNote'        = '500 keeps the modem a backup connection; a low value makes it the preferred one.'
    'Xaml.Updates'           = 'Updates'
    'Xaml.UpdateCheck'       = 'Look for a newer release once per start'
    'Xaml.Save'              = 'Save'
    'Xaml.DriverTab'         = 'Driver'
    'Xaml.OpenPage'          = 'Open the download page'
    'Xaml.ChoosePackage'     = 'Choose the downloaded package...'
    'Xaml.Install'           = 'Install'
    'Xaml.UninstallDriver'   = 'Uninstall the driver...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Startup'
    'Xaml.StartAtLogon'               = 'Start the app in the tray when you sign in to Windows'
    'Startup.NotInstalled'            = 'Only the installed app can start when you sign in to Windows.'
    'Startup.NeedsAdmin'              = 'Changing it needs administrator rights.'
    'Startup.ObserveOnly'             = 'The app only observes: it changes nothing.'
    'Result.SetStartAtLogon.Enabled'  = 'The app now starts when you sign in to Windows.'
    'Result.SetStartAtLogon.Disabled' = 'The app no longer starts when you sign in to Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Only the installed app can start when you sign in to Windows: nothing was changed.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Messages'
    'Xaml.From'                     = 'From'
    'Xaml.Time'                     = 'Time'
    'Xaml.Message'                  = 'Message'
    'Xaml.DeleteMessage'            = 'Delete...'
    'Xaml.NewMessage'               = 'New message'
    'Xaml.To'                       = 'To'
    'Xaml.Send'                     = 'Send'
    'Xaml.SendNote'                 = 'Each part is a message, which the operator may charge for. A part that fails is never sent again by itself.'
    'Messages.TabNew'               = 'Messages ({0})'
    'Messages.Storage'              = '{0} of {1} places used on the SIM.'
    'Messages.Full'                 = 'The SIM is full: new messages can''t be stored until some are deleted.'
    'Messages.Empty'                = 'No messages on the SIM.'
    'Messages.ObserveOnly'          = 'Messages are not read while the app only observes: reading them marks them read on the modem.'
    'Messages.NoModem'              = 'The modem is not connected.'
    'Messages.NotReady'             = 'Messages are read once the SIM is ready.'
    'Messages.Header'               = 'From {0}, {1}'
    'Messages.Missing'              = 'Parts not received (yet): {0}.'
    'Messages.Binary'               = 'This message carries data, not text.'
    'Messages.Compressed'           = 'This message is compressed: the app can''t show it.'
    'Messages.Malformed'            = 'This message can''t be read.'
    'Messages.NationalLanguage'     = 'It uses a national language table the app doesn''t have: some characters may be wrong.'
    'Messages.Silent'               = 'A silent message: the network asked that it never be shown.'
    'Messages.SilentNote'           = 'It takes a place on the SIM until it is deleted.'
    'Messages.Sending'              = 'Sending the message...'
    'Messages.Count'                = 'Characters: {0} - parts: {1}'
    'Messages.CountUnicode'         = 'Characters: {0} - parts: {1} (with special characters, {2} per part)'
    'Messages.TooLong'              = 'Too long: a message has at most 255 parts.'
    'Result.SendMessage.Sent'       = 'Message sent.'
    'Result.SendMessage.Failed'     = 'The message was not sent completely: {0} of {1} parts went out.'
    'Result.SendMessage.Invalid'    = 'Enter a phone number and a text.'
    'Result.DeleteMessage.Done'     = 'Message deleted from the SIM.'
    'Result.DeleteMessage.NotFound' = 'The message is no longer on the SIM.'
    'Result.DeleteMessage.Failed'   = 'The message could not be deleted.'
    'Result.NotReady'               = 'The SIM is not ready.'
    'Confirm.DeleteMessageTitle'    = 'Delete the message'
    'Confirm.DeleteMessage'         = @'
Delete this message from the SIM?

It can't be undone.
'@
    'Tray.NewMessage'               = 'New message'
    'Tray.NewMessages'              = '{0} new messages'
    'Tray.MessageFrom'              = 'From {0}'
    'Xaml.DataTab'                  = 'Data'
    'Xaml.CycleDay'                 = 'The billing cycle starts on day'
    'Xaml.Quota'                    = 'Data quota (GB)'
    'Xaml.QuotaNote'                = '0: none. At 80% and at 100% of it the tray says so, once per cycle; the connection stays on.'
    'Xaml.UsageNote'                = 'Counted from the modem''s network adapter: an estimate, which may differ from the operator''s count.'
    'Usage.Today'                   = 'Today: {0} (received {1}, sent {2})'
    'Usage.Cycle'                   = 'This cycle, from {0} to {1}: {2} (received {3}, sent {4})'
    'Usage.Quota'                   = 'Quota: {0} of {1} used ({2}%)'
    'Usage.NoQuota'                 = 'No quota set.'
    'Usage.NotCounted'              = 'Nothing counted yet: the modem''s network adapter has not been read.'
    'Tray.Usage'                    = 'Data today {0}, this cycle {1}'
    'Tray.UsageQuota'               = 'Data today {0}, this cycle {1} of {2}'
    'Tray.QuotaTitle'               = 'Data quota'
    'Tray.Quota'                    = '{0}% of the quota used in this cycle. The connection stays on.'
}
