# The app's texts in Spanish (Spain). Missing keys fall back to English (en.psd1).
# Placeholders {0}, {1}... are the same as in English; their order in a sentence may change.
# Saved as UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'No se ha encontrado ningún módem en USB.'
    'Reason.NoDriver'              = 'El puerto AT del módem no tiene controlador: la aplicación no puede comunicarse con el módem hasta que se instale.'
    'Reason.DeviceProblem'         = 'Windows informa de un problema con el puerto AT del módem.'
    'Reason.PortInUse'             = 'Otro programa está usando el puerto AT del módem.'
    'Reason.PortFailed'            = 'No se puede abrir el puerto AT del módem.'
    'Reason.SimUnknown'            = 'Leyendo la SIM.'
    'Reason.NoPin'                 = 'La SIM está esperando su PIN.'
    'Reason.PinForOtherSim'        = 'El PIN guardado pertenece a otra SIM: introduce el PIN de esta SIM.'
    'Reason.SimNotIdentified'      = 'No se puede identificar la SIM, así que no se le envía el PIN guardado.'
    'Reason.PinUnconfirmed'        = 'La última vez que se introdujo el PIN no hubo respuesta, y la aplicación nunca lo intenta dos veces: vuelve a introducir el PIN.'
    'Reason.LastAttempt'           = 'Solo queda un intento de PIN, y la aplicación no lo usará: desbloquea la SIM en un teléfono.'
    'Reason.PukRequired'           = 'La SIM está bloqueada y necesita su PUK: desbloquéala en un teléfono. La aplicación nunca introduce un PUK.'
    'Reason.NoSim'                 = 'No hay ninguna SIM en el módem.'
    'Reason.SimFailure'            = 'La SIM no funciona.'
    'Reason.SimOther'              = 'La SIM está esperando un código que la aplicación no gestiona.'
    'Reason.SimBusy'               = 'La SIM está ocupada; esperando a que esté lista.'
    'Reason.FccLocked'             = 'El módem está bloqueado por el fabricante de su portátil (bloqueo FCC): su radio permanece apagada.'
    'Reason.NotRegistered'         = 'No registrado en ninguna red.'
    'Reason.NotSearching'          = 'No registrado y sin buscar ninguna red.'
    'Reason.Searching'             = 'Buscando una red.'
    'Reason.Denied'                = 'La red ha rechazado el registro.'
    'Reason.Unknown'               = 'No registrado; se desconoce el motivo.'
    'Reason.EmergencyOnly'         = 'Solo llamadas de emergencia.'
    'Reason.ContextUnknown'        = 'Leyendo la conexión de datos.'
    'Reason.ApnPasswordUnreadable' = 'No se puede leer la contraseña del APN guardada: vuelve a introducirla.'
    'Reason.ApnNeeded'             = 'La red no ha dado acceso a Internet con un APN vacío: introduce el APN de tu operador.'
    'Reason.NoAddress'             = 'La conexión de datos no tiene dirección IPv4.'
    'Reason.AdapterDisabled'       = 'El adaptador de red del módem está deshabilitado.'
    'Reason.NoAdapter'             = 'Falta el adaptador de red del módem.'
    'Reason.NotElevated'           = 'El adaptador de red solo se puede configurar con permisos de administrador: ejecuta la aplicación como administrador.'
    'Reason.DataPathFailed'        = 'La conexión está activa, pero no pasa tráfico.'
    'Reason.DohServerUnresolved'   = 'Aún no se ha resuelto el nombre del servidor de DNS over HTTPS: la aplicación sigue intentándolo y, hasta entonces, deja el adaptador de red como lo configuró el módem.'
    'Reason.DohNeedsServers'       = 'El DNS cifrado necesita servidores DNS elegidos por ti: los del operador no admiten DNS over HTTPS. Hasta entonces, el adaptador de red no se configura.'
    'Reason.DohUnavailable'        = 'Esta versión de Windows no puede cifrar el DNS en un adaptador concreto - DNS over HTTPS necesita Windows 11: desactiva el DNS cifrado. Hasta entonces, el adaptador de red no se configura.'
    'Reason.DohTemplateMissing'    = 'Windows no conoce ninguna plantilla de DNS over HTTPS para un servidor DNS de la configuración: indica una, o elige servidores que conozca. Hasta entonces, el adaptador de red no se configura.'
    'Reason.Connected'             = 'Conectado.'
    'Reason.Other'                 = 'No registrado ({0}).'
    'Reason.Working'               = 'Trabajando en la conexión.'
    'Reason.NoNetworkForMode'      = 'No se ha encontrado ninguna red con {0}. Ningún reinicio la encontrará: elige un modo de red más amplio.'
    'Reason.NoNetworkForModeBands' = 'No se ha encontrado ninguna red con {0} en las bandas LTE elegidas. Ningún reinicio la encontrará: elige un modo de red más amplio.'
    'Reason.Withheld'              = 'La aplicación solo observa, así que no da el siguiente paso: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Abriendo el puerto AT del módem.'
    'Action.Initialize'              = 'Esperando a que el módem responda.'
    'Action.EnterPin'                = 'Introduciendo el PIN guardado.'
    'Action.RadioOn'                 = 'Encendiendo la radio.'
    'Action.AutoRegister'            = 'Seleccionando la red automáticamente.'
    'Action.DefineContext'           = 'Configurando la conexión de datos.'
    'Action.ActivateContext'         = 'Configurando la conexión de datos.'
    'Action.DeactivateContext'       = 'Configurando la conexión de datos.'
    'Action.ConfigureAdapter'        = 'Configurando el adaptador de red.'
    'Action.ApplyNetworkMode'        = 'Estableciendo el modo de red.'
    'ActionInline.OpenPort'          = 'abriendo el puerto AT del módem.'
    'ActionInline.Initialize'        = 'esperando a que el módem responda.'
    'ActionInline.EnterPin'          = 'introduciendo el PIN guardado.'
    'ActionInline.RadioOn'           = 'encendiendo la radio.'
    'ActionInline.AutoRegister'      = 'seleccionando la red automáticamente.'
    'ActionInline.DefineContext'     = 'configurando la conexión de datos.'
    'ActionInline.ActivateContext'   = 'configurando la conexión de datos.'
    'ActionInline.DeactivateContext' = 'configurando la conexión de datos.'
    'ActionInline.ConfigureAdapter'  = 'configurando el adaptador de red.'
    'ActionInline.ApplyNetworkMode'  = 'estableciendo el modo de red.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Solo 4G'
    'Mode.NrOnly'                  = 'Solo 5G (SA)'
    'Mode.NotManaged'              = 'Como lo tenga el módem'
    'Mode.Other'                   = 'modo {0}'
    'ModeProblem.NotKept'          = 'El módem no mantiene el modo de red tal como se escribió; la aplicación no lo vuelve a escribir.'
    'ModeProblem.NoSupportedBand'  = 'El módem no admite ninguna de las bandas elegidas para una de sus RAT.'
    'ModeProblem.ModeUnsupported'  = 'El módem no admite este modo de red.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Comprobando la conexión ahora.'
    'Result.SaveSettings.Done'              = 'Configuración guardada.'
    'Result.SaveSimPin.Done'                = 'PIN guardado: la aplicación lo introduce una vez cuando la SIM lo pide.'
    'Result.SaveSimPin.SimNotIdentified'    = 'No se puede identificar la SIM: el PIN no se ha guardado.'
    'Result.ForgetSimPin.Done'              = 'Se ha eliminado el PIN guardado.'
    'Result.DisableSimPin.Disabled'         = 'La SIM ya no pide su PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'La solicitud del PIN de la SIM ya estaba desactivada.'
    'Result.DisableSimPin.PinRejected'      = 'PIN incorrecto: la SIM sigue pidiéndolo.'
    'Result.DisableSimPin.LastAttempt'      = 'Solo queda un intento de PIN: no se ha enviado nada.'
    'Result.DisableSimPin.SimNotReady'      = 'La SIM no está lista: no se ha enviado nada.'
    'Result.DisableSimPin.Failed'           = 'No se ha podido cambiar la solicitud del PIN de la SIM.'
    'Result.UnlockFcc.Restarted'            = 'Desbloqueo enviado: el módem se está reiniciando.'
    'Result.UnlockFcc.NotLocked'            = 'El módem no está bloqueado: no se ha escrito nada.'
    'Result.UnlockFcc.Unknown'              = 'No se puede leer el bloqueo: no se ha escrito nada.'
    'Result.UnlockFcc.Failed'               = 'El desbloqueo se detuvo antes del reinicio.'
    'Result.UnlockFcc.PortLost'             = 'El módem se desconectó del USB durante el desbloqueo.'
    'Result.EnableAdapter.Done'             = 'Adaptador de red habilitado.'
    'Result.SetNetworkMode.Applied'         = 'Modo de red enviado: el módem se está registrando de nuevo. Se mantendrá en cuanto el módem encuentre una red con él.'
    'Result.SetNetworkMode.Unchanged'       = 'El módem ya tiene este modo de red: se mantiene.'
    'Result.SetNetworkMode.Done'            = 'La aplicación ya no gestiona el modo de red: el módem mantiene el que tiene.'
    'Result.SetNetworkMode.ModeUnsupported' = 'El módem no admite este modo de red: no se ha escrito nada.'
    'Result.SetNetworkMode.NoSupportedBand' = 'El módem no admite ninguna de las bandas elegidas para una de sus RAT: no se ha escrito nada.'
    'Result.SetNetworkMode.Unknown'         = 'No se puede leer el modo de red del módem: no se ha escrito nada.'
    'Result.CheckDriverPackage.Verified'    = 'Paquete del controlador comprobado: una versión que la aplicación conoce.'
    'Result.CheckDriverPackage.Signed'      = 'Paquete del controlador comprobado: firmado por Microsoft, una versión que la aplicación no conoce.'
    'Result.CheckDriverPackage.Refused'     = 'El paquete del controlador no se puede instalar: la pestaña Controlador indica el motivo.'
    'Result.CheckDriverPackage.NoPackage'   = 'No se ha elegido ningún paquete del controlador.'
    'Result.CheckDriverPackage.Failed'      = 'No se puede leer el paquete del controlador.'
    'Result.InstallDriver.Done'             = 'Controlador instalado: la aplicación abre el puerto AT del módem en cuanto Windows lo inicia.'
    'Result.InstallDriver.RestartNeeded'    = 'Controlador instalado: Windows necesita reiniciarse para terminar.'
    'Result.InstallDriver.NoDevice'         = 'Controlador añadido a Windows, pero ningún dispositivo lo ha adoptado: se usará cuando se conecte el módem, a menos que Windows dé más prioridad a otro controlador.'
    'Result.InstallDriver.Unconfirmed'      = 'No instalado: una versión que la aplicación no conoce necesita tu confirmación.'
    'Result.InstallDriver.NoPackage'        = 'Primero elige un paquete del controlador.'
    'Result.InstallDriver.DriverWorking'    = 'El puerto AT ya tiene un controlador que funciona: no se ha instalado nada.'
    'Result.InstallDriver.TimedOut'         = 'Windows no terminó de instalar el controlador a tiempo: se ha detenido.'
    'Result.InstallDriver.Failed'           = 'Windows no ha instalado el controlador.'
    'Result.UninstallDriver.Done'           = 'Controlador desinstalado: la aplicación no puede comunicarse con el módem hasta que se vuelva a instalar.'
    'Result.UninstallDriver.RestartNeeded'  = 'Controlador desinstalado: Windows necesita reiniciarse para terminar.'
    'Result.UninstallDriver.NoDriver'       = 'El puerto AT no tiene ningún controlador que la aplicación pueda desinstalar.'
    'Result.UninstallDriver.TrialOn'        = 'No desinstalado: hay un modo de red en prueba, y solo el puerto AT puede volver a escribir el anterior.'
    'Result.UninstallDriver.TimedOut'       = 'Windows no terminó de desinstalar el controlador a tiempo: se ha detenido.'
    'Result.UninstallDriver.Failed'         = 'Windows no ha desinstalado el controlador.'
    'Result.NotElevated'                    = 'Eso necesita permisos de administrador.'
    'Result.Refused'                        = 'No disponible mientras la aplicación solo observa.'
    'Result.NoModem'                        = 'El módem no está conectado.'
    'Result.PortLost'                       = 'El módem se desconectó del USB durante el comando.'
    'Result.Failed'                         = 'No ha funcionado.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Intentos restantes: {0}.'
    'Result.Restarting'                     = 'La supervisión se está reiniciando: vuelve a intentarlo en un momento.'

    # The headline.
    'Tone.Online'         = 'En línea'
    'Tone.Working'        = 'Conectando'
    'Tone.Recovering'     = 'Recuperando'
    'Tone.Attention'      = 'Acción necesaria'
    'Tone.Offline'        = 'Sin módem'
    'Tone.Stopped'        = 'Sin supervisión'
    'Title.ConnectionLost' = 'Conexión perdida'
    'Title.NoNetwork'     = 'Sin red'
    'Title.NotConnected'  = 'No conectado'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'El módem no está en USB.'
    'Check.H2'          = 'El módem no responde.'
    'Check.H3'          = 'La SIM no está lista.'
    'Check.H4'          = 'No registrado en ninguna red.'
    'Check.H5'          = 'La conexión de datos está caída.'
    'Check.H6'          = 'El adaptador de red no está configurado.'
    'Check.H7'          = 'No pasa tráfico.'
    'Check.Other'       = 'La conexión está caída.'
    'Step.R1'           = 'Configurando de nuevo el adaptador de red.'
    'Step.R2'           = 'Reiniciando la conexión de datos.'
    'Step.R3'           = 'Registrándose de nuevo en la red.'
    'Step.R4'           = 'Apagando y encendiendo la radio.'
    'Step.R5'           = 'Reiniciando el módem.'
    'Step.R6'           = 'Reiniciando el dispositivo USB del módem.'
    'StepInline.R1'     = 'configurando de nuevo el adaptador de red.'
    'StepInline.R2'     = 'reiniciando la conexión de datos.'
    'StepInline.R3'     = 'registrándose de nuevo en la red.'
    'StepInline.R4'     = 'apagando y encendiendo la radio.'
    'StepInline.R5'     = 'reiniciando el módem.'
    'StepInline.R6'     = 'reiniciando el dispositivo USB del módem.'
    'Recovery.Waiting'  = '{0} Los pasos de recuperación no han servido: vuelven a empezar a las {1}.'
    'Recovery.Slow'     = '{0} La recuperación ha fallado {1} veces: la aplicación lo vuelve a intentar a las {2}.'
    'Recovery.Withheld' = '{0} La aplicación solo observa, así que no da el paso de recuperación: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Abrir'
    'Tray.CheckNow'       = 'Comprobar ahora'
    'Tray.NetworkMode'    = 'Modo de red'
    'Tray.NetworkModeNow' = 'Modo de red: {0}'
    'Tray.Exit'           = 'Salir'
    'Tray.Update'         = 'Versión {0} disponible...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Usar {0}, todas las bandas'
    'Blocker.SaveApn'       = 'Guardar APN'
    'Blocker.SavePassword'  = 'Guardar contraseña'
    'Blocker.StorePin'      = 'Guardar PIN'
    'Blocker.EnableAdapter' = 'Habilitar adaptador'
    'Blocker.Unlock'        = 'Desbloquear...'
    'Blocker.InstallDriver' = 'Instalar el controlador...'
    'Blocker.OpenSettings'  = 'Abrir la configuración'
    'Blocker.ObserveOnly'   = 'La aplicación solo observa: no cambia nada.'
    'Blocker.NeedsAdmin'    = 'Para habilitarlo se necesitan permisos de administrador.'
    'Blocker.UnlockNote'    = 'El desbloqueo escribe en la memoria no volátil del módem: la aplicación pregunta antes de hacerlo.'
    'Blocker.AttemptsLeft'  = 'Intentos restantes: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Lista'
    'Sim.PinRequired'    = 'Esperando su PIN'
    'Sim.PukRequired'    = 'Bloqueada: necesita su PUK'
    'Sim.Absent'         = 'Sin SIM'
    'Sim.Busy'           = 'Ocupada'
    'Sim.Failure'        = 'No funciona'
    'Sim.Other'          = 'Esperando otro código'
    'Sim.Unknown'        = 'Estado desconocido'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - intentos de PIN restantes: {1}'
    'Sim.RequestOn'      = 'Solicitud de PIN al encender: activada'
    'Sim.RequestOff'     = 'Solicitud de PIN al encender: desactivada'
    'Sim.RequestUnknown' = 'Solicitud de PIN al encender: se desconoce'
    'Sim.Stored'         = 'Hay un PIN guardado para esta SIM.'
    'Sim.NotStored'      = 'No hay ningún PIN guardado.'
    'Sim.Rejected'       = 'El PIN guardado se rechazó y se ha eliminado: la aplicación nunca lo vuelve a intentar.'

    # The network tab.
    'Bands.Every'       = 'todas las bandas'
    'Bands.EveryBut'    = 'todas las bandas excepto {0}'
    'Bands.None'        = 'ninguna'
    'Network.Current'   = 'El módem ahora: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'Aún no se ha leído el modo de red del módem.'
    'Network.Trial'     = 'Probando {0}: si el módem no encuentra ninguna red con él antes de las {1}, vuelve a lo que tenía.'
    'Network.Reverted'  = 'A las {0}, el módem no había encontrado ninguna red con {1}: ha vuelto a lo que tenía.'
    'Network.Kept'      = 'A las {0}, el módem se registró con {1}: se mantiene.'
    'Network.Missing'   = 'El módem omite {0}, aunque se le pidió: usa las demás bandas elegidas.'
    'Network.ChooseBand' = 'Elige al menos una banda {0}, o todas las bandas.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'El DNS cifrado no está disponible en esta versión de Windows: DNS over HTTPS en un adaptador concreto necesita Windows 11.'
    'Dns.On'                   = 'El DNS cifrado está activado: {0}.'
    'Dns.Waiting'              = 'El DNS cifrado espera la dirección de su servidor: mientras tanto, no se establece ningún servidor DNS.'
    'Dns.Off'                  = 'El DNS cifrado está desactivado.'
    'Dns.Advertised'           = 'La red también proporciona servidores DNS IPv6 ({0}), que Windows puede usar sin cifrar.'
    'Dns.LookupFailed'         = 'No se puede resolver {0}; la aplicación sigue intentándolo.'
    'Dns.LookingUp'            = 'Resolviendo {0}...'
    'Dns.LookedUp'             = 'Su servidor, {0}, se resolvió a las {1}.'
    'Dns.LookedUpNext'         = 'Su servidor, {0}, se resolvió a las {1}; se resolverá de nuevo a las {2}.'
    'Dns.LookedUpOperator'     = 'Su servidor, {0}, se resolvió a las {1} mediante el DNS del operador, sin cifrar.'
    'Dns.LookedUpOperatorNext' = 'Su servidor, {0}, se resolvió a las {1} mediante el DNS del operador, sin cifrar; se resolverá de nuevo a las {2}.'
    'Dns.NotAvailableHere'     = 'El DNS cifrado no está disponible en esta versión de Windows.'
    'Dns.NoTemplate'           = 'Windows no conoce ninguna plantilla de DNS over HTTPS para {0}: indica una.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; se usa el valor predeterminado.'
    'Setting.Unknown'          = 'Se ignora la opción desconocida ''{0}''.'
    'Setting.Unreadable'       = 'No se puede leer el archivo de configuración; se usan los valores predeterminados.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps necesita DnsServers, o una DohTemplate que indique el servidor: los servidores del operador no admiten DoH, y no se establece ningún servidor DNS hasta que haya uno.'
    'Setting.TemplateAddress'  = 'DohTemplate indica la dirección {0}, así que solo puede servir a ese servidor; se usa el valor predeterminado.'
    'Rule.Text'                = 'debe ser ASCII imprimible, sin comillas dobles ni espacios al principio o al final'
    'Rule.TextQuotes'          = 'debe ser ASCII imprimible, sin comillas dobles'
    'Rule.OneOf'               = 'debe ser uno de estos valores: {0}'
    'Rule.EmptyOrOneOf'        = 'debe estar vacío o ser uno de estos valores: {0}'
    'Rule.Addresses'           = 'debe ser una lista de direcciones IP'
    'Rule.Number'              = 'debe ser un número entero de {0} a {1}'
    'Rule.Minutes'             = 'debe ser un número entero de minutos de {0} a {1}'
    'Rule.Bool'                = 'debe ser true o false'
    'Rule.Https'               = 'debe estar vacío o ser una dirección https sin espacios, comillas ni credenciales'
    'Rule.Bands'               = 'debe ser una lista de números de banda sin repetir, de {0} a {1}'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'no contiene ningún controlador (no hay archivo INF)'
    'DriverProblem.NotForModem'  = 'ninguno de sus controladores está destinado al puerto AT de este módem'
    'DriverProblem.NoCatalog'    = 'su controlador no tiene catálogo de firmas'
    'DriverProblem.NotWhql'      = 'su catálogo no está firmado por Microsoft (WHQL)'
    'DriverProblem.NotInCatalog' = 'su archivo INF no es el que avala su catálogo: se ha modificado o está dañado'
    'DriverProblem.NotTrusted'   = 'no se puede verificar su firma'
    'Driver.Present'             = 'El puerto AT del módem tiene su controlador.'
    'Driver.PresentWhat'         = 'El puerto AT del módem tiene su controlador: {0}.'
    'Driver.NoDriver'            = 'El puerto AT del módem no tiene controlador: la aplicación no puede comunicarse con el módem.'
    'Driver.Problem'             = 'Windows informa de un problema con el puerto AT del módem: volver a instalar su controlador puede solucionarlo.'
    'Driver.Absent'              = 'No hay ningún módem en USB. Un controlador instalado ahora se usará en cuanto se conecte el módem.'
    'Driver.NotLooked'           = 'Aún no se ha examinado el puerto AT del módem.'
    'Driver.Source'              = 'La aplicación no incluye el controlador del módem: no tiene licencia para redistribuirlo. Descarga una copia y luego elígela aquí: la aplicación comprueba que Microsoft la firmó (WHQL) para este módem, y nunca ejecuta ningún programa que contenga.'
    'Driver.SourceCopy'          = 'La aplicación no incluye el controlador del módem: no tiene licencia para redistribuirlo. Un tercero, {1}, publica una copia del controlador de MediaTek, {0}, como {2}. Descárgala y luego elígela aquí: la aplicación comprueba que Microsoft la firmó (WHQL) para este módem, y nunca ejecuta ningún programa que contenga.'
    'Driver.Checking'            = 'Comprobando el paquete del controlador...'
    'Driver.Installing'          = 'Instalando el controlador: Windows puede tardar un minuto.'
    'Driver.Uninstalling'        = 'Desinstalando el controlador...'
    'Driver.Verified'            = '{0}: {1}, una versión que la aplicación conoce, firmada por Microsoft (WHQL) para este módem.'
    'Driver.Signed'              = '{0}: {1}, firmado por Microsoft (WHQL) para este módem, pero no es una versión que la aplicación conozca: pregunta antes de instalarlo.'
    'Driver.Refused'             = 'No se puede instalar {0}: {1}.'
    'Driver.ObserveOnly'         = 'La aplicación solo observa: no cambia nada.'
    'Driver.NeedsAdmin'          = 'Para instalar o desinstalar un controlador se necesitan permisos de administrador: ejecuta la aplicación como administrador.'
    'Driver.Trial'               = 'Hay un modo de red en prueba: el controlador se podrá desinstalar cuando termine la prueba.'
    'Driver.Install'             = 'Instalar'
    'Driver.InstallConfirm'      = 'Instalar...'
    'Driver.ChooseTitle'         = 'Elegir el paquete del controlador descargado'
    'Driver.FileKind'            = 'Paquete del controlador'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'La supervisión se detuvo y se está reiniciando. La conexión no se toca.'
    'Window.NotResponding'   = 'La supervisión no responde. La conexión no se toca.'
    'Window.Starting'        = 'Iniciando.'
    'Window.Simulated'       = 'Modo de desarrollo: un módem simulado (escenario {0}).'
    'Window.ObserveOnly'     = 'La aplicación solo observa: no cambia nada en el módem ni en el sistema.'
    'Window.SettingsPending' = 'La conexión de datos está activa con otra configuración: la nueva se aplica en la próxima conexión.'
    'Window.SettingsFile'    = 'Archivo de configuración: {0}'
    'Window.Modems'          = 'Se han encontrado {0} módems: la aplicación usa el de {1}.'
    'Window.Recovered'       = 'Conexión recuperada a las {0}: {1}'
    'Window.NrAvailable'     = '{0}, 5G disponible'
    'Window.NothingMeasured' = 'Sin mediciones.'
    'Window.PasswordStored'  = 'Hay una contraseña guardada.'
    'Window.NoPassword'      = 'No hay ninguna contraseña guardada.'
    'Window.PinFirst'        = 'Escribe primero el PIN de la SIM: para quitarlo se necesita el PIN.'
    'Cell.Serving'           = 'Servidora'
    'Cell.Neighbour'         = 'Vecina'
    'Carrier.Primary'        = 'Primaria'
    'Carrier.Active'         = 'Activa'
    'Carrier.Inactive'       = 'Inactiva'
    'Footer.Port'            = 'Puerto AT {0}'
    'Footer.PortClosed'      = 'Puerto AT cerrado'
    'Footer.Updated'         = 'actualizado a las {0}'
    'Footer.PathChecked'     = 'ruta de datos comprobada a las {0}'
    'Footer.PathFailed'      = 'ruta de datos fallida a las {0}'
    'Footer.PathPending'     = 'ruta de datos aún sin comprobar a las {0}'
    'Footer.NotElevated'     = 'sin permisos de administrador'
    'Footer.Version'         = 'versión {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Desbloquear el módem'
    'Confirm.Unlock'               = @'
¿Desbloquear el módem?

Esto escribe en la memoria no volátil del módem y elimina una restricción que el fabricante del portátil impuso para la certificación de su radio. Se hace bajo tu propia responsabilidad, y puede que no funcione en todos los módulos.

Después, el módem se reinicia.
'@
    'Confirm.DisablePinTitle'      = 'Quitar el PIN de la SIM'
    'Confirm.DisablePin'           = @'
¿Quitar el PIN de la SIM?

Esto cambia la tarjeta SIM, no la aplicación: la SIM ya no pedirá su PIN, ni en este módem ni en ningún teléfono. Un PIN incorrecto gasta uno de sus intentos.
'@
    'Confirm.UnknownDriverTitle'   = 'Instalar una versión desconocida del controlador'
    'Confirm.UnknownDriver'        = @'
¿Instalar una versión del controlador que la aplicación no conoce?

Microsoft firmó este paquete (WHQL) para el puerto AT del módem, así que Windows lo acepta; pero no es una versión que la aplicación conozca.

Windows lo instala en todos los dispositivos para los que sirva.
'@
    'Confirm.UninstallDriverTitle' = 'Desinstalar el controlador'
    'Confirm.UninstallDriver'      = @'
¿Desinstalar el controlador del puerto AT del módem?

Windows lo quita de los puertos serie del módem y de su almacén de controladores. La conexión de datos sigue activa, pero la aplicación no puede comunicarse con el módem ni vigilar la conexión hasta que se vuelva a instalar el controlador.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Comprobar ahora'
    'Xaml.SignalTab'         = 'Señal'
    'Xaml.Cells'             = 'Celdas'
    'Xaml.Cell'              = 'Celda'
    'Xaml.Band'              = 'Banda'
    'Xaml.Channel'           = 'Canal'
    'Xaml.Bandwidth'         = 'Ancho de banda'
    'Xaml.CarrierAggregation' = 'Agregación de portadoras'
    'Xaml.Carrier'           = 'Portadora'
    'Xaml.State'             = 'Estado'
    'Xaml.BandwidthDlUl'     = 'Ancho de banda DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulación DL/UL'
    'Xaml.StorePin'          = 'Guardar PIN'
    'Xaml.ForgetPin'         = 'Olvidar el PIN guardado'
    'Xaml.DisablePin'        = 'Quitar el PIN de la SIM...'
    'Xaml.PinNote'           = 'Un PIN guardado se conserva cifrado para tu usuario de Windows, junto con la SIM a la que pertenece. La aplicación lo introduce una vez cuando esa SIM lo pide - nunca dos veces, nunca con un solo intento restante y nunca un PUK.'
    'Xaml.NetworkTab'        = 'Red'
    'Xaml.NetworkMode'       = 'Modo de red'
    'Xaml.Apply'             = 'Aplicar'
    'Xaml.Undo'              = 'Deshacer cambios'
    'Xaml.ModeNote'          = 'El módem conserva su modo de red y sus bandas, también después de que la aplicación se cierre. Primero se prueba un modo: si el módem no encuentra ninguna red con él, vuelve a lo que tenía.'
    'Xaml.LteAll'            = 'LTE: todas las bandas'
    'Xaml.NrAll'             = 'NR: todas las bandas'
    'Xaml.ConnectionTab'     = 'Conexión'
    'Xaml.ApnTip'            = 'Vacío: el de tu suscripción.'
    'Xaml.PdpType'           = 'Tipo de PDP'
    'Xaml.Authentication'    = 'Autenticación'
    'Xaml.AuthNone'          = 'Ninguna'
    'Xaml.User'              = 'Usuario'
    'Xaml.Password'          = 'Contraseña'
    'Xaml.ClearPassword'     = 'Eliminar la contraseña guardada'
    'Xaml.DnsServers'        = 'Servidores DNS'
    'Xaml.DnsTip'            = 'Separados por comas. Vacío: los del operador.'
    'Xaml.EncryptedDns'      = 'DNS cifrado'
    'Xaml.Doh'               = 'DNS over HTTPS a los servidores de arriba, o al de la plantilla - nunca sin cifrar'
    'Xaml.DohTemplate'       = 'Plantilla DoH'
    'Xaml.DohTemplateTip'    = 'Vacío: la plantilla que Windows conoce para cada servidor. Si no, una sola dirección https para todos; sin servidores DNS, su nombre o dirección es el servidor.'
    'Xaml.RefreshBefore'     = 'Resolver su servidor cada'
    'Xaml.RefreshAfter'      = 'minutos, cuando no se indica ningún servidor DNS: el nombre de la plantilla es el servidor.'
    'Xaml.Metric'            = 'Métrica de interfaz'
    'Xaml.MetricNote'        = '500 mantiene el módem como conexión de respaldo; un valor bajo la convierte en la preferida.'
    'Xaml.Updates'           = 'Actualizaciones'
    'Xaml.UpdateCheck'       = 'Buscar una versión más reciente una vez en cada inicio'
    'Xaml.Save'              = 'Guardar'
    'Xaml.DriverTab'         = 'Controlador'
    'Xaml.OpenPage'          = 'Abrir la página de descarga'
    'Xaml.ChoosePackage'     = 'Elegir el paquete descargado...'
    'Xaml.Install'           = 'Instalar'
    'Xaml.UninstallDriver'   = 'Desinstalar el controlador...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Inicio'
    'Xaml.StartAtLogon'               = 'Iniciar la aplicación en el área de notificación al iniciar sesión en Windows'
    'Startup.NotInstalled'            = 'Solo la aplicación instalada puede iniciarse al iniciar sesión en Windows.'
    'Startup.NeedsAdmin'              = 'Para cambiarlo se necesitan permisos de administrador.'
    'Startup.ObserveOnly'             = 'La aplicación solo observa: no cambia nada.'
    'Result.SetStartAtLogon.Enabled'  = 'La aplicación ahora se inicia al iniciar sesión en Windows.'
    'Result.SetStartAtLogon.Disabled' = 'La aplicación ya no se inicia al iniciar sesión en Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Solo la aplicación instalada puede iniciarse al iniciar sesión en Windows: no se ha cambiado nada.'
}
