# The app's texts in French. Same keys as en.psd1, which is the fallback of any key missing here.
# Placeholders {0}, {1}... keep the meaning they have in English. Saved as UTF-8 with a byte order
# mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Aucun modem trouvé en USB.'
    'Reason.DeviceProblem'         = 'Windows signale un problème avec le port AT du modem.'
    'Reason.PortInUse'             = 'Un autre programme utilise le port AT du modem.'
    'Reason.BindFailed'            = 'Le port AT du modem n''a pas pu passer au pilote WinUSB de Windows : l''application réessaie avec « Vérifier maintenant », ou quand le modem est rebranché.'
    'Reason.BindNotElevated'       = 'Passer le port AT du modem au pilote WinUSB de Windows demande des droits d''administrateur : lancez l''application en tant qu''administrateur.'
    'Reason.BindRestartNeeded'     = 'Le port AT du modem passe au pilote WinUSB de Windows au prochain redémarrage de Windows.'
    'Reason.PortFailed'            = 'Impossible d''ouvrir le port AT du modem.'
    'Reason.SimUnknown'            = 'Lecture de la SIM.'
    'Reason.NoPin'                 = 'La SIM attend son code PIN.'
    'Reason.PinForOtherSim'        = 'Le code PIN mémorisé appartient à une autre SIM : saisissez le code PIN de cette SIM.'
    'Reason.SimNotIdentified'      = 'Impossible d''identifier la SIM : le code PIN mémorisé ne lui est donc pas envoyé.'
    'Reason.PinUnconfirmed'        = 'La dernière saisie du code PIN est restée sans réponse, et l''application n''essaie jamais deux fois : saisissez à nouveau le code PIN.'
    'Reason.LastAttempt'           = 'Il ne reste qu''une tentative de code PIN, et l''application ne l''utilisera pas : déverrouillez la SIM dans un téléphone.'
    'Reason.PukRequired'           = 'La SIM est bloquée et demande son code PUK : débloquez-la dans un téléphone. L''application ne saisit jamais de code PUK.'
    'Reason.NoSim'                 = 'Aucune SIM dans le modem.'
    'Reason.SimFailure'            = 'La SIM ne fonctionne pas.'
    'Reason.SimOther'              = 'La SIM attend un code que l''application ne gère pas.'
    'Reason.NoProfile'             = 'Aucun profil n''est activé sur l''eSIM.'
    'Reason.SimBusy'               = 'La SIM est occupée ; en attente.'
    'Reason.FccLocked'             = 'Le modem est verrouillé par le fabricant de l''ordinateur portable (verrouillage FCC) : sa radio reste désactivée.'
    'Reason.NotRegistered'         = 'Non enregistré sur un réseau.'
    'Reason.NotSearching'          = 'Non enregistré, et aucune recherche de réseau en cours.'
    'Reason.Searching'             = 'Recherche d''un réseau.'
    'Reason.Denied'                = 'Le réseau a refusé l''enregistrement.'
    'Reason.Unknown'               = 'Non enregistré ; la raison est inconnue.'
    'Reason.EmergencyOnly'         = 'Appels d''urgence uniquement.'
    'Reason.ContextUnknown'        = 'Lecture de la connexion de données.'
    'Reason.ApnPasswordUnreadable' = 'Impossible de lire le mot de passe APN mémorisé : saisissez-le à nouveau.'
    'Reason.ApnNeeded'             = 'Le réseau n''a donné aucun accès à Internet avec un APN vide : saisissez l''APN de votre opérateur.'
    'Reason.NoAddress'             = 'La connexion de données n''a pas d''adresse IPv4.'
    'Reason.AdapterDisabled'       = 'La carte réseau du modem est désactivée.'
    'Reason.NoAdapter'             = 'La carte réseau du modem est introuvable.'
    'Reason.NotElevated'           = 'La carte réseau ne peut être configurée qu''avec des droits d''administrateur : lancez l''application en tant qu''administrateur.'
    'Reason.DataPathFailed'        = 'La connexion est établie, mais aucun trafic ne passe.'
    'Reason.DohServerUnresolved'   = 'Le nom du serveur DNS over HTTPS n''a pas encore été résolu : l''application continue d''essayer et, d''ici là, laisse la carte réseau telle que le modem l''a configurée.'
    'Reason.DohNeedsServers'       = 'Le DNS chiffré nécessite des serveurs DNS de votre choix : ceux de l''opérateur ne prennent pas en charge DNS over HTTPS. La carte réseau n''est pas configurée d''ici là.'
    'Reason.DohUnavailable'        = 'Cette version de Windows ne peut pas chiffrer le DNS d''une seule carte réseau - DNS over HTTPS nécessite Windows 11 : désactivez le DNS chiffré. La carte réseau n''est pas configurée d''ici là.'
    'Reason.DohTemplateMissing'    = 'Windows ne connaît aucun modèle DNS over HTTPS pour un serveur DNS des paramètres : indiquez-en un, ou choisissez des serveurs qu''il connaît. La carte réseau n''est pas configurée d''ici là.'
    'Reason.Connected'             = 'Connecté.'
    'Reason.Other'                 = 'Non enregistré ({0}).'
    'Reason.Working'               = 'Connexion en cours de traitement.'
    'Reason.NoNetworkForMode'      = 'Aucun réseau trouvé en {0}. Aucune réinitialisation n''en trouvera : choisissez un mode réseau plus large.'
    'Reason.NoNetworkForModeBands' = 'Aucun réseau trouvé en {0} sur les bandes LTE choisies. Aucune réinitialisation n''en trouvera : choisissez un mode réseau plus large.'
    'Reason.Withheld'              = 'L''application ne fait qu''observer, elle ne passe donc pas à l''étape suivante : {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Ouverture du port AT du modem.'
    'Action.BindUsb'                 = 'Passage du port AT du modem au pilote WinUSB de Windows.'
    'Action.Initialize'              = 'Attente de la réponse du modem.'
    'Action.EnterPin'                = 'Saisie du code PIN mémorisé.'
    'Action.RadioOn'                 = 'Activation de la radio.'
    'Action.AutoRegister'            = 'Sélection automatique du réseau.'
    'Action.DefineContext'           = 'Configuration de la connexion de données.'
    'Action.ActivateContext'         = 'Configuration de la connexion de données.'
    'Action.DeactivateContext'       = 'Configuration de la connexion de données.'
    'Action.ConfigureAdapter'        = 'Configuration de la carte réseau.'
    'Action.ApplyNetworkMode'        = 'Définition du mode réseau.'
    'ActionInline.OpenPort'          = 'ouverture du port AT du modem.'
    'ActionInline.BindUsb'           = 'passage du port AT du modem au pilote WinUSB de Windows.'
    'ActionInline.Initialize'        = 'attente de la réponse du modem.'
    'ActionInline.EnterPin'          = 'saisie du code PIN mémorisé.'
    'ActionInline.RadioOn'           = 'activation de la radio.'
    'ActionInline.AutoRegister'      = 'sélection automatique du réseau.'
    'ActionInline.DefineContext'     = 'configuration de la connexion de données.'
    'ActionInline.ActivateContext'   = 'configuration de la connexion de données.'
    'ActionInline.DeactivateContext' = 'configuration de la connexion de données.'
    'ActionInline.ConfigureAdapter'  = 'configuration de la carte réseau.'
    'ActionInline.ApplyNetworkMode'  = 'définition du mode réseau.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = '4G uniquement'
    'Mode.NrOnly'                  = '5G uniquement (SA)'
    'Mode.NotManaged'              = 'Réglage actuel du modem'
    'Mode.Other'                   = 'mode {0}'
    'ModeProblem.NotKept'          = 'Le modem ne conserve pas le mode réseau tel qu''il a été écrit ; l''application ne le réécrit pas.'
    'ModeProblem.NoSupportedBand'  = 'Le modem ne prend en charge aucune des bandes choisies pour l''une de ses RAT.'
    'ModeProblem.ModeUnsupported'  = 'Le modem ne prend pas en charge ce mode réseau.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Vérification de la connexion en cours.'
    'Result.SaveSettings.Done'              = 'Paramètres enregistrés.'
    'Result.SaveSettings.NoSim'             = 'Aucune SIM n''est prête : les paramètres n''ont pas été enregistrés, car ceux de l''APN appartiennent à la SIM utilisée.'
    'Result.SaveSettings.SimChanged'        = 'La SIM utilisée a changé : les paramètres n''ont pas été enregistrés. Vérifiez ses paramètres d''APN et enregistrez à nouveau.'
    'Result.SaveSimPin.Done'                = 'Code PIN mémorisé : l''application le saisit une seule fois quand la SIM le demande.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Impossible d''identifier la SIM : le code PIN n''a pas été mémorisé.'
    'Result.ForgetSimPin.Done'              = 'Le code PIN mémorisé est supprimé.'
    'Result.DisableSimPin.Disabled'         = 'La SIM ne demande plus son code PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'La demande de code PIN de la SIM était déjà désactivée.'
    'Result.DisableSimPin.PinRejected'      = 'Code PIN incorrect : la SIM le demande toujours.'
    'Result.DisableSimPin.LastAttempt'      = 'Il ne reste qu''une tentative de code PIN : rien n''a été envoyé.'
    'Result.DisableSimPin.SimNotReady'      = 'La SIM n''est pas prête : rien n''a été envoyé.'
    'Result.DisableSimPin.Failed'           = 'Impossible de modifier la demande de code PIN de la SIM.'
    'Result.UnlockFcc.Restarted'            = 'Déverrouillage envoyé : le modem redémarre.'
    'Result.UnlockFcc.NotLocked'            = 'Le modem n''est pas verrouillé : rien n''a été écrit.'
    'Result.UnlockFcc.Unknown'              = 'Impossible de lire le verrouillage : rien n''a été écrit.'
    'Result.UnlockFcc.Failed'               = 'Le déverrouillage s''est arrêté avant le redémarrage.'
    'Result.UnlockFcc.PortLost'             = 'Le modem a disparu de l''USB pendant le déverrouillage.'
    'Result.EnableAdapter.Done'             = 'Carte réseau activée.'
    'Result.SetNetworkMode.Applied'         = 'Mode réseau envoyé : le modem s''enregistre à nouveau. Le mode est conservé dès que le modem trouve un réseau avec lui.'
    'Result.SetNetworkMode.Unchanged'       = 'Le modem a déjà ce mode réseau : il est conservé.'
    'Result.SetNetworkMode.Done'            = 'L''application ne gère plus le mode réseau : le modem conserve celui qu''il a.'
    'Result.SetNetworkMode.ModeUnsupported' = 'Le modem ne prend pas en charge ce mode réseau : rien n''a été écrit.'
    'Result.SetNetworkMode.NoSupportedBand' = 'Le modem ne prend en charge aucune des bandes choisies pour l''une de ses RAT : rien n''a été écrit.'
    'Result.SetNetworkMode.Unknown'         = 'Impossible de lire le mode réseau du modem : rien n''a été écrit.'
    'Result.NotElevated'                    = 'Cette opération nécessite des droits d''administrateur.'
    'Result.Refused'                        = 'Indisponible tant que l''application ne fait qu''observer.'
    'Result.NoModem'                        = 'Le modem n''est pas connecté.'
    'Result.PortLost'                       = 'Le modem a disparu de l''USB pendant la commande.'
    'Result.Failed'                         = 'Cela n''a pas fonctionné.'
    'Result.Other'                          = '{0} : {1}.'
    'Result.AttemptsLeft'                   = 'Tentatives restantes : {0}.'
    'Result.Restarting'                     = 'La surveillance redémarre : réessayez dans un instant.'

    # The headline.
    'Tone.Online'         = 'En ligne'
    'Tone.Working'        = 'Connexion en cours'
    'Tone.Recovering'     = 'Rétablissement'
    'Tone.Attention'      = 'Action requise'
    'Tone.Offline'        = 'Aucun modem'
    'Tone.Stopped'        = 'Surveillance arrêtée'
    'Title.ConnectionLost' = 'Connexion perdue'
    'Title.NoNetwork'     = 'Aucun réseau'
    'Title.NotConnected'  = 'Non connecté'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'Le modem n''est pas connecté en USB.'
    'Check.H2'          = 'Le modem ne répond pas.'
    'Check.H3'          = 'La SIM n''est pas prête.'
    'Check.H4'          = 'Non enregistré sur un réseau.'
    'Check.H5'          = 'La connexion de données est interrompue.'
    'Check.H6'          = 'La carte réseau n''est pas configurée.'
    'Check.H7'          = 'Aucun trafic ne passe.'
    'Check.Other'       = 'La connexion est interrompue.'
    'Step.R1'           = 'Reconfiguration de la carte réseau.'
    'Step.R2'           = 'Redémarrage de la connexion de données.'
    'Step.R3'           = 'Nouvel enregistrement sur le réseau.'
    'Step.R4'           = 'Désactivation puis réactivation de la radio.'
    'Step.R5'           = 'Redémarrage du modem.'
    'Step.R6'           = 'Redémarrage du périphérique USB du modem.'
    'StepInline.R1'     = 'reconfiguration de la carte réseau.'
    'StepInline.R2'     = 'redémarrage de la connexion de données.'
    'StepInline.R3'     = 'nouvel enregistrement sur le réseau.'
    'StepInline.R4'     = 'désactivation puis réactivation de la radio.'
    'StepInline.R5'     = 'redémarrage du modem.'
    'StepInline.R6'     = 'redémarrage du périphérique USB du modem.'
    'Recovery.Waiting'  = '{0} Les étapes de rétablissement n''ont rien donné : elles reprennent à {1}.'
    'Recovery.Slow'     = '{0} Le rétablissement a échoué {1} fois : l''application réessaie à {2}.'
    'Recovery.Withheld' = '{0} L''application ne fait qu''observer, elle n''effectue donc pas l''étape de rétablissement : {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL : {0}'
    'Tray.Open'           = 'Ouvrir'
    'Tray.CheckNow'       = 'Vérifier maintenant'
    'Tray.NetworkMode'    = 'Mode réseau'
    'Tray.NetworkModeNow' = 'Mode réseau : {0}'
    'Tray.Exit'           = 'Quitter'
    'Tray.Update'         = 'La version {0} est disponible...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Utiliser {0}, toutes les bandes'
    'Blocker.SaveApn'       = 'Enregistrer l''APN'
    'Blocker.SavePassword'  = 'Enregistrer le mot de passe'
    'Blocker.StorePin'      = 'Mémoriser le PIN'
    'Blocker.EnableAdapter' = 'Activer la carte'
    'Blocker.Unlock'        = 'Déverrouiller...'
    'Blocker.OpenSettings'  = 'Ouvrir les paramètres'
    'Blocker.ObserveOnly'   = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Blocker.NeedsAdmin'    = 'L''activer nécessite des droits d''administrateur.'
    'Blocker.UnlockNote'    = 'Le déverrouillage écrit dans la mémoire non volatile du modem : l''application demande avant de le faire.'
    'Blocker.AttemptsLeft'  = 'Tentatives restantes : {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Prête'
    'Sim.PinRequired'    = 'En attente de son code PIN'
    'Sim.PukRequired'    = 'Bloquée : code PUK requis'
    'Sim.Absent'         = 'Aucune SIM'
    'Sim.Busy'           = 'Occupée'
    'Sim.Failure'        = 'Ne fonctionne pas'
    'Sim.Other'          = 'En attente d''un autre code'
    'Sim.NoProfile'      = 'eSIM sans profil activé'
    'Sim.Unknown'        = 'État inconnu'
    'Sim.State'          = 'SIM : {0}'
    'Sim.StateAttempts'  = 'SIM : {0} - tentatives de code PIN restantes : {1}'
    'Sim.RequestOn'      = 'Demande du code PIN à la mise sous tension : activée'
    'Sim.RequestOff'     = 'Demande du code PIN à la mise sous tension : désactivée'
    'Sim.RequestUnknown' = 'Demande du code PIN à la mise sous tension : inconnue'
    'Sim.Stored'         = 'Un code PIN est mémorisé pour cette SIM.'
    'Sim.NotStored'      = 'Aucun code PIN n''est mémorisé.'
    'Sim.Rejected'       = 'Le code PIN mémorisé a été refusé et supprimé : l''application ne l''essaie plus jamais.'

    # The network tab.
    'Bands.Every'       = 'toutes les bandes'
    'Bands.EveryBut'    = 'toutes les bandes sauf {0}'
    'Bands.None'        = 'aucune'
    'Network.Current'   = 'Actuellement sur le modem : {0}.'
    'Network.Lte'       = 'LTE : {0}.'
    'Network.Nr'        = 'NR : {0}.'
    'Network.NotRead'   = 'Le mode réseau du modem n''est pas encore lu.'
    'Network.Trial'     = 'Essai de {0} : si le modem ne trouve aucun réseau avec ce mode avant {1}, il revient à son réglage précédent.'
    'Network.Reverted'  = 'À {0}, le modem n''avait trouvé aucun réseau avec {1} : il est revenu à son réglage précédent.'
    'Network.Kept'      = 'À {0}, le modem s''est enregistré avec {1} : ce mode est conservé.'
    'Network.Missing'   = 'Le modem laisse de côté {0} malgré la demande : il utilise les autres bandes choisies.'
    'Network.ChooseBand' = 'Choisissez au moins une bande {0}, ou toutes les bandes.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Le DNS chiffré n''est pas disponible sur cette version de Windows : DNS over HTTPS sur une seule carte réseau nécessite Windows 11.'
    'Dns.On'                   = 'Le DNS chiffré est activé : {0}.'
    'Dns.Waiting'              = 'Le DNS chiffré attend l''adresse de son serveur : aucun serveur DNS n''est défini en attendant.'
    'Dns.Off'                  = 'Le DNS chiffré est désactivé.'
    'Dns.Advertised'           = 'Le réseau fournit aussi des serveurs DNS IPv6 ({0}), que Windows peut utiliser en clair.'
    'Dns.LookupFailed'         = 'Impossible de résoudre {0} ; l''application continue d''essayer.'
    'Dns.LookingUp'            = 'Résolution de {0}...'
    'Dns.LookedUp'             = 'Son serveur, {0}, a été résolu à {1}.'
    'Dns.LookedUpNext'         = 'Son serveur, {0}, a été résolu à {1} ; prochaine résolution à {2}.'
    'Dns.LookedUpOperator'     = 'Son serveur, {0}, a été résolu à {1} via le DNS de l''opérateur, en clair.'
    'Dns.LookedUpOperatorNext' = 'Son serveur, {0}, a été résolu à {1} via le DNS de l''opérateur, en clair ; prochaine résolution à {2}.'
    'Dns.NotAvailableHere'     = 'Le DNS chiffré n''est pas disponible sur cette version de Windows.'
    'Dns.NoTemplate'           = 'Windows ne connaît aucun modèle DNS over HTTPS pour {0} : indiquez-en un.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1} ; la valeur par défaut est utilisée.'
    'Setting.Unknown'          = 'Le paramètre inconnu « {0} » est ignoré.'
    'Setting.Unreadable'       = 'Impossible de lire le fichier de paramètres ; les valeurs par défaut sont utilisées.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps nécessite DnsServers, ou un DohTemplate qui désigne le serveur : les serveurs de l''opérateur ne prennent pas en charge DoH, et aucun serveur DNS n''est défini tant qu''il n''y en a pas.'
    'Setting.TemplateAddress'  = 'DohTemplate désigne l''adresse {0}, il ne peut donc servir que ce serveur ; la valeur par défaut est utilisée.'
    'Rule.Text'                = 'doit être en ASCII imprimable, sans guillemets doubles ni espaces au début ou à la fin'
    'Rule.TextQuotes'          = 'doit être en ASCII imprimable, sans guillemets doubles'
    'Rule.OneOf'               = 'doit être l''une des valeurs suivantes : {0}'
    'Rule.EmptyOrOneOf'        = 'doit être vide ou l''une des valeurs suivantes : {0}'
    'Rule.Addresses'           = 'doit être une liste d''adresses IP'
    'Rule.Number'              = 'doit être un nombre entier de {0} à {1}'
    'Rule.Minutes'             = 'doit être un nombre entier de minutes de {0} à {1}'
    'Rule.Bool'                = 'doit être true ou false'
    'Rule.Https'               = 'doit être vide ou une adresse https sans espaces, guillemets ni identifiants'
    'Rule.Bands'               = 'doit être une liste de numéros de bande distincts de {0} à {1}'
    'Rule.Gigabytes'           = 'doit être un nombre de gigaoctets de {0} à {1}, 0 pour aucun'

    # The USB tab.
    'Usb.Present'                 = 'Le port AT du modem est sur le pilote WinUSB de Windows : il n''y a aucun pilote à installer.'
    'Usb.Unbound'                 = 'Le port AT du modem n''est pas encore sur le pilote WinUSB de Windows : l''application l''y passe.'
    'Usb.NotLooked'               = 'Les fonctions du modem n''ont pas encore été examinées.'
    'Usb.FunctionName'            = '{0} (MI_{1})'
    'Usb.FunctionLine'            = '{0} : {1}'
    'Usb.Function.MdAt'           = 'Port AT'
    'Usb.Function.MdMeta'         = 'Port META du modem'
    'Usb.Function.ApMeta'         = 'Port META AP'
    'Usb.Function.ApLog'          = 'Port journal AP'
    'Usb.Function.ApGnss'         = 'Port GNSS'
    'Usb.Function.Npt'            = 'Port NPT'
    'Usb.Function.Debug'          = 'Port de débogage'
    'Usb.Function.Other'          = 'Fonction'
    'Usb.OnWinUsb'                = 'WinUSB'
    'Usb.OtherDriver'             = 'un autre pilote'
    'Usb.NoDriver'                = 'aucun pilote'
    'Usb.ProblemCode'             = '{0}, code de problème {1}'
    'Usb.LastChange'              = 'Dernier passage à {0} :'
    'Usb.Bound'                   = '{0} : désormais sur WinUSB.'
    'Usb.Held'                    = '{0} : laissé sur son pilote, un autre programme tient son port.'
    'Usb.Failed'                  = '{0} : pas passé sur WinUSB ({1}).'
    'Usb.RestartNeeded'           = '{0} : sur WinUSB au prochain redémarrage de Windows.'
    'Usb.ObserveOnly'             = 'L''application ne fait qu''observer : elle ne passe aucune fonction sur WinUSB.'
    'Usb.NeedsAdmin'              = 'Passer les fonctions du modem sur WinUSB demande des droits d''administrateur : lancez l''application en tant qu''administrateur.'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'La surveillance s''est arrêtée et redémarre. La connexion n''est pas touchée.'
    'Window.NotResponding'   = 'La surveillance ne répond pas. La connexion n''est pas touchée.'
    'Window.Starting'        = 'Démarrage.'
    'Window.Simulated'       = 'Mode développement : un modem simulé (scénario {0}).'
    'Window.ObserveOnly'     = 'L''application ne fait qu''observer : elle ne modifie rien sur le modem ni sur le système.'
    'Window.SettingsPending' = 'La connexion de données est établie avec d''autres paramètres : les nouveaux s''appliquent à la prochaine connexion.'
    'Window.SettingsFile'    = 'Fichier de paramètres : {0}'
    'Window.Modems'          = '{0} modems trouvés : l''application en utilise un, toujours le même.'
    'Window.Recovered'       = 'Rétabli à {0} : {1}'
    'Window.NrAvailable'     = '{0}, 5G disponible'
    'Window.NothingMeasured' = 'Aucune mesure.'
    'Window.PasswordStored'  = 'Un mot de passe est mémorisé.'
    'Window.NoPassword'      = 'Aucun mot de passe n''est mémorisé.'
    'Window.ApnPerSim'       = 'Chaque SIM a ses propres paramètres d''APN : ceux-ci sont ceux de la SIM utilisée.'
    'Window.ApnNoSim'        = 'Chaque SIM a ses propres paramètres d''APN : ils peuvent être modifiés dès qu''une SIM est prête.'
    'Window.PinFirst'        = 'Saisissez d''abord le code PIN de la SIM : sa suppression nécessite le code PIN.'
    'Cell.Serving'           = 'Serveuse'
    'Cell.Neighbour'         = 'Voisine'
    'Carrier.Primary'        = 'Primaire'
    'Carrier.Active'         = 'Active'
    'Carrier.Inactive'       = 'Inactive'
    'Footer.Port'            = 'Port AT sur {0}'
    'Footer.PortClosed'      = 'Port AT fermé'
    'Footer.Updated'         = 'mis à jour à {0}'
    'Footer.PathChecked'     = 'chemin de données vérifié à {0}'
    'Footer.PathFailed'      = 'échec du chemin de données à {0}'
    'Footer.PathPending'     = 'chemin de données pas encore vérifié à {0}'
    'Footer.NotElevated'     = 'sans droits d''administrateur'
    'Footer.Version'         = 'version {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Déverrouiller le modem'
    'Confirm.Unlock'               = @'
Déverrouiller le modem ?

Cette opération écrit dans la mémoire non volatile du modem et lève une restriction que le fabricant de l'ordinateur portable a mise en place pour la certification de sa radio. Vous le faites sous votre propre responsabilité, et cela peut ne pas fonctionner sur tous les modules.

Le modem redémarre ensuite.
'@
    'Confirm.DisablePinTitle'      = 'Retirer le code PIN de la SIM'
    'Confirm.DisablePin'           = @'
Retirer le code PIN de la SIM ?

Cette opération modifie la carte SIM, pas l'application : la SIM ne demandera plus son code PIN, ni dans ce modem ni dans aucun téléphone. Un code PIN incorrect consomme l'une de ses tentatives.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Vérifier maintenant'
    'Xaml.SignalTab'         = 'Signal'
    'Xaml.Cells'             = 'Cellules'
    'Xaml.Cell'              = 'Cellule'
    'Xaml.Band'              = 'Bande'
    'Xaml.Channel'           = 'Canal'
    'Xaml.Bandwidth'         = 'Bande passante'
    'Xaml.CarrierAggregation' = 'Agrégation de porteuses'
    'Xaml.Carrier'           = 'Porteuse'
    'Xaml.State'             = 'État'
    'Xaml.BandwidthDlUl'     = 'Bande passante DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulation DL/UL'
    'Xaml.StorePin'          = 'Mémoriser le PIN'
    'Xaml.ForgetPin'         = 'Oublier le PIN mémorisé'
    'Xaml.DisablePin'        = 'Retirer le PIN de la SIM...'
    'Xaml.PinNote'           = 'Un code PIN mémorisé est conservé chiffré pour votre utilisateur Windows, avec la SIM à laquelle il appartient. L''application le saisit une seule fois quand cette SIM le demande - jamais deux fois, jamais quand il ne reste qu''une tentative, et jamais un code PUK.'
    'Xaml.NetworkTab'        = 'Réseau'
    'Xaml.NetworkMode'       = 'Mode réseau'
    'Xaml.Apply'             = 'Appliquer'
    'Xaml.Undo'              = 'Annuler les modifications'
    'Xaml.ModeNote'          = 'Le modem conserve son mode réseau et ses bandes, même après la fermeture de l''application. Un mode est d''abord mis à l''essai : si le modem ne trouve aucun réseau avec ce mode, il revient à son réglage précédent.'
    'Xaml.LteAll'            = 'LTE : toutes les bandes'
    'Xaml.NrAll'             = 'NR : toutes les bandes'
    'Xaml.ConnectionTab'     = 'Connexion'
    'Xaml.ApnTip'            = 'Vide : celui de votre abonnement.'
    'Xaml.PdpType'           = 'Type PDP'
    'Xaml.Authentication'    = 'Authentification'
    'Xaml.AuthNone'          = 'Aucune'
    'Xaml.User'              = 'Utilisateur'
    'Xaml.Password'          = 'Mot de passe'
    'Xaml.ClearPassword'     = 'Supprimer le mot de passe mémorisé'
    'Xaml.DnsServers'        = 'Serveurs DNS'
    'Xaml.DnsTip'            = 'Séparés par des virgules. Vide : ceux de l''opérateur.'
    'Xaml.EncryptedDns'      = 'DNS chiffré'
    'Xaml.Doh'               = 'DNS over HTTPS vers les serveurs ci-dessus, ou vers celui du modèle - jamais en clair'
    'Xaml.DohTemplate'       = 'Modèle DoH'
    'Xaml.DohTemplateTip'    = 'Vide : le modèle que Windows connaît pour chaque serveur. Sinon, une seule adresse https pour tous ; sans serveurs DNS, son nom ou son adresse est le serveur.'
    'Xaml.RefreshBefore'     = 'Résoudre son serveur toutes les'
    'Xaml.RefreshAfter'      = 'minutes, quand aucun serveur DNS n''est indiqué : le nom du modèle est le serveur.'
    'Xaml.Metric'            = 'Métrique d''interface'
    'Xaml.MetricNote'        = '500 fait du modem une connexion de secours ; une valeur basse en fait la connexion préférée.'
    'Xaml.Updates'           = 'Mises à jour'
    'Xaml.UpdateCheck'       = 'Rechercher une version plus récente une fois par démarrage'
    'Xaml.Save'              = 'Enregistrer'
    'Xaml.UsbTab'            = 'USB'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Démarrage'
    'Xaml.StartAtLogon'               = 'Démarrer l''application dans la zone de notification à l''ouverture de session Windows'
    'Startup.NotInstalled'            = 'Seule l''application installée peut démarrer à l''ouverture de session Windows.'
    'Startup.NeedsAdmin'              = 'Le modifier nécessite des droits d''administrateur.'
    'Startup.ObserveOnly'             = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Result.SetStartAtLogon.Enabled'  = 'L''application démarre désormais à l''ouverture de session Windows.'
    'Result.SetStartAtLogon.Disabled' = 'L''application ne démarre plus à l''ouverture de session Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Seule l''application installée peut démarrer à l''ouverture de session Windows : rien n''a été modifié.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Messages'
    'Xaml.From'                     = 'De'
    'Xaml.Time'                     = 'Heure'
    'Xaml.Message'                  = 'Message'
    'Xaml.DeleteMessage'            = 'Supprimer...'
    'Xaml.NewMessage'               = 'Nouveau message'
    'Xaml.To'                       = 'À'
    'Xaml.Send'                     = 'Envoyer'
    'Xaml.SendNote'                 = 'Chaque partie est un message, que l''opérateur peut facturer. Une partie qui échoue n''est jamais renvoyée d''elle-même.'
    'Messages.TabNew'               = 'Messages ({0})'
    'Messages.Storage'              = '{0} emplacements sur {1} occupés sur la SIM.'
    'Messages.Full'                 = 'La SIM est pleine : les nouveaux messages ne peuvent pas être enregistrés tant que certains ne sont pas supprimés.'
    'Messages.Empty'                = 'Aucun message sur la SIM.'
    'Messages.Hidden'               = 'Messages arrivés avec un autre profil eSIM, visibles quand il est utilisé : {0}.'
    'Messages.ObserveOnly'          = 'Les messages ne sont pas lus tant que l''application ne fait qu''observer : les lire les marque comme lus sur le modem.'
    'Messages.NoModem'              = 'Le modem n''est pas connecté.'
    'Messages.NotReady'             = 'Les messages sont lus dès que la SIM est prête.'
    'Messages.Header'               = 'De {0}, {1}'
    'Messages.Missing'              = 'Parties pas (encore) reçues : {0}.'
    'Messages.Binary'               = 'Ce message contient des données, pas du texte.'
    'Messages.Compressed'           = 'Ce message est compressé : l''application ne peut pas l''afficher.'
    'Messages.Malformed'            = 'Ce message ne peut pas être lu.'
    'Messages.NationalLanguage'     = 'Il utilise une table de langue nationale que l''application n''a pas : certains caractères peuvent être faux.'
    'Messages.Silent'               = 'Un message silencieux : le réseau a demandé qu''il ne soit jamais affiché.'
    'Messages.SilentNote'           = 'Il occupe un emplacement sur la SIM jusqu''à ce qu''il soit supprimé.'
    'Messages.Sending'              = 'Envoi du message...'
    'Messages.From'                 = 'Un message part de la SIM utilisée : le modem en utilise une à la fois. Pour envoyer depuis l''autre, mettez-la en service depuis l''onglet SIM ou eSIM.'
    'Messages.FromGoneProfile'      = 'Il est arrivé avec le profil eSIM {0}, qui n''est pas utilisé maintenant.'
    'Messages.FromOtherProfile'     = 'Il est arrivé avec un autre profil eSIM, qui n''est pas utilisé maintenant.'
    'Messages.FromOtherSim'         = 'Il est arrivé avec une autre SIM, qui n''est pas utilisée maintenant.'
    'Messages.Count'                = 'Caractères : {0} - parties : {1}'
    'Messages.CountUnicode'         = 'Caractères : {0} - parties : {1} (avec des caractères spéciaux, {2} par partie)'
    'Messages.TooLong'              = 'Trop long : un message compte au plus 255 parties.'
    'Result.SendMessage.Sent'       = 'Message envoyé.'
    'Result.SendMessage.Failed'     = 'Le message n''a pas été envoyé entièrement : {0} parties sur {1} sont parties.'
    'Result.SendMessage.Invalid'    = 'Saisissez un numéro de téléphone et un texte.'
    'Result.DeleteMessage.Done'     = 'Message supprimé de la SIM.'
    'Result.DeleteMessage.NotFound' = 'Le message n''est plus sur la SIM.'
    'Result.DeleteMessage.Failed'   = 'Le message n''a pas pu être supprimé.'
    'Result.NotReady'               = 'La SIM n''est pas prête.'
    'Confirm.DeleteMessageTitle'    = 'Supprimer le message'
    'Confirm.DeleteMessage'         = @'
Supprimer ce message de la SIM ?

Cela ne peut pas être annulé.
'@
    'Tray.NewMessage'               = 'Nouveau message'
    'Tray.NewMessages'              = '{0} nouveaux messages'
    'Tray.MessageFrom'              = 'De {0}'
    'Xaml.DataTab'                  = 'Données'
    'Xaml.CycleDay'                 = 'Le cycle de facturation commence le jour'
    'Xaml.Quota'                    = 'Forfait de données (Go)'
    'Xaml.QuotaNote'                = '0 : aucun. À 80 % et à 100 % du forfait, la zone de notification le signale, une fois par cycle ; la connexion reste active.'
    'Xaml.UsageNote'                = 'Comptées sur la carte réseau du modem : une estimation, qui peut différer du décompte de l''opérateur.'
    'Usage.Today'                   = 'Aujourd''hui : {0} (reçu {1}, envoyé {2})'
    'Usage.Cycle'                   = 'Ce cycle, du {0} au {1} : {2} (reçu {3}, envoyé {4})'
    'Usage.Quota'                   = 'Forfait : {0} utilisés sur {1} ({2} %)'
    'Usage.NoQuota'                 = 'Aucun forfait défini.'
    'Usage.NotCounted'              = 'Rien de compté encore : la carte réseau du modem n''a pas été lue.'
    'Tray.Usage'                    = 'Données aujourd''hui {0}, ce cycle {1}'
    'Tray.UsageQuota'               = 'Données aujourd''hui {0}, ce cycle {1} sur {2}'
    'Tray.QuotaTitle'               = 'Forfait de données'
    'Tray.Quota'                    = '{0} % du forfait utilisé pendant ce cycle. La connexion reste active.'

    # The eSIM tab and the SIM in use (M9).
    'Xaml.EsimTab'                              = 'eSIM'
    'Xaml.EsimProfiles'                         = 'Profils'
    'Xaml.EsimName'                             = 'Nom'
    'Xaml.EsimProvider'                         = 'Opérateur'
    'Xaml.EsimKind'                             = 'Type'
    'Xaml.EsimNickname'                         = 'Nom personnalisé'
    'Xaml.EsimEnable'                           = 'Activer...'
    'Xaml.EsimDisable'                          = 'Désactiver...'
    'Xaml.EsimDelete'                           = 'Supprimer...'
    'Xaml.EsimRename'                           = 'Renommer'
    'Xaml.EsimReadAgain'                        = 'Relire'
    'Xaml.EsimCopy'                             = 'Copier'
    'Xaml.EsimDownload'                         = 'Télécharger un profil'
    'Xaml.EsimCode'                             = 'Code d''activation (LPA:1$...), tel que l''opérateur l''a fourni'
    'Xaml.EsimReadQr'                           = 'Lire un code QR...'
    'Xaml.EsimConfirmation'                     = 'Code de confirmation, si l''opérateur en a fourni un'
    'Xaml.EsimDownloadButton'                   = 'Télécharger'
    'Xaml.EsimDownloadNote'                     = 'Un téléchargement envoie l''EID de l''eSIM au serveur de l''opérateur indiqué par le code. Le profil est téléchargé désactivé : activez-le pour l''utiliser.'
    'SimInUse.Physical'                         = 'SIM utilisée : emplacement {0}, une SIM physique.'
    'SimInUse.Esim'                             = 'SIM utilisée : emplacement {0}, l''eSIM - {1}.'
    'SimInUse.EsimEmpty'                        = 'SIM utilisée : emplacement {0}, l''eSIM, aucun profil activé.'
    'SimInUse.EsimUnread'                       = 'SIM utilisée : emplacement {0}, l''eSIM.'
    'SimInUse.Slot'                             = 'SIM utilisée : emplacement {0}.'
    'Sim.UsePhysical'                           = 'Utiliser la SIM physique (emplacement {0})...'
    'Sim.PhysicalInUse'                         = 'Utilisée : la SIM physique (emplacement {0})'
    'Esim.UseEsim'                              = 'Utiliser l''eSIM (emplacement {0})...'
    'Esim.EsimInUse'                            = 'Utilisée : l''eSIM (emplacement {0})'
    'Sim.OneAtATime'                            = 'Le modem utilise une SIM à la fois : la SIM physique (emplacement {0}) ou l''eSIM (emplacement {1}). L''onglet SIM met en service la SIM physique, l''onglet eSIM l''eSIM ; le changement interrompt la connexion un instant.'
    'Esim.Unnamed'                              = '(sans nom)'
    'Esim.NoModem'                              = 'Le modem n''est pas connecté.'
    'Esim.NoSlot'                               = 'L''emplacement SIM utilisé n''a pas encore été lu.'
    'Esim.NotInUse'                             = 'Les profils de l''eSIM ne peuvent être gérés que lorsque son emplacement est utilisé.'
    'Esim.NoLpac'                               = 'lpac n''est pas installé avec l''application : les profils de l''eSIM ne peuvent pas être gérés.'
    'Esim.ReadFailed'                           = 'L''eSIM n''a pas pu être lue : {0}'
    'Esim.NotRead'                              = 'L''eSIM n''a pas encore été lue.'
    'Esim.NoProfiles'                           = 'L''eSIM ne contient aucun profil.'
    'Esim.ObserveOnly'                          = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Esim.Chip'                                 = 'eUICC : SGP.22 {0}, micrologiciel {1}, {2} libres.'
    'Esim.Notifications'                        = 'Notifications en attente pour les serveurs des opérateurs : {0}. Elles sont envoyées à la prochaine lecture.'
    'Esim.Operation.ReadEsim'                   = 'Lecture de l''eSIM...'
    'Esim.Operation.SelectSimSlot'              = 'Changement d''emplacement SIM...'
    'Esim.Operation.EnableProfile'              = 'Activation du profil...'
    'Esim.Operation.DisableProfile'             = 'Désactivation du profil...'
    'Esim.Operation.SetProfileNickname'         = 'Enregistrement du nom...'
    'Esim.Operation.DeleteProfile'              = 'Suppression du profil...'
    'Esim.Operation.DownloadProfile'            = 'Téléchargement du profil : cela peut prendre une minute...'
    'Esim.State.Enabled'                        = 'Activé'
    'Esim.State.Disabled'                       = 'Désactivé'
    'Esim.State.Unknown'                        = 'Inconnu'
    'Esim.Class.Operational'                    = 'Opérateur'
    'Esim.Class.Test'                           = 'Test'
    'Esim.Class.Provisioning'                   = 'Provisionnement'
    'Esim.Class.Unknown'                        = 'Inconnu'
    'Esim.QrTitle'                              = 'Choisir l''image du code QR'
    'Esim.QrKind'                               = 'Images'
    'Esim.QrChosen'                             = 'Image du code QR : {0}. Son code est lu au début du téléchargement.'
    'Esim.QrMissing'                            = 'La lecture des codes QR n''est pas installée avec l''application : saisissez ou collez le code.'
    'Esim.CodeFirst'                            = 'Saisissez ou collez d''abord le code d''activation, ou choisissez l''image de son code QR.'
    'Esim.NicknameInvalid'                      = 'Un nom personnalisé fait au plus 64 octets - moins avec des lettres hors de A à Z - et aucun caractère de contrôle.'
    'Esim.CopyFailed'                           = 'L''EID n''a pas pu être copié : sélectionnez-le et copiez-le avec Ctrl+C.'
    'Blocker.OpenEsim'                          = 'Ouvrir eSIM'
    'Confirm.SelectSlotTitle'                   = 'Changer d''emplacement SIM'
    'Confirm.SelectSlot'                        = @'
Utiliser l'emplacement SIM {0} ?

Le modem garde ce choix, même après la fermeture de l'application et après un redémarrage. La connexion est coupée pendant le changement de SIM. Si l'emplacement contient l'eSIM et qu'aucun de ses profils n'est activé, il n'y a pas de réseau tant que vous n'en activez pas un.
'@
    'Confirm.EnableProfileTitle'                = 'Activer un profil eSIM'
    'Confirm.EnableProfile'                     = @'
Activer le profil "{0}" ?

La SIM redémarre avec lui : la connexion est coupée quelques secondes, puis le modem s'enregistre avec le nouveau profil. Le profil activé jusqu'ici est désactivé.
'@
    'Confirm.DisableProfileTitle'               = 'Désactiver un profil eSIM'
    'Confirm.DisableProfile'                    = @'
Désactiver le profil "{0}" ?

La SIM redémarre sans lui : sans profil activé, il n'y a pas de réseau tant que vous n'en activez pas un.
'@
    'Confirm.DeleteProfileTitle'                = 'Supprimer un profil eSIM'
    'Confirm.DeleteProfile'                     = @'
Supprimer le profil "{0}" de l'eSIM ?

C'est irréversible : pour le récupérer, l'opérateur doit vous fournir un nouveau code d'activation. Saisissez le nom du profil pour confirmer.
'@
    'Confirm.Delete'                            = 'Supprimer'
    'Confirm.Cancel'                            = 'Annuler'
    'Result.ReadEsim.Done'                      = 'eSIM lue.'
    'Result.ReadEsim.Failed'                    = 'L''eSIM n''a pas pu être lue.'
    'Result.SelectSimSlot.Done'                 = 'Emplacement SIM changé : le modem le garde.'
    'Result.SelectSimSlot.Unchanged'            = 'Cet emplacement est déjà utilisé.'
    'Result.SelectSimSlot.Failed'               = 'L''emplacement SIM n''a pas pu être changé.'
    'Result.EnableProfile.Done'                 = 'Profil activé : la SIM redémarre avec lui.'
    'Result.EnableProfile.Unchanged'            = 'Ce profil est déjà activé.'
    'Result.EnableProfile.Failed'               = 'Le profil n''a pas pu être activé.'
    'Result.DisableProfile.Done'                = 'Profil désactivé : la SIM redémarre sans lui.'
    'Result.DisableProfile.Unchanged'           = 'Ce profil n''est pas activé.'
    'Result.DisableProfile.Failed'              = 'Le profil n''a pas pu être désactivé.'
    'Result.DeleteProfile.Done'                 = 'Profil supprimé.'
    'Result.DeleteProfile.ProfileEnabled'       = 'Un profil activé ne peut pas être supprimé : désactivez-le d''abord.'
    'Result.DeleteProfile.Failed'               = 'Le profil n''a pas pu être supprimé.'
    'Result.SetProfileNickname.Done'            = 'Nom enregistré.'
    'Result.SetProfileNickname.Failed'          = 'Le nom n''a pas pu être enregistré.'
    'Result.DownloadProfile.Done'               = 'Profil téléchargé : activez-le pour l''utiliser.'
    'Result.DownloadProfile.Failed'             = 'Le profil n''a pas pu être téléchargé.'
    'Result.DownloadProfile.ConfirmationNeeded' = 'Ce code d''activation demande un code de confirmation : l''opérateur le fournit avec le code.'
    'Result.DownloadProfile.BadCode'            = 'Ce n''est pas un code d''activation eSIM.'
    'Result.DownloadProfile.BadCode.Empty'      = 'Saisissez ou collez d''abord le code d''activation.'
    'Result.DownloadProfile.BadCode.Format'     = 'Ce n''est pas un code d''activation eSIM : un tel code commence par LPA:1$.'
    'Result.DownloadProfile.BadCode.Address'    = 'Le code d''activation n''indique aucun serveur valide.'
    'Result.DownloadProfile.BadCode.MatchingId' = 'Le matching ID du code d''activation contient des caractères non autorisés.'
    'Result.DownloadProfile.NoQrCode'           = 'Aucun code d''activation n''a pu être lu dans l''image.'
    'Result.DownloadProfile.NoQrCode.NotImage'  = 'Le fichier choisi n''est pas une image que l''application sait lire.'
    'Result.DownloadProfile.NoQrCode.TooLarge'  = 'L''image est trop grande : 20 Mo et 50 mégapixels au plus.'
    'Result.DownloadProfile.NoQrCode.NoLibrary' = 'La lecture des codes QR n''est pas installée avec l''application : saisissez ou collez le code.'
    'Result.DownloadProfile.NoQrCode.NoCode'    = 'Aucun code QR trouvé dans l''image.'
    'Result.NotEuicc'                           = 'L''eSIM n''est pas la SIM utilisée.'
    'Result.NoLpac'                             = 'lpac n''est pas installé avec l''application.'
    'Result.UnknownProfile'                     = 'Ce profil n''est plus sur l''eSIM.'
    'Result.TrialOn'                            = 'Pas maintenant : un mode réseau est à l''essai.'
    'Result.Timeout'                            = 'Cela a pris trop de temps et a été interrompu.'
}
