# The app's texts in French. Same keys as en.psd1, which is the fallback of any key missing here.
# Placeholders {0}, {1}... keep the meaning they have in English. Saved as UTF-8 with a byte order
# mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Aucun modem trouvé en USB.'
    'Reason.NoDriver'              = 'Le port AT du modem n''a pas de pilote : l''application ne peut pas communiquer avec le modem tant qu''il n''est pas installé.'
    'Reason.DeviceProblem'         = 'Windows signale un problème avec le port AT du modem.'
    'Reason.PortInUse'             = 'Un autre programme utilise le port AT du modem.'
    'Reason.PortFailed'            = 'Impossible d''ouvrir le port AT du modem.'
    'Reason.SimUnknown'            = 'Lecture de la SIM.'
    'Reason.NoPin'                 = 'La SIM attend son code PIN.'
    'Reason.PinForOtherSim'        = 'Le code PIN mémorisé appartient à une autre SIM : saisissez le code PIN de cette SIM.'
    'Reason.SimNotIdentified'      = 'Impossible d''identifier la SIM : le code PIN mémorisé ne lui est donc pas envoyé.'
    'Reason.PinUnconfirmed'        = 'La dernière saisie du code PIN est restée sans réponse, et l''application n''essaie jamais deux fois : saisissez à nouveau le code PIN.'
    'Reason.LastAttempt'           = 'Il ne reste qu''une tentative de code PIN, et l''application ne l''utilisera pas : déverrouillez la SIM dans un téléphone.'
    'Reason.PukRequired'           = 'La SIM est bloquée et demande son code PUK : débloquez-la dans un téléphone. L''application ne saisit jamais de code PUK.'
    'Reason.NoSim'                 = 'Aucune SIM dans le modem.'
    'Reason.SimFailure'            = 'La SIM ne fonctionne pas.'
    'Reason.SimOther'              = 'La SIM attend un code que l''application ne gère pas.'
    'Reason.SimBusy'               = 'La SIM est occupée ; en attente.'
    'Reason.FccLocked'             = 'Le modem est verrouillé par le fabricant de l''ordinateur portable (verrouillage FCC) : sa radio reste désactivée.'
    'Reason.NotRegistered'         = 'Non enregistré sur un réseau.'
    'Reason.NotSearching'          = 'Non enregistré, et aucune recherche de réseau en cours.'
    'Reason.Searching'             = 'Recherche d''un réseau.'
    'Reason.Denied'                = 'Le réseau a refusé l''enregistrement.'
    'Reason.Unknown'               = 'Non enregistré ; la raison est inconnue.'
    'Reason.EmergencyOnly'         = 'Appels d''urgence uniquement.'
    'Reason.ContextUnknown'        = 'Lecture de la connexion de données.'
    'Reason.ApnPasswordUnreadable' = 'Impossible de lire le mot de passe APN mémorisé : saisissez-le à nouveau.'
    'Reason.ApnNeeded'             = 'Le réseau n''a donné aucun accès à Internet avec un APN vide : saisissez l''APN de votre opérateur.'
    'Reason.NoAddress'             = 'La connexion de données n''a pas d''adresse IPv4.'
    'Reason.AdapterDisabled'       = 'La carte réseau du modem est désactivée.'
    'Reason.NoAdapter'             = 'La carte réseau du modem est introuvable.'
    'Reason.NotElevated'           = 'La carte réseau ne peut être configurée qu''avec des droits d''administrateur : lancez l''application en tant qu''administrateur.'
    'Reason.DataPathFailed'        = 'La connexion est établie, mais aucun trafic ne passe.'
    'Reason.DohServerUnresolved'   = 'Le nom du serveur DNS over HTTPS n''a pas encore été résolu : l''application continue d''essayer et, d''ici là, laisse la carte réseau telle que le modem l''a configurée.'
    'Reason.DohNeedsServers'       = 'Le DNS chiffré nécessite des serveurs DNS de votre choix : ceux de l''opérateur ne prennent pas en charge DNS over HTTPS. La carte réseau n''est pas configurée d''ici là.'
    'Reason.DohUnavailable'        = 'Cette version de Windows ne peut pas chiffrer le DNS d''une seule carte réseau - DNS over HTTPS nécessite Windows 11 : désactivez le DNS chiffré. La carte réseau n''est pas configurée d''ici là.'
    'Reason.DohTemplateMissing'    = 'Windows ne connaît aucun modèle DNS over HTTPS pour un serveur DNS des paramètres : indiquez-en un, ou choisissez des serveurs qu''il connaît. La carte réseau n''est pas configurée d''ici là.'
    'Reason.Connected'             = 'Connecté.'
    'Reason.Other'                 = 'Non enregistré ({0}).'
    'Reason.Working'               = 'Connexion en cours de traitement.'
    'Reason.NoNetworkForMode'      = 'Aucun réseau trouvé en {0}. Aucune réinitialisation n''en trouvera : choisissez un mode réseau plus large.'
    'Reason.NoNetworkForModeBands' = 'Aucun réseau trouvé en {0} sur les bandes LTE choisies. Aucune réinitialisation n''en trouvera : choisissez un mode réseau plus large.'
    'Reason.Withheld'              = 'L''application ne fait qu''observer, elle ne passe donc pas à l''étape suivante : {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Ouverture du port AT du modem.'
    'Action.Initialize'              = 'Attente de la réponse du modem.'
    'Action.EnterPin'                = 'Saisie du code PIN mémorisé.'
    'Action.RadioOn'                 = 'Activation de la radio.'
    'Action.AutoRegister'            = 'Sélection automatique du réseau.'
    'Action.DefineContext'           = 'Configuration de la connexion de données.'
    'Action.ActivateContext'         = 'Configuration de la connexion de données.'
    'Action.DeactivateContext'       = 'Configuration de la connexion de données.'
    'Action.ConfigureAdapter'        = 'Configuration de la carte réseau.'
    'Action.ApplyNetworkMode'        = 'Définition du mode réseau.'
    'ActionInline.OpenPort'          = 'ouverture du port AT du modem.'
    'ActionInline.Initialize'        = 'attente de la réponse du modem.'
    'ActionInline.EnterPin'          = 'saisie du code PIN mémorisé.'
    'ActionInline.RadioOn'           = 'activation de la radio.'
    'ActionInline.AutoRegister'      = 'sélection automatique du réseau.'
    'ActionInline.DefineContext'     = 'configuration de la connexion de données.'
    'ActionInline.ActivateContext'   = 'configuration de la connexion de données.'
    'ActionInline.DeactivateContext' = 'configuration de la connexion de données.'
    'ActionInline.ConfigureAdapter'  = 'configuration de la carte réseau.'
    'ActionInline.ApplyNetworkMode'  = 'définition du mode réseau.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = '4G uniquement'
    'Mode.NrOnly'                  = '5G uniquement (SA)'
    'Mode.NotManaged'              = 'Réglage actuel du modem'
    'Mode.Other'                   = 'mode {0}'
    'ModeProblem.NotKept'          = 'Le modem ne conserve pas le mode réseau tel qu''il a été écrit ; l''application ne le réécrit pas.'
    'ModeProblem.NoSupportedBand'  = 'Le modem ne prend en charge aucune des bandes choisies pour l''une de ses RAT.'
    'ModeProblem.ModeUnsupported'  = 'Le modem ne prend pas en charge ce mode réseau.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Vérification de la connexion en cours.'
    'Result.SaveSettings.Done'              = 'Paramètres enregistrés.'
    'Result.SaveSimPin.Done'                = 'Code PIN mémorisé : l''application le saisit une seule fois quand la SIM le demande.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Impossible d''identifier la SIM : le code PIN n''a pas été mémorisé.'
    'Result.ForgetSimPin.Done'              = 'Le code PIN mémorisé est supprimé.'
    'Result.DisableSimPin.Disabled'         = 'La SIM ne demande plus son code PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'La demande de code PIN de la SIM était déjà désactivée.'
    'Result.DisableSimPin.PinRejected'      = 'Code PIN incorrect : la SIM le demande toujours.'
    'Result.DisableSimPin.LastAttempt'      = 'Il ne reste qu''une tentative de code PIN : rien n''a été envoyé.'
    'Result.DisableSimPin.SimNotReady'      = 'La SIM n''est pas prête : rien n''a été envoyé.'
    'Result.DisableSimPin.Failed'           = 'Impossible de modifier la demande de code PIN de la SIM.'
    'Result.UnlockFcc.Restarted'            = 'Déverrouillage envoyé : le modem redémarre.'
    'Result.UnlockFcc.NotLocked'            = 'Le modem n''est pas verrouillé : rien n''a été écrit.'
    'Result.UnlockFcc.Unknown'              = 'Impossible de lire le verrouillage : rien n''a été écrit.'
    'Result.UnlockFcc.Failed'               = 'Le déverrouillage s''est arrêté avant le redémarrage.'
    'Result.UnlockFcc.PortLost'             = 'Le modem a disparu de l''USB pendant le déverrouillage.'
    'Result.EnableAdapter.Done'             = 'Carte réseau activée.'
    'Result.SetNetworkMode.Applied'         = 'Mode réseau envoyé : le modem s''enregistre à nouveau. Le mode est conservé dès que le modem trouve un réseau avec lui.'
    'Result.SetNetworkMode.Unchanged'       = 'Le modem a déjà ce mode réseau : il est conservé.'
    'Result.SetNetworkMode.Done'            = 'L''application ne gère plus le mode réseau : le modem conserve celui qu''il a.'
    'Result.SetNetworkMode.ModeUnsupported' = 'Le modem ne prend pas en charge ce mode réseau : rien n''a été écrit.'
    'Result.SetNetworkMode.NoSupportedBand' = 'Le modem ne prend en charge aucune des bandes choisies pour l''une de ses RAT : rien n''a été écrit.'
    'Result.SetNetworkMode.Unknown'         = 'Impossible de lire le mode réseau du modem : rien n''a été écrit.'
    'Result.CheckDriverPackage.Verified'    = 'Package du pilote vérifié : une version que l''application connaît.'
    'Result.CheckDriverPackage.Signed'      = 'Package du pilote vérifié : signé par Microsoft, une version que l''application ne connaît pas.'
    'Result.CheckDriverPackage.Refused'     = 'Le package du pilote ne peut pas être installé : l''onglet Pilote en indique la raison.'
    'Result.CheckDriverPackage.NoPackage'   = 'Aucun package du pilote n''a été choisi.'
    'Result.CheckDriverPackage.Failed'      = 'Impossible de lire le package du pilote.'
    'Result.InstallDriver.Done'             = 'Pilote installé : l''application ouvre le port AT du modem dès que Windows le démarre.'
    'Result.InstallDriver.RestartNeeded'    = 'Pilote installé : Windows doit redémarrer pour terminer.'
    'Result.InstallDriver.NoDevice'         = 'Pilote ajouté à Windows, mais aucun périphérique ne l''a adopté : il est utilisé quand le modem est branché, sauf si Windows classe un autre pilote devant lui.'
    'Result.InstallDriver.Unconfirmed'      = 'Non installé : une version que l''application ne connaît pas nécessite votre confirmation.'
    'Result.InstallDriver.NoPackage'        = 'Choisissez d''abord un package du pilote.'
    'Result.InstallDriver.DriverWorking'    = 'Le port AT a déjà un pilote qui fonctionne : rien n''a été installé.'
    'Result.InstallDriver.TimedOut'         = 'Windows n''a pas terminé l''installation du pilote à temps : elle a été arrêtée.'
    'Result.InstallDriver.Failed'           = 'Windows n''a pas installé le pilote.'
    'Result.UninstallDriver.Done'           = 'Pilote désinstallé : l''application ne peut pas communiquer avec le modem tant qu''il n''est pas réinstallé.'
    'Result.UninstallDriver.RestartNeeded'  = 'Pilote désinstallé : Windows doit redémarrer pour terminer.'
    'Result.UninstallDriver.NoDriver'       = 'Le port AT n''a aucun pilote que l''application puisse désinstaller.'
    'Result.UninstallDriver.TrialOn'        = 'Non désinstallé : un mode réseau est à l''essai, et seul le port AT permet de rétablir le mode précédent.'
    'Result.UninstallDriver.TimedOut'       = 'Windows n''a pas terminé la désinstallation du pilote à temps : elle a été arrêtée.'
    'Result.UninstallDriver.Failed'         = 'Windows n''a pas désinstallé le pilote.'
    'Result.NotElevated'                    = 'Cette opération nécessite des droits d''administrateur.'
    'Result.Refused'                        = 'Indisponible tant que l''application ne fait qu''observer.'
    'Result.NoModem'                        = 'Le modem n''est pas connecté.'
    'Result.PortLost'                       = 'Le modem a disparu de l''USB pendant la commande.'
    'Result.Failed'                         = 'Cela n''a pas fonctionné.'
    'Result.Other'                          = '{0} : {1}.'
    'Result.AttemptsLeft'                   = 'Tentatives restantes : {0}.'
    'Result.Restarting'                     = 'La surveillance redémarre : réessayez dans un instant.'

    # The headline.
    'Tone.Online'         = 'En ligne'
    'Tone.Working'        = 'Connexion en cours'
    'Tone.Recovering'     = 'Rétablissement'
    'Tone.Attention'      = 'Action requise'
    'Tone.Offline'        = 'Aucun modem'
    'Tone.Stopped'        = 'Surveillance arrêtée'
    'Title.ConnectionLost' = 'Connexion perdue'
    'Title.NoNetwork'     = 'Aucun réseau'
    'Title.NotConnected'  = 'Non connecté'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'Le modem n''est pas connecté en USB.'
    'Check.H2'          = 'Le modem ne répond pas.'
    'Check.H3'          = 'La SIM n''est pas prête.'
    'Check.H4'          = 'Non enregistré sur un réseau.'
    'Check.H5'          = 'La connexion de données est interrompue.'
    'Check.H6'          = 'La carte réseau n''est pas configurée.'
    'Check.H7'          = 'Aucun trafic ne passe.'
    'Check.Other'       = 'La connexion est interrompue.'
    'Step.R1'           = 'Reconfiguration de la carte réseau.'
    'Step.R2'           = 'Redémarrage de la connexion de données.'
    'Step.R3'           = 'Nouvel enregistrement sur le réseau.'
    'Step.R4'           = 'Désactivation puis réactivation de la radio.'
    'Step.R5'           = 'Redémarrage du modem.'
    'Step.R6'           = 'Redémarrage du périphérique USB du modem.'
    'StepInline.R1'     = 'reconfiguration de la carte réseau.'
    'StepInline.R2'     = 'redémarrage de la connexion de données.'
    'StepInline.R3'     = 'nouvel enregistrement sur le réseau.'
    'StepInline.R4'     = 'désactivation puis réactivation de la radio.'
    'StepInline.R5'     = 'redémarrage du modem.'
    'StepInline.R6'     = 'redémarrage du périphérique USB du modem.'
    'Recovery.Waiting'  = '{0} Les étapes de rétablissement n''ont rien donné : elles reprennent à {1}.'
    'Recovery.Slow'     = '{0} Le rétablissement a échoué {1} fois : l''application réessaie à {2}.'
    'Recovery.Withheld' = '{0} L''application ne fait qu''observer, elle n''effectue donc pas l''étape de rétablissement : {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL : {0}'
    'Tray.Open'           = 'Ouvrir'
    'Tray.CheckNow'       = 'Vérifier maintenant'
    'Tray.NetworkMode'    = 'Mode réseau'
    'Tray.NetworkModeNow' = 'Mode réseau : {0}'
    'Tray.Exit'           = 'Quitter'
    'Tray.Update'         = 'La version {0} est disponible...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Utiliser {0}, toutes les bandes'
    'Blocker.SaveApn'       = 'Enregistrer l''APN'
    'Blocker.SavePassword'  = 'Enregistrer le mot de passe'
    'Blocker.StorePin'      = 'Mémoriser le PIN'
    'Blocker.EnableAdapter' = 'Activer la carte'
    'Blocker.Unlock'        = 'Déverrouiller...'
    'Blocker.InstallDriver' = 'Installer le pilote...'
    'Blocker.OpenSettings'  = 'Ouvrir les paramètres'
    'Blocker.ObserveOnly'   = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Blocker.NeedsAdmin'    = 'L''activer nécessite des droits d''administrateur.'
    'Blocker.UnlockNote'    = 'Le déverrouillage écrit dans la mémoire non volatile du modem : l''application demande avant de le faire.'
    'Blocker.AttemptsLeft'  = 'Tentatives restantes : {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Prête'
    'Sim.PinRequired'    = 'En attente de son code PIN'
    'Sim.PukRequired'    = 'Bloquée : code PUK requis'
    'Sim.Absent'         = 'Aucune SIM'
    'Sim.Busy'           = 'Occupée'
    'Sim.Failure'        = 'Ne fonctionne pas'
    'Sim.Other'          = 'En attente d''un autre code'
    'Sim.Unknown'        = 'État inconnu'
    'Sim.State'          = 'SIM : {0}'
    'Sim.StateAttempts'  = 'SIM : {0} - tentatives de code PIN restantes : {1}'
    'Sim.RequestOn'      = 'Demande du code PIN à la mise sous tension : activée'
    'Sim.RequestOff'     = 'Demande du code PIN à la mise sous tension : désactivée'
    'Sim.RequestUnknown' = 'Demande du code PIN à la mise sous tension : inconnue'
    'Sim.Stored'         = 'Un code PIN est mémorisé pour cette SIM.'
    'Sim.NotStored'      = 'Aucun code PIN n''est mémorisé.'
    'Sim.Rejected'       = 'Le code PIN mémorisé a été refusé et supprimé : l''application ne l''essaie plus jamais.'

    # The network tab.
    'Bands.Every'       = 'toutes les bandes'
    'Bands.EveryBut'    = 'toutes les bandes sauf {0}'
    'Bands.None'        = 'aucune'
    'Network.Current'   = 'Actuellement sur le modem : {0}.'
    'Network.Lte'       = 'LTE : {0}.'
    'Network.Nr'        = 'NR : {0}.'
    'Network.NotRead'   = 'Le mode réseau du modem n''est pas encore lu.'
    'Network.Trial'     = 'Essai de {0} : si le modem ne trouve aucun réseau avec ce mode avant {1}, il revient à son réglage précédent.'
    'Network.Reverted'  = 'À {0}, le modem n''avait trouvé aucun réseau avec {1} : il est revenu à son réglage précédent.'
    'Network.Kept'      = 'À {0}, le modem s''est enregistré avec {1} : ce mode est conservé.'
    'Network.Missing'   = 'Le modem laisse de côté {0} malgré la demande : il utilise les autres bandes choisies.'
    'Network.ChooseBand' = 'Choisissez au moins une bande {0}, ou toutes les bandes.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Le DNS chiffré n''est pas disponible sur cette version de Windows : DNS over HTTPS sur une seule carte réseau nécessite Windows 11.'
    'Dns.On'                   = 'Le DNS chiffré est activé : {0}.'
    'Dns.Waiting'              = 'Le DNS chiffré attend l''adresse de son serveur : aucun serveur DNS n''est défini en attendant.'
    'Dns.Off'                  = 'Le DNS chiffré est désactivé.'
    'Dns.Advertised'           = 'Le réseau fournit aussi des serveurs DNS IPv6 ({0}), que Windows peut utiliser en clair.'
    'Dns.LookupFailed'         = 'Impossible de résoudre {0} ; l''application continue d''essayer.'
    'Dns.LookingUp'            = 'Résolution de {0}...'
    'Dns.LookedUp'             = 'Son serveur, {0}, a été résolu à {1}.'
    'Dns.LookedUpNext'         = 'Son serveur, {0}, a été résolu à {1} ; prochaine résolution à {2}.'
    'Dns.LookedUpOperator'     = 'Son serveur, {0}, a été résolu à {1} via le DNS de l''opérateur, en clair.'
    'Dns.LookedUpOperatorNext' = 'Son serveur, {0}, a été résolu à {1} via le DNS de l''opérateur, en clair ; prochaine résolution à {2}.'
    'Dns.NotAvailableHere'     = 'Le DNS chiffré n''est pas disponible sur cette version de Windows.'
    'Dns.NoTemplate'           = 'Windows ne connaît aucun modèle DNS over HTTPS pour {0} : indiquez-en un.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1} ; la valeur par défaut est utilisée.'
    'Setting.Unknown'          = 'Le paramètre inconnu « {0} » est ignoré.'
    'Setting.Unreadable'       = 'Impossible de lire le fichier de paramètres ; les valeurs par défaut sont utilisées.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps nécessite DnsServers, ou un DohTemplate qui désigne le serveur : les serveurs de l''opérateur ne prennent pas en charge DoH, et aucun serveur DNS n''est défini tant qu''il n''y en a pas.'
    'Setting.TemplateAddress'  = 'DohTemplate désigne l''adresse {0}, il ne peut donc servir que ce serveur ; la valeur par défaut est utilisée.'
    'Rule.Text'                = 'doit être en ASCII imprimable, sans guillemets doubles ni espaces au début ou à la fin'
    'Rule.TextQuotes'          = 'doit être en ASCII imprimable, sans guillemets doubles'
    'Rule.OneOf'               = 'doit être l''une des valeurs suivantes : {0}'
    'Rule.EmptyOrOneOf'        = 'doit être vide ou l''une des valeurs suivantes : {0}'
    'Rule.Addresses'           = 'doit être une liste d''adresses IP'
    'Rule.Number'              = 'doit être un nombre entier de {0} à {1}'
    'Rule.Minutes'             = 'doit être un nombre entier de minutes de {0} à {1}'
    'Rule.Bool'                = 'doit être true ou false'
    'Rule.Https'               = 'doit être vide ou une adresse https sans espaces, guillemets ni identifiants'
    'Rule.Bands'               = 'doit être une liste de numéros de bande distincts de {0} à {1}'
    'Rule.Gigabytes'           = 'doit être un nombre de gigaoctets de {0} à {1}, 0 pour aucun'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'il ne contient aucun pilote (aucun fichier INF)'
    'DriverProblem.NotForModem'  = 'aucun de ses pilotes n''est destiné au port AT de ce modem'
    'DriverProblem.NoCatalog'    = 'son pilote n''a pas de catalogue de signature'
    'DriverProblem.NotWhql'      = 'son catalogue n''est pas signé par Microsoft (WHQL)'
    'DriverProblem.NotInCatalog' = 'son fichier INF n''est pas celui que garantit son catalogue : il a été modifié ou est endommagé'
    'DriverProblem.NotTrusted'   = 'sa signature ne peut pas être vérifiée'
    'Driver.Present'             = 'Le port AT du modem a son pilote.'
    'Driver.PresentWhat'         = 'Le port AT du modem a son pilote : {0}.'
    'Driver.NoDriver'            = 'Le port AT du modem n''a pas de pilote : l''application ne peut pas communiquer avec le modem.'
    'Driver.Problem'             = 'Windows signale un problème avec le port AT du modem : réinstaller son pilote peut le résoudre.'
    'Driver.Absent'              = 'Aucun modem en USB. Un pilote installé maintenant est utilisé dès que le modem est branché.'
    'Driver.NotLooked'           = 'Le port AT du modem n''a pas encore été examiné.'
    'Driver.Source'              = 'L''application n''est pas fournie avec le pilote du modem : elle n''a pas de licence pour le redistribuer. Téléchargez-en une copie, puis choisissez-la ici : l''application vérifie que Microsoft l''a signée (WHQL) pour ce modem, et n''exécute jamais aucun programme qu''elle contient.'
    'Driver.SourceCopy'          = 'L''application n''est pas fournie avec le pilote du modem : elle n''a pas de licence pour le redistribuer. Une copie du pilote de MediaTek, {0}, est publiée par un tiers, {1}, sous le nom {2}. Téléchargez-la, puis choisissez-la ici : l''application vérifie que Microsoft l''a signée (WHQL) pour ce modem, et n''exécute jamais aucun programme qu''elle contient.'
    'Driver.Checking'            = 'Vérification du package du pilote...'
    'Driver.Installing'          = 'Installation du pilote : Windows peut prendre une minute.'
    'Driver.Uninstalling'        = 'Désinstallation du pilote...'
    'Driver.Verified'            = '{0} : {1}, une version que l''application connaît, signée par Microsoft (WHQL) pour ce modem.'
    'Driver.Signed'              = '{0} : {1}, signée par Microsoft (WHQL) pour ce modem, mais pas une version que l''application connaît : elle demande avant de l''installer.'
    'Driver.Refused'             = '{0} ne peut pas être installé : {1}.'
    'Driver.ObserveOnly'         = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Driver.NeedsAdmin'          = 'L''installation ou la désinstallation d''un pilote nécessite des droits d''administrateur : lancez l''application en tant qu''administrateur.'
    'Driver.Trial'               = 'Un mode réseau est à l''essai : le pilote pourra être désinstallé à la fin de l''essai.'
    'Driver.Install'             = 'Installer'
    'Driver.InstallConfirm'      = 'Installer...'
    'Driver.ChooseTitle'         = 'Choisir le package du pilote téléchargé'
    'Driver.FileKind'            = 'Package du pilote'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'La surveillance s''est arrêtée et redémarre. La connexion n''est pas touchée.'
    'Window.NotResponding'   = 'La surveillance ne répond pas. La connexion n''est pas touchée.'
    'Window.Starting'        = 'Démarrage.'
    'Window.Simulated'       = 'Mode développement : un modem simulé (scénario {0}).'
    'Window.ObserveOnly'     = 'L''application ne fait qu''observer : elle ne modifie rien sur le modem ni sur le système.'
    'Window.SettingsPending' = 'La connexion de données est établie avec d''autres paramètres : les nouveaux s''appliquent à la prochaine connexion.'
    'Window.SettingsFile'    = 'Fichier de paramètres : {0}'
    'Window.Modems'          = '{0} modems trouvés : l''application utilise celui sur {1}.'
    'Window.Recovered'       = 'Rétabli à {0} : {1}'
    'Window.NrAvailable'     = '{0}, 5G disponible'
    'Window.NothingMeasured' = 'Aucune mesure.'
    'Window.PasswordStored'  = 'Un mot de passe est mémorisé.'
    'Window.NoPassword'      = 'Aucun mot de passe n''est mémorisé.'
    'Window.PinFirst'        = 'Saisissez d''abord le code PIN de la SIM : sa suppression nécessite le code PIN.'
    'Cell.Serving'           = 'Serveuse'
    'Cell.Neighbour'         = 'Voisine'
    'Carrier.Primary'        = 'Primaire'
    'Carrier.Active'         = 'Active'
    'Carrier.Inactive'       = 'Inactive'
    'Footer.Port'            = 'Port AT {0}'
    'Footer.PortClosed'      = 'Port AT fermé'
    'Footer.Updated'         = 'mis à jour à {0}'
    'Footer.PathChecked'     = 'chemin de données vérifié à {0}'
    'Footer.PathFailed'      = 'échec du chemin de données à {0}'
    'Footer.PathPending'     = 'chemin de données pas encore vérifié à {0}'
    'Footer.NotElevated'     = 'sans droits d''administrateur'
    'Footer.Version'         = 'version {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Déverrouiller le modem'
    'Confirm.Unlock'               = @'
Déverrouiller le modem ?

Cette opération écrit dans la mémoire non volatile du modem et lève une restriction que le fabricant de l'ordinateur portable a mise en place pour la certification de sa radio. Vous le faites sous votre propre responsabilité, et cela peut ne pas fonctionner sur tous les modules.

Le modem redémarre ensuite.
'@
    'Confirm.DisablePinTitle'      = 'Retirer le code PIN de la SIM'
    'Confirm.DisablePin'           = @'
Retirer le code PIN de la SIM ?

Cette opération modifie la carte SIM, pas l'application : la SIM ne demandera plus son code PIN, ni dans ce modem ni dans aucun téléphone. Un code PIN incorrect consomme l'une de ses tentatives.
'@
    'Confirm.UnknownDriverTitle'   = 'Installer une version de pilote inconnue'
    'Confirm.UnknownDriver'        = @'
Installer une version de pilote que l'application ne connaît pas ?

Microsoft a signé ce package (WHQL) pour le port AT du modem, Windows l'accepte donc ; mais ce n'est pas une version que l'application connaît.

Windows l'installe pour chaque périphérique auquel il convient.
'@
    'Confirm.UninstallDriverTitle' = 'Désinstaller le pilote'
    'Confirm.UninstallDriver'      = @'
Désinstaller le pilote du port AT du modem ?

Windows le supprime des ports série du modem et du magasin de pilotes. La connexion de données reste établie, mais l'application ne peut plus communiquer avec le modem, ni surveiller la connexion, tant que le pilote n'est pas réinstallé.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Vérifier maintenant'
    'Xaml.SignalTab'         = 'Signal'
    'Xaml.Cells'             = 'Cellules'
    'Xaml.Cell'              = 'Cellule'
    'Xaml.Band'              = 'Bande'
    'Xaml.Channel'           = 'Canal'
    'Xaml.Bandwidth'         = 'Bande passante'
    'Xaml.CarrierAggregation' = 'Agrégation de porteuses'
    'Xaml.Carrier'           = 'Porteuse'
    'Xaml.State'             = 'État'
    'Xaml.BandwidthDlUl'     = 'Bande passante DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulation DL/UL'
    'Xaml.StorePin'          = 'Mémoriser le PIN'
    'Xaml.ForgetPin'         = 'Oublier le PIN mémorisé'
    'Xaml.DisablePin'        = 'Retirer le PIN de la SIM...'
    'Xaml.PinNote'           = 'Un code PIN mémorisé est conservé chiffré pour votre utilisateur Windows, avec la SIM à laquelle il appartient. L''application le saisit une seule fois quand cette SIM le demande - jamais deux fois, jamais quand il ne reste qu''une tentative, et jamais un code PUK.'
    'Xaml.NetworkTab'        = 'Réseau'
    'Xaml.NetworkMode'       = 'Mode réseau'
    'Xaml.Apply'             = 'Appliquer'
    'Xaml.Undo'              = 'Annuler les modifications'
    'Xaml.ModeNote'          = 'Le modem conserve son mode réseau et ses bandes, même après la fermeture de l''application. Un mode est d''abord mis à l''essai : si le modem ne trouve aucun réseau avec ce mode, il revient à son réglage précédent.'
    'Xaml.LteAll'            = 'LTE : toutes les bandes'
    'Xaml.NrAll'             = 'NR : toutes les bandes'
    'Xaml.ConnectionTab'     = 'Connexion'
    'Xaml.ApnTip'            = 'Vide : celui de votre abonnement.'
    'Xaml.PdpType'           = 'Type PDP'
    'Xaml.Authentication'    = 'Authentification'
    'Xaml.AuthNone'          = 'Aucune'
    'Xaml.User'              = 'Utilisateur'
    'Xaml.Password'          = 'Mot de passe'
    'Xaml.ClearPassword'     = 'Supprimer le mot de passe mémorisé'
    'Xaml.DnsServers'        = 'Serveurs DNS'
    'Xaml.DnsTip'            = 'Séparés par des virgules. Vide : ceux de l''opérateur.'
    'Xaml.EncryptedDns'      = 'DNS chiffré'
    'Xaml.Doh'               = 'DNS over HTTPS vers les serveurs ci-dessus, ou vers celui du modèle - jamais en clair'
    'Xaml.DohTemplate'       = 'Modèle DoH'
    'Xaml.DohTemplateTip'    = 'Vide : le modèle que Windows connaît pour chaque serveur. Sinon, une seule adresse https pour tous ; sans serveurs DNS, son nom ou son adresse est le serveur.'
    'Xaml.RefreshBefore'     = 'Résoudre son serveur toutes les'
    'Xaml.RefreshAfter'      = 'minutes, quand aucun serveur DNS n''est indiqué : le nom du modèle est le serveur.'
    'Xaml.Metric'            = 'Métrique d''interface'
    'Xaml.MetricNote'        = '500 fait du modem une connexion de secours ; une valeur basse en fait la connexion préférée.'
    'Xaml.Updates'           = 'Mises à jour'
    'Xaml.UpdateCheck'       = 'Rechercher une version plus récente une fois par démarrage'
    'Xaml.Save'              = 'Enregistrer'
    'Xaml.DriverTab'         = 'Pilote'
    'Xaml.OpenPage'          = 'Ouvrir la page de téléchargement'
    'Xaml.ChoosePackage'     = 'Choisir le package téléchargé...'
    'Xaml.Install'           = 'Installer'
    'Xaml.UninstallDriver'   = 'Désinstaller le pilote...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Démarrage'
    'Xaml.StartAtLogon'               = 'Démarrer l''application dans la zone de notification à l''ouverture de session Windows'
    'Startup.NotInstalled'            = 'Seule l''application installée peut démarrer à l''ouverture de session Windows.'
    'Startup.NeedsAdmin'              = 'Le modifier nécessite des droits d''administrateur.'
    'Startup.ObserveOnly'             = 'L''application ne fait qu''observer : elle ne modifie rien.'
    'Result.SetStartAtLogon.Enabled'  = 'L''application démarre désormais à l''ouverture de session Windows.'
    'Result.SetStartAtLogon.Disabled' = 'L''application ne démarre plus à l''ouverture de session Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Seule l''application installée peut démarrer à l''ouverture de session Windows : rien n''a été modifié.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Messages'
    'Xaml.From'                     = 'De'
    'Xaml.Time'                     = 'Heure'
    'Xaml.Message'                  = 'Message'
    'Xaml.DeleteMessage'            = 'Supprimer...'
    'Xaml.NewMessage'               = 'Nouveau message'
    'Xaml.To'                       = 'À'
    'Xaml.Send'                     = 'Envoyer'
    'Xaml.SendNote'                 = 'Chaque partie est un message, que l''opérateur peut facturer. Une partie qui échoue n''est jamais renvoyée d''elle-même.'
    'Messages.TabNew'               = 'Messages ({0})'
    'Messages.Storage'              = '{0} emplacements sur {1} occupés sur la SIM.'
    'Messages.Full'                 = 'La SIM est pleine : les nouveaux messages ne peuvent pas être enregistrés tant que certains ne sont pas supprimés.'
    'Messages.Empty'                = 'Aucun message sur la SIM.'
    'Messages.ObserveOnly'          = 'Les messages ne sont pas lus tant que l''application ne fait qu''observer : les lire les marque comme lus sur le modem.'
    'Messages.NoModem'              = 'Le modem n''est pas connecté.'
    'Messages.NotReady'             = 'Les messages sont lus dès que la SIM est prête.'
    'Messages.Header'               = 'De {0}, {1}'
    'Messages.Missing'              = 'Parties pas (encore) reçues : {0}.'
    'Messages.Binary'               = 'Ce message contient des données, pas du texte.'
    'Messages.Compressed'           = 'Ce message est compressé : l''application ne peut pas l''afficher.'
    'Messages.Malformed'            = 'Ce message ne peut pas être lu.'
    'Messages.NationalLanguage'     = 'Il utilise une table de langue nationale que l''application n''a pas : certains caractères peuvent être faux.'
    'Messages.Silent'               = 'Un message silencieux : le réseau a demandé qu''il ne soit jamais affiché.'
    'Messages.SilentNote'           = 'Il occupe un emplacement sur la SIM jusqu''à ce qu''il soit supprimé.'
    'Messages.Sending'              = 'Envoi du message...'
    'Messages.Count'                = 'Caractères : {0} - parties : {1}'
    'Messages.CountUnicode'         = 'Caractères : {0} - parties : {1} (avec des caractères spéciaux, {2} par partie)'
    'Messages.TooLong'              = 'Trop long : un message compte au plus 255 parties.'
    'Result.SendMessage.Sent'       = 'Message envoyé.'
    'Result.SendMessage.Failed'     = 'Le message n''a pas été envoyé entièrement : {0} parties sur {1} sont parties.'
    'Result.SendMessage.Invalid'    = 'Saisissez un numéro de téléphone et un texte.'
    'Result.DeleteMessage.Done'     = 'Message supprimé de la SIM.'
    'Result.DeleteMessage.NotFound' = 'Le message n''est plus sur la SIM.'
    'Result.DeleteMessage.Failed'   = 'Le message n''a pas pu être supprimé.'
    'Result.NotReady'               = 'La SIM n''est pas prête.'
    'Confirm.DeleteMessageTitle'    = 'Supprimer le message'
    'Confirm.DeleteMessage'         = @'
Supprimer ce message de la SIM ?

Cela ne peut pas être annulé.
'@
    'Tray.NewMessage'               = 'Nouveau message'
    'Tray.NewMessages'              = '{0} nouveaux messages'
    'Tray.MessageFrom'              = 'De {0}'
    'Xaml.DataTab'                  = 'Données'
    'Xaml.CycleDay'                 = 'Le cycle de facturation commence le jour'
    'Xaml.Quota'                    = 'Forfait de données (Go)'
    'Xaml.QuotaNote'                = '0 : aucun. À 80 % et à 100 % du forfait, la zone de notification le signale, une fois par cycle ; la connexion reste active.'
    'Xaml.UsageNote'                = 'Comptées sur la carte réseau du modem : une estimation, qui peut différer du décompte de l''opérateur.'
    'Usage.Today'                   = 'Aujourd''hui : {0} (reçu {1}, envoyé {2})'
    'Usage.Cycle'                   = 'Ce cycle, du {0} au {1} : {2} (reçu {3}, envoyé {4})'
    'Usage.Quota'                   = 'Forfait : {0} utilisés sur {1} ({2} %)'
    'Usage.NoQuota'                 = 'Aucun forfait défini.'
    'Usage.NotCounted'              = 'Rien de compté encore : la carte réseau du modem n''a pas été lue.'
    'Tray.Usage'                    = 'Données aujourd''hui {0}, ce cycle {1}'
    'Tray.UsageQuota'               = 'Données aujourd''hui {0}, ce cycle {1} sur {2}'
    'Tray.QuotaTitle'               = 'Forfait de données'
    'Tray.Quota'                    = '{0} % du forfait utilisé pendant ce cycle. La connexion reste active.'
}
