# The app's texts in Italian: the same keys as en.psd1, which is the fallback of any key missing here.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Nessun modem trovato su USB.'
    'Reason.NoDriver'              = 'La porta AT del modem non ha un driver: l''app non può comunicare con il modem finché non viene installato.'
    'Reason.DeviceProblem'         = 'Windows segnala un problema con la porta AT del modem.'
    'Reason.PortInUse'             = 'Un altro programma sta usando la porta AT del modem.'
    'Reason.PortFailed'            = 'Impossibile aprire la porta AT del modem.'
    'Reason.SimUnknown'            = 'Lettura della SIM in corso.'
    'Reason.NoPin'                 = 'La SIM attende il PIN.'
    'Reason.PinForOtherSim'        = 'Il PIN memorizzato appartiene a un''altra SIM: inserisci il PIN di questa SIM.'
    'Reason.SimNotIdentified'      = 'Impossibile identificare la SIM, quindi il PIN memorizzato non le viene inviato.'
    'Reason.PinUnconfirmed'        = 'L''ultimo inserimento del PIN non ha ricevuto risposta e l''app non riprova mai una seconda volta: inserisci di nuovo il PIN.'
    'Reason.LastAttempt'           = 'Resta un solo tentativo per il PIN e l''app non lo usa: sblocca la SIM in un telefono.'
    'Reason.PukRequired'           = 'La SIM è bloccata e richiede il PUK: sbloccala in un telefono. L''app non inserisce mai un PUK.'
    'Reason.NoSim'                 = 'Nessuna SIM nel modem.'
    'Reason.SimFailure'            = 'La SIM non funziona.'
    'Reason.SimOther'              = 'La SIM attende un codice che l''app non gestisce.'
    'Reason.SimBusy'               = 'La SIM è occupata; in attesa che sia pronta.'
    'Reason.FccLocked'             = 'Il modem è bloccato dal produttore del suo portatile (blocco FCC): la radio resta spenta.'
    'Reason.NotRegistered'         = 'Non registrato sulla rete.'
    'Reason.NotSearching'          = 'Non registrato sulla rete e nessuna ricerca di rete in corso.'
    'Reason.Searching'             = 'Ricerca di una rete in corso.'
    'Reason.Denied'                = 'La rete ha rifiutato la registrazione.'
    'Reason.Unknown'               = 'Non registrato sulla rete; il motivo è sconosciuto.'
    'Reason.EmergencyOnly'         = 'Solo chiamate di emergenza.'
    'Reason.ContextUnknown'        = 'Lettura della connessione dati in corso.'
    'Reason.ApnPasswordUnreadable' = 'Impossibile leggere la password APN memorizzata: inseriscila di nuovo.'
    'Reason.ApnNeeded'             = 'Con un APN vuoto la rete non ha dato accesso a Internet: inserisci l''APN del tuo operatore.'
    'Reason.NoAddress'             = 'La connessione dati non ha un indirizzo IPv4.'
    'Reason.AdapterDisabled'       = 'L''adattatore di rete del modem è disabilitato.'
    'Reason.NoAdapter'             = 'L''adattatore di rete del modem non è presente.'
    'Reason.NotElevated'           = 'L''adattatore di rete si può configurare solo con i diritti di amministratore: avvia l''app come amministratore.'
    'Reason.DataPathFailed'        = 'La connessione è attiva, ma il traffico non passa.'
    'Reason.DohServerUnresolved'   = 'Il nome del server DNS over HTTPS non è stato ancora risolto: l''app continua a provare e fino ad allora lascia l''adattatore di rete come l''ha impostato il modem.'
    'Reason.DohNeedsServers'       = 'Il DNS cifrato richiede server DNS scelti da te: quelli dell''operatore non supportano DNS over HTTPS. Fino ad allora l''adattatore di rete non viene configurato.'
    'Reason.DohUnavailable'        = 'Questa versione di Windows non può cifrare il DNS su un singolo adattatore - DNS over HTTPS richiede Windows 11: disattiva il DNS cifrato. Fino ad allora l''adattatore di rete non viene configurato.'
    'Reason.DohTemplateMissing'    = 'Windows non conosce un modello DNS over HTTPS per uno dei server DNS delle impostazioni: indicane uno, oppure scegli server che conosce. Fino ad allora l''adattatore di rete non viene configurato.'
    'Reason.Connected'             = 'Connesso.'
    'Reason.Other'                 = 'Non registrato sulla rete ({0}).'
    'Reason.Working'               = 'Operazioni sulla connessione in corso.'
    'Reason.NoNetworkForMode'      = 'Nessuna rete trovata con {0}. Nessun reset ne trova una: scegli una modalità di rete più ampia.'
    'Reason.NoNetworkForModeBands' = 'Nessuna rete trovata con {0} sulle bande LTE scelte. Nessun reset ne trova una: scegli una modalità di rete più ampia.'
    'Reason.Withheld'              = 'L''app osserva soltanto, quindi non esegue il passo successivo: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Apertura della porta AT del modem.'
    'Action.Initialize'              = 'In attesa della risposta del modem.'
    'Action.EnterPin'                = 'Inserimento del PIN memorizzato.'
    'Action.RadioOn'                 = 'Accensione della radio.'
    'Action.AutoRegister'            = 'Selezione automatica della rete.'
    'Action.DefineContext'           = 'Configurazione della connessione dati.'
    'Action.ActivateContext'         = 'Configurazione della connessione dati.'
    'Action.DeactivateContext'       = 'Configurazione della connessione dati.'
    'Action.ConfigureAdapter'        = 'Configurazione dell''adattatore di rete.'
    'Action.ApplyNetworkMode'        = 'Impostazione della modalità di rete.'
    'ActionInline.OpenPort'          = 'apertura della porta AT del modem.'
    'ActionInline.Initialize'        = 'in attesa della risposta del modem.'
    'ActionInline.EnterPin'          = 'inserimento del PIN memorizzato.'
    'ActionInline.RadioOn'           = 'accensione della radio.'
    'ActionInline.AutoRegister'      = 'selezione automatica della rete.'
    'ActionInline.DefineContext'     = 'configurazione della connessione dati.'
    'ActionInline.ActivateContext'   = 'configurazione della connessione dati.'
    'ActionInline.DeactivateContext' = 'configurazione della connessione dati.'
    'ActionInline.ConfigureAdapter'  = 'configurazione dell''adattatore di rete.'
    'ActionInline.ApplyNetworkMode'  = 'impostazione della modalità di rete.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Solo 4G'
    'Mode.NrOnly'                  = 'Solo 5G (SA)'
    'Mode.NotManaged'              = 'Come impostata nel modem'
    'Mode.Other'                   = 'modalità {0}'
    'ModeProblem.NotKept'          = 'Il modem non mantiene la modalità di rete così come è stata scritta; l''app non la riscrive.'
    'ModeProblem.NoSupportedBand'  = 'Il modem non supporta nessuna delle bande scelte per una delle sue RAT.'
    'ModeProblem.ModeUnsupported'  = 'Il modem non supporta questa modalità di rete.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Verifica della connessione in corso.'
    'Result.SaveSettings.Done'              = 'Impostazioni salvate.'
    'Result.SaveSimPin.Done'                = 'PIN memorizzato: l''app lo inserisce una volta quando la SIM lo richiede.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Impossibile identificare la SIM: il PIN non è stato memorizzato.'
    'Result.ForgetSimPin.Done'              = 'Il PIN memorizzato è stato eliminato.'
    'Result.DisableSimPin.Disabled'         = 'La SIM non richiede più il PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'La richiesta del PIN della SIM era già disattivata.'
    'Result.DisableSimPin.PinRejected'      = 'PIN errato: la SIM lo richiede ancora.'
    'Result.DisableSimPin.LastAttempt'      = 'Resta un solo tentativo per il PIN: non è stato inviato nulla.'
    'Result.DisableSimPin.SimNotReady'      = 'La SIM non è pronta: non è stato inviato nulla.'
    'Result.DisableSimPin.Failed'           = 'Impossibile modificare la richiesta del PIN della SIM.'
    'Result.UnlockFcc.Restarted'            = 'Sblocco inviato: il modem si sta riavviando.'
    'Result.UnlockFcc.NotLocked'            = 'Il modem non è bloccato: non è stato scritto nulla.'
    'Result.UnlockFcc.Unknown'              = 'Impossibile leggere il blocco: non è stato scritto nulla.'
    'Result.UnlockFcc.Failed'               = 'Lo sblocco si è interrotto prima del riavvio.'
    'Result.UnlockFcc.PortLost'             = 'Il modem si è disconnesso da USB durante lo sblocco.'
    'Result.EnableAdapter.Done'             = 'Adattatore di rete abilitato.'
    'Result.SetNetworkMode.Applied'         = 'Modalità di rete inviata: il modem si sta registrando di nuovo. Viene mantenuta quando il modem trova una rete con questa modalità.'
    'Result.SetNetworkMode.Unchanged'       = 'Il modem ha già questa modalità di rete: viene mantenuta.'
    'Result.SetNetworkMode.Done'            = 'L''app non gestisce più la modalità di rete: il modem mantiene quella che ha.'
    'Result.SetNetworkMode.ModeUnsupported' = 'Il modem non supporta questa modalità di rete: non è stato scritto nulla.'
    'Result.SetNetworkMode.NoSupportedBand' = 'Il modem non supporta nessuna delle bande scelte per una delle sue RAT: non è stato scritto nulla.'
    'Result.SetNetworkMode.Unknown'         = 'Impossibile leggere la modalità di rete del modem: non è stato scritto nulla.'
    'Result.CheckDriverPackage.Verified'    = 'Pacchetto del driver verificato: una versione che l''app conosce.'
    'Result.CheckDriverPackage.Signed'      = 'Pacchetto del driver verificato: firmato da Microsoft, una versione che l''app non conosce.'
    'Result.CheckDriverPackage.Refused'     = 'Impossibile installare il pacchetto del driver: la scheda Driver spiega il motivo.'
    'Result.CheckDriverPackage.NoPackage'   = 'Nessun pacchetto del driver scelto.'
    'Result.CheckDriverPackage.Failed'      = 'Impossibile leggere il pacchetto del driver.'
    'Result.InstallDriver.Done'             = 'Driver installato: l''app apre la porta AT del modem non appena Windows la avvia.'
    'Result.InstallDriver.RestartNeeded'    = 'Driver installato: per completare, Windows deve essere riavviato.'
    'Result.InstallDriver.NoDevice'         = 'Driver aggiunto a Windows, ma nessun dispositivo lo usa: viene usato quando il modem viene collegato, a meno che Windows non dia la precedenza a un altro driver.'
    'Result.InstallDriver.Unconfirmed'      = 'Non installato: una versione che l''app non conosce richiede la tua conferma.'
    'Result.InstallDriver.NoPackage'        = 'Scegli prima un pacchetto del driver.'
    'Result.InstallDriver.DriverWorking'    = 'La porta AT ha già un driver funzionante: non è stato installato nulla.'
    'Result.InstallDriver.TimedOut'         = 'Windows non ha completato in tempo l''installazione del driver: è stata interrotta.'
    'Result.InstallDriver.Failed'           = 'Windows non ha installato il driver.'
    'Result.UninstallDriver.Done'           = 'Driver disinstallato: l''app non può comunicare con il modem finché non viene installato di nuovo.'
    'Result.UninstallDriver.RestartNeeded'  = 'Driver disinstallato: per completare, Windows deve essere riavviato.'
    'Result.UninstallDriver.NoDriver'       = 'La porta AT non ha un driver che l''app possa disinstallare.'
    'Result.UninstallDriver.TrialOn'        = 'Non disinstallato: una modalità di rete è in prova, e solo tramite la porta AT si può riscrivere quella precedente.'
    'Result.UninstallDriver.TimedOut'       = 'Windows non ha completato in tempo la disinstallazione del driver: è stata interrotta.'
    'Result.UninstallDriver.Failed'         = 'Windows non ha disinstallato il driver.'
    'Result.NotElevated'                    = 'Questa operazione richiede i diritti di amministratore.'
    'Result.Refused'                        = 'Non disponibile mentre l''app osserva soltanto.'
    'Result.NoModem'                        = 'Il modem non è collegato.'
    'Result.PortLost'                       = 'Il modem si è disconnesso da USB durante il comando.'
    'Result.Failed'                         = 'Operazione non riuscita.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Tentativi rimasti: {0}.'
    'Result.Restarting'                     = 'Il monitoraggio si sta riavviando: riprova tra poco.'

    # The headline.
    'Tone.Online'         = 'Online'
    'Tone.Working'        = 'In connessione'
    'Tone.Recovering'     = 'In ripristino'
    'Tone.Attention'      = 'Azione richiesta'
    'Tone.Offline'        = 'Nessun modem'
    'Tone.Stopped'        = 'Monitoraggio fermo'
    'Title.ConnectionLost' = 'Connessione persa'
    'Title.NoNetwork'     = 'Nessuna rete'
    'Title.NotConnected'  = 'Non connesso'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'Il modem non è collegato via USB.'
    'Check.H2'          = 'Il modem non risponde.'
    'Check.H3'          = 'La SIM non è pronta.'
    'Check.H4'          = 'Non registrato sulla rete.'
    'Check.H5'          = 'La connessione dati non è attiva.'
    'Check.H6'          = 'L''adattatore di rete non è configurato.'
    'Check.H7'          = 'Il traffico non passa.'
    'Check.Other'       = 'La connessione non è attiva.'
    'Step.R1'           = 'Nuova configurazione dell''adattatore di rete.'
    'Step.R2'           = 'Riavvio della connessione dati.'
    'Step.R3'           = 'Nuova registrazione sulla rete.'
    'Step.R4'           = 'Spegnimento e riaccensione della radio.'
    'Step.R5'           = 'Riavvio del modem.'
    'Step.R6'           = 'Riavvio del dispositivo USB del modem.'
    'StepInline.R1'     = 'nuova configurazione dell''adattatore di rete.'
    'StepInline.R2'     = 'riavvio della connessione dati.'
    'StepInline.R3'     = 'nuova registrazione sulla rete.'
    'StepInline.R4'     = 'spegnimento e riaccensione della radio.'
    'StepInline.R5'     = 'riavvio del modem.'
    'StepInline.R6'     = 'riavvio del dispositivo USB del modem.'
    'Recovery.Waiting'  = '{0} I passi di ripristino non sono serviti: ripartono alle {1}.'
    'Recovery.Slow'     = '{0} Il ripristino non è riuscito {1} volte: l''app riprova alle {2}.'
    'Recovery.Withheld' = '{0} L''app osserva soltanto, quindi non esegue il passo di ripristino: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Apri'
    'Tray.CheckNow'       = 'Verifica ora'
    'Tray.NetworkMode'    = 'Modalità di rete'
    'Tray.NetworkModeNow' = 'Modalità di rete: {0}'
    'Tray.Exit'           = 'Esci'
    'Tray.Update'         = 'È disponibile la versione {0}...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Usa {0}, tutte le bande'
    'Blocker.SaveApn'       = 'Salva APN'
    'Blocker.SavePassword'  = 'Salva password'
    'Blocker.StorePin'      = 'Memorizza PIN'
    'Blocker.EnableAdapter' = 'Abilita adattatore'
    'Blocker.Unlock'        = 'Sblocca...'
    'Blocker.InstallDriver' = 'Installa il driver...'
    'Blocker.OpenSettings'  = 'Apri le impostazioni'
    'Blocker.ObserveOnly'   = 'L''app osserva soltanto: non modifica nulla.'
    'Blocker.NeedsAdmin'    = 'Per abilitarlo servono i diritti di amministratore.'
    'Blocker.UnlockNote'    = 'Lo sblocco scrive nella memoria non volatile del modem: l''app chiede conferma prima di farlo.'
    'Blocker.AttemptsLeft'  = 'Tentativi rimasti: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Pronta'
    'Sim.PinRequired'    = 'In attesa del PIN'
    'Sim.PukRequired'    = 'Bloccata: richiede il PUK'
    'Sim.Absent'         = 'Nessuna SIM'
    'Sim.Busy'           = 'Occupata'
    'Sim.Failure'        = 'Non funzionante'
    'Sim.Other'          = 'In attesa di un altro codice'
    'Sim.Unknown'        = 'Stato sconosciuto'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - tentativi PIN rimasti: {1}'
    'Sim.RequestOn'      = 'Richiesta del PIN all''accensione: attiva'
    'Sim.RequestOff'     = 'Richiesta del PIN all''accensione: disattivata'
    'Sim.RequestUnknown' = 'Richiesta del PIN all''accensione: sconosciuta'
    'Sim.Stored'         = 'Per questa SIM è memorizzato un PIN.'
    'Sim.NotStored'      = 'Nessun PIN memorizzato.'
    'Sim.Rejected'       = 'Il PIN memorizzato è stato rifiutato ed eliminato: l''app non lo riprova mai più.'

    # The network tab.
    'Bands.Every'       = 'tutte le bande'
    'Bands.EveryBut'    = 'tutte le bande tranne {0}'
    'Bands.None'        = 'nessuna'
    'Network.Current'   = 'Impostazione attuale del modem: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'La modalità di rete del modem non è stata ancora letta.'
    'Network.Trial'     = 'Prova in corso con {0}: se entro le {1} il modem non trova una rete con questa modalità, torna a quella precedente.'
    'Network.Reverted'  = 'Alle {0} il modem non aveva trovato una rete con {1}: è tornato alla modalità precedente.'
    'Network.Kept'      = 'Alle {0} il modem si è registrato con {1}: la modalità viene mantenuta.'
    'Network.Missing'   = 'Il modem esclude {0} nonostante la richiesta: usa le altre bande scelte.'
    'Network.ChooseBand' = 'Scegli almeno una banda {0}, oppure tutte le bande.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Il DNS cifrato non è disponibile in questa versione di Windows: DNS over HTTPS su un singolo adattatore richiede Windows 11.'
    'Dns.On'                   = 'Il DNS cifrato è attivo: {0}.'
    'Dns.Waiting'              = 'Il DNS cifrato attende l''indirizzo del suo server: nel frattempo non è impostato alcun server DNS.'
    'Dns.Off'                  = 'Il DNS cifrato è disattivato.'
    'Dns.Advertised'           = 'La rete fornisce anche server DNS IPv6 ({0}), che Windows potrebbe usare in chiaro.'
    'Dns.LookupFailed'         = 'Impossibile risolvere {0}; l''app continua a provare.'
    'Dns.LookingUp'            = 'Risoluzione di {0}...'
    'Dns.LookedUp'             = 'Il nome del server, {0}, è stato risolto alle {1}.'
    'Dns.LookedUpNext'         = 'Il nome del server, {0}, è stato risolto alle {1}; nuova risoluzione alle {2}.'
    'Dns.LookedUpOperator'     = 'Il nome del server, {0}, è stato risolto alle {1} tramite i DNS dell''operatore, in chiaro.'
    'Dns.LookedUpOperatorNext' = 'Il nome del server, {0}, è stato risolto alle {1} tramite i DNS dell''operatore, in chiaro; nuova risoluzione alle {2}.'
    'Dns.NotAvailableHere'     = 'Il DNS cifrato non è disponibile in questa versione di Windows.'
    'Dns.NoTemplate'           = 'Windows non conosce un modello DNS over HTTPS per {0}: indicane uno.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; viene usato il valore predefinito.'
    'Setting.Unknown'          = 'L''impostazione sconosciuta ''{0}'' viene ignorata.'
    'Setting.Unreadable'       = 'Impossibile leggere il file delle impostazioni; vengono usati i valori predefiniti.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps richiede DnsServers, oppure un DohTemplate che indichi il server: i server dell''operatore non supportano DoH, e finché non ce n''è uno non viene impostato alcun server DNS.'
    'Setting.TemplateAddress'  = 'DohTemplate indica l''indirizzo {0}, quindi può valere solo per quel server; viene usato il valore predefinito.'
    'Rule.Text'                = 'deve essere testo ASCII stampabile, senza virgolette doppie né spazi iniziali o finali'
    'Rule.TextQuotes'          = 'deve essere testo ASCII stampabile, senza virgolette doppie'
    'Rule.OneOf'               = 'deve essere uno dei valori {0}'
    'Rule.EmptyOrOneOf'        = 'deve essere vuoto o uno dei valori {0}'
    'Rule.Addresses'           = 'deve essere un elenco di indirizzi IP'
    'Rule.Number'              = 'deve essere un numero intero da {0} a {1}'
    'Rule.Minutes'             = 'deve essere un numero intero di minuti da {0} a {1}'
    'Rule.Bool'                = 'deve essere true o false'
    'Rule.Https'               = 'deve essere vuoto o un indirizzo https senza spazi, virgolette o credenziali'
    'Rule.Bands'               = 'deve essere un elenco di numeri di banda distinti da {0} a {1}'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'non contiene alcun driver (nessun file INF)'
    'DriverProblem.NotForModem'  = 'nessuno dei suoi driver è destinato alla porta AT di questo modem'
    'DriverProblem.NoCatalog'    = 'il suo driver non ha un catalogo di firma'
    'DriverProblem.NotWhql'      = 'il suo catalogo non è firmato da Microsoft (WHQL)'
    'DriverProblem.NotInCatalog' = 'il suo file INF non è quello garantito dal suo catalogo: è stato modificato o è danneggiato'
    'DriverProblem.NotTrusted'   = 'la sua firma non può essere verificata'
    'Driver.Present'             = 'La porta AT del modem ha il suo driver.'
    'Driver.PresentWhat'         = 'La porta AT del modem ha il suo driver: {0}.'
    'Driver.NoDriver'            = 'La porta AT del modem non ha un driver: l''app non può comunicare con il modem.'
    'Driver.Problem'             = 'Windows segnala un problema con la porta AT del modem: reinstallarne il driver potrebbe risolverlo.'
    'Driver.Absent'              = 'Nessun modem su USB. Un driver installato ora viene usato non appena il modem viene collegato.'
    'Driver.NotLooked'           = 'La porta AT del modem non è stata ancora esaminata.'
    'Driver.Source'              = 'L''app non include il driver del modem: non ha la licenza per ridistribuirlo. Scaricane una copia, poi sceglila qui: l''app verifica che Microsoft l''abbia firmata (WHQL) per questo modem e non esegue mai programmi in essa contenuti.'
    'Driver.SourceCopy'          = 'L''app non include il driver del modem: non ha la licenza per ridistribuirlo. Una copia del driver di MediaTek, {0}, è pubblicata da terzi, {1}, come {2}. Scaricala, poi sceglila qui: l''app verifica che Microsoft l''abbia firmata (WHQL) per questo modem e non esegue mai programmi in essa contenuti.'
    'Driver.Checking'            = 'Verifica del pacchetto del driver...'
    'Driver.Installing'          = 'Installazione del driver: Windows potrebbe impiegare un minuto.'
    'Driver.Uninstalling'        = 'Disinstallazione del driver...'
    'Driver.Verified'            = '{0}: {1}, una versione che l''app conosce, firmata da Microsoft (WHQL) per questo modem.'
    'Driver.Signed'              = '{0}: {1}, firmato da Microsoft (WHQL) per questo modem, ma non è una versione che l''app conosce: l''app chiede conferma prima di installarlo.'
    'Driver.Refused'             = 'Impossibile installare {0}: {1}.'
    'Driver.ObserveOnly'         = 'L''app osserva soltanto: non modifica nulla.'
    'Driver.NeedsAdmin'          = 'Per installare o disinstallare un driver servono i diritti di amministratore: avvia l''app come amministratore.'
    'Driver.Trial'               = 'Una modalità di rete è in prova: il driver si potrà disinstallare al termine della prova.'
    'Driver.Install'             = 'Installa'
    'Driver.InstallConfirm'      = 'Installa...'
    'Driver.ChooseTitle'         = 'Scegli il pacchetto del driver scaricato'
    'Driver.FileKind'            = 'Pacchetto del driver'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'Il monitoraggio si è fermato e si sta riavviando. La connessione non viene toccata.'
    'Window.NotResponding'   = 'Il monitoraggio non risponde. La connessione non viene toccata.'
    'Window.Starting'        = 'Avvio in corso.'
    'Window.Simulated'       = 'Modalità di sviluppo: un modem simulato (scenario {0}).'
    'Window.ObserveOnly'     = 'L''app osserva soltanto: non modifica nulla sul modem o sul sistema.'
    'Window.SettingsPending' = 'La connessione dati è attiva con altre impostazioni: le nuove si applicano alla prossima connessione.'
    'Window.SettingsFile'    = 'File delle impostazioni: {0}'
    'Window.Modems'          = 'Trovati {0} modem: l''app usa quello su {1}.'
    'Window.Recovered'       = 'Ripristino riuscito alle {0}: {1}'
    'Window.NrAvailable'     = '{0}, 5G disponibile'
    'Window.NothingMeasured' = 'Nessun valore misurato.'
    'Window.PasswordStored'  = 'È memorizzata una password.'
    'Window.NoPassword'      = 'Nessuna password memorizzata.'
    'Window.PinFirst'        = 'Digita prima il PIN della SIM: per rimuoverlo serve il PIN.'
    'Cell.Serving'           = 'Servente'
    'Cell.Neighbour'         = 'Adiacente'
    'Carrier.Primary'        = 'Primaria'
    'Carrier.Active'         = 'Attiva'
    'Carrier.Inactive'       = 'Inattiva'
    'Footer.Port'            = 'Porta AT {0}'
    'Footer.PortClosed'      = 'Porta AT chiusa'
    'Footer.Updated'         = 'aggiornato alle {0}'
    'Footer.PathChecked'     = 'percorso dati verificato alle {0}'
    'Footer.PathFailed'      = 'percorso dati non funzionante alle {0}'
    'Footer.PathPending'     = 'percorso dati non ancora verificato alle {0}'
    'Footer.NotElevated'     = 'senza diritti di amministratore'
    'Footer.Version'         = 'versione {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Sblocca il modem'
    'Confirm.Unlock'               = @'
Sbloccare il modem?

Questa operazione scrive nella memoria non volatile del modem e rimuove una restrizione che il produttore del portatile ha impostato per la certificazione radio. Viene eseguita sotto la tua responsabilità e potrebbe non funzionare su tutti i moduli.

Al termine il modem si riavvia.
'@
    'Confirm.DisablePinTitle'      = 'Rimuovi il PIN dalla SIM'
    'Confirm.DisablePin'           = @'
Rimuovere il PIN dalla SIM?

Questa operazione modifica la scheda SIM, non l'app: la SIM non chiederà più il PIN, né in questo modem né in alcun telefono. Un PIN errato consuma uno dei tentativi.
'@
    'Confirm.UnknownDriverTitle'   = 'Installa una versione sconosciuta del driver'
    'Confirm.UnknownDriver'        = @'
Installare una versione del driver che l'app non conosce?

Microsoft ha firmato questo pacchetto (WHQL) per la porta AT del modem, quindi Windows lo accetta; ma non è una versione che l'app conosce.

Windows lo installa per ogni dispositivo compatibile.
'@
    'Confirm.UninstallDriverTitle' = 'Disinstalla il driver'
    'Confirm.UninstallDriver'      = @'
Disinstallare il driver della porta AT del modem?

Windows lo rimuove dalle porte seriali del modem e dal proprio archivio driver. La connessione dati resta attiva, ma l'app non può comunicare con il modem, né controllare la connessione, finché il driver non viene installato di nuovo.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Verifica ora'
    'Xaml.SignalTab'         = 'Segnale'
    'Xaml.Cells'             = 'Celle'
    'Xaml.Cell'              = 'Cella'
    'Xaml.Band'              = 'Banda'
    'Xaml.Channel'           = 'Canale'
    'Xaml.Bandwidth'         = 'Larghezza di banda'
    'Xaml.CarrierAggregation' = 'Aggregazione di portanti'
    'Xaml.Carrier'           = 'Portante'
    'Xaml.State'             = 'Stato'
    'Xaml.BandwidthDlUl'     = 'Larghezza di banda DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulazione DL/UL'
    'Xaml.StorePin'          = 'Memorizza PIN'
    'Xaml.ForgetPin'         = 'Dimentica il PIN memorizzato'
    'Xaml.DisablePin'        = 'Rimuovi il PIN dalla SIM...'
    'Xaml.PinNote'           = 'Un PIN memorizzato viene conservato cifrato per il tuo utente Windows, associato alla SIM a cui appartiene. L''app lo inserisce una volta quando quella SIM lo richiede - mai due volte, mai con un solo tentativo rimasto, e mai un PUK.'
    'Xaml.NetworkTab'        = 'Rete'
    'Xaml.NetworkMode'       = 'Modalità di rete'
    'Xaml.Apply'             = 'Applica'
    'Xaml.Undo'              = 'Annulla modifiche'
    'Xaml.ModeNote'          = 'Il modem mantiene la modalità di rete e le bande anche dopo la chiusura dell''app. Una modalità viene prima provata: se il modem non trova una rete con essa, torna a quella precedente.'
    'Xaml.LteAll'            = 'LTE: tutte le bande'
    'Xaml.NrAll'             = 'NR: tutte le bande'
    'Xaml.ConnectionTab'     = 'Connessione'
    'Xaml.ApnTip'            = 'Vuoto: quello del tuo abbonamento.'
    'Xaml.PdpType'           = 'Tipo PDP'
    'Xaml.Authentication'    = 'Autenticazione'
    'Xaml.AuthNone'          = 'Nessuna'
    'Xaml.User'              = 'Utente'
    'Xaml.Password'          = 'Password'
    'Xaml.ClearPassword'     = 'Elimina la password memorizzata'
    'Xaml.DnsServers'        = 'Server DNS'
    'Xaml.DnsTip'            = 'Separati da virgole. Vuoto: quelli dell''operatore.'
    'Xaml.EncryptedDns'      = 'DNS cifrato'
    'Xaml.Doh'               = 'DNS over HTTPS verso i server indicati sopra, o verso quello del modello - mai in chiaro'
    'Xaml.DohTemplate'       = 'Modello DoH'
    'Xaml.DohTemplateTip'    = 'Vuoto: il modello che Windows conosce per ciascun server. Altrimenti un indirizzo https per tutti; senza server DNS, il suo nome o indirizzo è il server.'
    'Xaml.RefreshBefore'     = 'Risolvi il nome del server ogni'
    'Xaml.RefreshAfter'      = 'minuti, se non è indicato alcun server DNS: il nome nel modello è il server.'
    'Xaml.Metric'            = 'Metrica dell''interfaccia'
    'Xaml.MetricNote'        = '500 mantiene il modem come connessione di riserva; un valore basso lo rende quella preferita.'
    'Xaml.Updates'           = 'Aggiornamenti'
    'Xaml.UpdateCheck'       = 'Cerca una nuova versione una volta a ogni avvio'
    'Xaml.Save'              = 'Salva'
    'Xaml.DriverTab'         = 'Driver'
    'Xaml.OpenPage'          = 'Apri la pagina di download'
    'Xaml.ChoosePackage'     = 'Scegli il pacchetto scaricato...'
    'Xaml.Install'           = 'Installa'
    'Xaml.UninstallDriver'   = 'Disinstalla il driver...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Avvio'
    'Xaml.StartAtLogon'               = 'Avvia l''app nell''area di notifica all''accesso a Windows'
    'Startup.NotInstalled'            = 'Solo l''app installata può avviarsi all''accesso a Windows.'
    'Startup.NeedsAdmin'              = 'Per cambiarlo servono i diritti di amministratore.'
    'Startup.ObserveOnly'             = 'L''app osserva soltanto: non modifica nulla.'
    'Result.SetStartAtLogon.Enabled'  = 'Ora l''app si avvia all''accesso a Windows.'
    'Result.SetStartAtLogon.Disabled' = 'L''app non si avvia più all''accesso a Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Solo l''app installata può avviarsi all''accesso a Windows: non è stato modificato nulla.'
}
