# The app's texts in Dutch: every key of the English table, with the same placeholders. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Geen modem gevonden op USB.'
    'Reason.NoDriver'              = 'De AT-poort van de modem heeft geen stuurprogramma: de app kan pas met de modem communiceren als het is geïnstalleerd.'
    'Reason.DeviceProblem'         = 'Windows meldt een probleem met de AT-poort van de modem.'
    'Reason.PortInUse'             = 'Een ander programma gebruikt de AT-poort van de modem.'
    'Reason.PortFailed'            = 'De AT-poort van de modem kan niet worden geopend.'
    'Reason.SimUnknown'            = 'De SIM wordt gelezen.'
    'Reason.NoPin'                 = 'De SIM wacht op de PIN.'
    'Reason.PinForOtherSim'        = 'De opgeslagen PIN hoort bij een andere SIM: voer de PIN van deze SIM in.'
    'Reason.SimNotIdentified'      = 'De SIM kan niet worden geïdentificeerd, dus de opgeslagen PIN wordt er niet naartoe gestuurd.'
    'Reason.PinUnconfirmed'        = 'De laatste PIN-invoer kreeg geen antwoord, en de app probeert het nooit twee keer: voer de PIN opnieuw in.'
    'Reason.LastAttempt'           = 'Er is nog maar één PIN-poging over, en de app gebruikt die niet: ontgrendel de SIM in een telefoon.'
    'Reason.PukRequired'           = 'De SIM is geblokkeerd en heeft de PUK nodig: deblokkeer de SIM in een telefoon. De app voert nooit een PUK in.'
    'Reason.NoSim'                 = 'Geen SIM in de modem.'
    'Reason.SimFailure'            = 'De SIM werkt niet.'
    'Reason.SimOther'              = 'De SIM wacht op een code die de app niet afhandelt.'
    'Reason.SimBusy'               = 'De SIM is bezet; er wordt gewacht.'
    'Reason.FccLocked'             = 'De modem is vergrendeld door de fabrikant van de laptop (FCC-vergrendeling): de radio blijft uit.'
    'Reason.NotRegistered'         = 'Niet geregistreerd op een netwerk.'
    'Reason.NotSearching'          = 'Niet geregistreerd, en er wordt niet naar een netwerk gezocht.'
    'Reason.Searching'             = 'Zoeken naar een netwerk.'
    'Reason.Denied'                = 'Het netwerk heeft de registratie geweigerd.'
    'Reason.Unknown'               = 'Niet geregistreerd; de reden is onbekend.'
    'Reason.EmergencyOnly'         = 'Alleen noodoproepen.'
    'Reason.ContextUnknown'        = 'De gegevensverbinding wordt gelezen.'
    'Reason.ApnPasswordUnreadable' = 'Het opgeslagen APN-wachtwoord kan niet worden gelezen: voer het opnieuw in.'
    'Reason.ApnNeeded'             = 'Het netwerk gaf geen internettoegang met een lege APN: voer de APN van je provider in.'
    'Reason.NoAddress'             = 'De gegevensverbinding heeft geen IPv4-adres.'
    'Reason.AdapterDisabled'       = 'De netwerkadapter van de modem is uitgeschakeld.'
    'Reason.NoAdapter'             = 'De netwerkadapter van de modem ontbreekt.'
    'Reason.NotElevated'           = 'De netwerkadapter kan alleen met administratorrechten worden geconfigureerd: start de app als administrator.'
    'Reason.DataPathFailed'        = 'De verbinding is actief, maar er komt geen verkeer door.'
    'Reason.DohServerUnresolved'   = 'De naam van de DNS-over-HTTPS-server is nog niet opgezocht: de app blijft het proberen en laat de netwerkadapter tot die tijd zoals de modem hem heeft ingesteld.'
    'Reason.DohNeedsServers'       = 'Versleutelde DNS heeft DNS-servers van je eigen keuze nodig: die van de provider ondersteunen geen DNS over HTTPS. De netwerkadapter wordt tot dan niet geconfigureerd.'
    'Reason.DohUnavailable'        = 'Deze versie van Windows kan DNS niet op één adapter versleutelen - DNS over HTTPS vereist Windows 11: schakel versleutelde DNS uit. De netwerkadapter wordt tot dan niet geconfigureerd.'
    'Reason.DohTemplateMissing'    = 'Windows kent geen DNS-over-HTTPS-sjabloon voor een DNS-server uit de instellingen: geef er een op, of kies servers die Windows kent. De netwerkadapter wordt tot dan niet geconfigureerd.'
    'Reason.Connected'             = 'Verbonden.'
    'Reason.Other'                 = 'Niet geregistreerd ({0}).'
    'Reason.Working'               = 'Bezig met de verbinding.'
    'Reason.NoNetworkForMode'      = 'Geen netwerk gevonden met {0}. Geen enkele reset vindt er een: kies een ruimere netwerkmodus.'
    'Reason.NoNetworkForModeBands' = 'Geen netwerk gevonden met {0} op de gekozen LTE-banden. Geen enkele reset vindt er een: kies een ruimere netwerkmodus.'
    'Reason.Withheld'              = 'De app observeert alleen en voert de volgende stap dus niet uit: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'De AT-poort van de modem openen.'
    'Action.Initialize'              = 'Wachten tot de modem antwoordt.'
    'Action.EnterPin'                = 'De opgeslagen PIN invoeren.'
    'Action.RadioOn'                 = 'De radio inschakelen.'
    'Action.AutoRegister'            = 'Het netwerk automatisch selecteren.'
    'Action.DefineContext'           = 'De gegevensverbinding instellen.'
    'Action.ActivateContext'         = 'De gegevensverbinding instellen.'
    'Action.DeactivateContext'       = 'De gegevensverbinding instellen.'
    'Action.ConfigureAdapter'        = 'De netwerkadapter configureren.'
    'Action.ApplyNetworkMode'        = 'De netwerkmodus instellen.'
    'ActionInline.OpenPort'          = 'de AT-poort van de modem openen.'
    'ActionInline.Initialize'        = 'wachten tot de modem antwoordt.'
    'ActionInline.EnterPin'          = 'de opgeslagen PIN invoeren.'
    'ActionInline.RadioOn'           = 'de radio inschakelen.'
    'ActionInline.AutoRegister'      = 'het netwerk automatisch selecteren.'
    'ActionInline.DefineContext'     = 'de gegevensverbinding instellen.'
    'ActionInline.ActivateContext'   = 'de gegevensverbinding instellen.'
    'ActionInline.DeactivateContext' = 'de gegevensverbinding instellen.'
    'ActionInline.ConfigureAdapter'  = 'de netwerkadapter configureren.'
    'ActionInline.ApplyNetworkMode'  = 'de netwerkmodus instellen.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Alleen 4G'
    'Mode.NrOnly'                  = 'Alleen 5G (SA)'
    'Mode.NotManaged'              = 'Zoals ingesteld in de modem'
    'Mode.Other'                   = 'modus {0}'
    'ModeProblem.NotKept'          = 'De modem behoudt de netwerkmodus niet zoals die is geschreven; de app schrijft hem niet opnieuw.'
    'ModeProblem.NoSupportedBand'  = 'De modem ondersteunt geen van de banden die voor een van zijn RAT''s zijn gekozen.'
    'ModeProblem.ModeUnsupported'  = 'De modem ondersteunt deze netwerkmodus niet.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'De verbinding wordt nu gecontroleerd.'
    'Result.SaveSettings.Done'              = 'Instellingen opgeslagen.'
    'Result.SaveSimPin.Done'                = 'PIN opgeslagen: de app voert hem één keer in wanneer de SIM erom vraagt.'
    'Result.SaveSimPin.SimNotIdentified'    = 'De SIM kan niet worden geïdentificeerd: de PIN is niet opgeslagen.'
    'Result.ForgetSimPin.Done'              = 'De opgeslagen PIN is verwijderd.'
    'Result.DisableSimPin.Disabled'         = 'De SIM vraagt niet meer om de PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'Het PIN-verzoek van de SIM stond al uit.'
    'Result.DisableSimPin.PinRejected'      = 'Onjuiste PIN: de SIM vraagt er nog steeds om.'
    'Result.DisableSimPin.LastAttempt'      = 'Er is nog maar één PIN-poging over: er is niets verzonden.'
    'Result.DisableSimPin.SimNotReady'      = 'De SIM is niet gereed: er is niets verzonden.'
    'Result.DisableSimPin.Failed'           = 'Het PIN-verzoek van de SIM kon niet worden gewijzigd.'
    'Result.UnlockFcc.Restarted'            = 'Ontgrendeling verzonden: de modem wordt opnieuw opgestart.'
    'Result.UnlockFcc.NotLocked'            = 'De modem is niet vergrendeld: er is niets geschreven.'
    'Result.UnlockFcc.Unknown'              = 'De vergrendeling kan niet worden gelezen: er is niets geschreven.'
    'Result.UnlockFcc.Failed'               = 'De ontgrendeling is gestopt vóór het opnieuw opstarten.'
    'Result.UnlockFcc.PortLost'             = 'De modem is tijdens de ontgrendeling van USB verdwenen.'
    'Result.EnableAdapter.Done'             = 'Netwerkadapter ingeschakeld.'
    'Result.SetNetworkMode.Applied'         = 'Netwerkmodus verzonden: de modem registreert zich opnieuw. De modus blijft behouden zodra de modem er een netwerk mee vindt.'
    'Result.SetNetworkMode.Unchanged'       = 'De modem heeft deze netwerkmodus al: die blijft behouden.'
    'Result.SetNetworkMode.Done'            = 'De app beheert de netwerkmodus niet meer: de modem houdt de modus die hij heeft.'
    'Result.SetNetworkMode.ModeUnsupported' = 'De modem ondersteunt deze netwerkmodus niet: er is niets geschreven.'
    'Result.SetNetworkMode.NoSupportedBand' = 'De modem ondersteunt geen van de banden die voor een van zijn RAT''s zijn gekozen: er is niets geschreven.'
    'Result.SetNetworkMode.Unknown'         = 'De netwerkmodus van de modem kan niet worden gelezen: er is niets geschreven.'
    'Result.CheckDriverPackage.Verified'    = 'Stuurprogrammapakket gecontroleerd: een versie die de app kent.'
    'Result.CheckDriverPackage.Signed'      = 'Stuurprogrammapakket gecontroleerd: ondertekend door Microsoft, een versie die de app niet kent.'
    'Result.CheckDriverPackage.Refused'     = 'Het stuurprogrammapakket kan niet worden geïnstalleerd: op het tabblad Stuurprogramma staat waarom.'
    'Result.CheckDriverPackage.NoPackage'   = 'Er is geen stuurprogrammapakket gekozen.'
    'Result.CheckDriverPackage.Failed'      = 'Het stuurprogrammapakket kan niet worden gelezen.'
    'Result.InstallDriver.Done'             = 'Stuurprogramma geïnstalleerd: de app opent de AT-poort van de modem zodra Windows die start.'
    'Result.InstallDriver.RestartNeeded'    = 'Stuurprogramma geïnstalleerd: Windows moet opnieuw worden opgestart om te voltooien.'
    'Result.InstallDriver.NoDevice'         = 'Stuurprogramma toegevoegd aan Windows, maar geen apparaat heeft het overgenomen: het wordt gebruikt wanneer de modem wordt aangesloten, tenzij Windows een ander stuurprogramma hoger rangschikt.'
    'Result.InstallDriver.Unconfirmed'      = 'Niet geïnstalleerd: een versie die de app niet kent, heeft je bevestiging nodig.'
    'Result.InstallDriver.NoPackage'        = 'Kies eerst een stuurprogrammapakket.'
    'Result.InstallDriver.DriverWorking'    = 'De AT-poort heeft al een werkend stuurprogramma: er is niets geïnstalleerd.'
    'Result.InstallDriver.TimedOut'         = 'Windows heeft de installatie van het stuurprogramma niet op tijd voltooid: de installatie is gestopt.'
    'Result.InstallDriver.Failed'           = 'Windows heeft het stuurprogramma niet geïnstalleerd.'
    'Result.UninstallDriver.Done'           = 'Stuurprogramma verwijderd: de app kan pas weer met de modem communiceren als het opnieuw is geïnstalleerd.'
    'Result.UninstallDriver.RestartNeeded'  = 'Stuurprogramma verwijderd: Windows moet opnieuw worden opgestart om te voltooien.'
    'Result.UninstallDriver.NoDriver'       = 'De AT-poort heeft geen stuurprogramma dat de app kan verwijderen.'
    'Result.UninstallDriver.TrialOn'        = 'Niet verwijderd: er wordt een netwerkmodus uitgeprobeerd, en alleen de AT-poort kan de vorige terugzetten.'
    'Result.UninstallDriver.TimedOut'       = 'Windows heeft het verwijderen van het stuurprogramma niet op tijd voltooid: het verwijderen is gestopt.'
    'Result.UninstallDriver.Failed'         = 'Windows heeft het stuurprogramma niet verwijderd.'
    'Result.NotElevated'                    = 'Daarvoor zijn administratorrechten nodig.'
    'Result.Refused'                        = 'Niet beschikbaar zolang de app alleen observeert.'
    'Result.NoModem'                        = 'De modem is niet aangesloten.'
    'Result.PortLost'                       = 'De modem is tijdens de opdracht van USB verdwenen.'
    'Result.Failed'                         = 'Het is niet gelukt.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Resterende pogingen: {0}.'
    'Result.Restarting'                     = 'De bewaking wordt opnieuw gestart: probeer het zo nog eens.'

    # The headline.
    'Tone.Online'         = 'Online'
    'Tone.Working'        = 'Verbinden'
    'Tone.Recovering'     = 'Herstellen'
    'Tone.Attention'      = 'Actie vereist'
    'Tone.Offline'        = 'Geen modem'
    'Tone.Stopped'        = 'Geen bewaking'
    'Title.ConnectionLost' = 'Verbinding verbroken'
    'Title.NoNetwork'     = 'Geen netwerk'
    'Title.NotConnected'  = 'Niet verbonden'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'De modem is niet aanwezig op USB.'
    'Check.H2'          = 'De modem antwoordt niet.'
    'Check.H3'          = 'De SIM is niet gereed.'
    'Check.H4'          = 'Niet geregistreerd op een netwerk.'
    'Check.H5'          = 'De gegevensverbinding is niet actief.'
    'Check.H6'          = 'De netwerkadapter is niet geconfigureerd.'
    'Check.H7'          = 'Er komt geen verkeer door.'
    'Check.Other'       = 'De verbinding is niet actief.'
    'Step.R1'           = 'De netwerkadapter opnieuw configureren.'
    'Step.R2'           = 'De gegevensverbinding opnieuw starten.'
    'Step.R3'           = 'Opnieuw registreren op het netwerk.'
    'Step.R4'           = 'De radio uit- en weer inschakelen.'
    'Step.R5'           = 'De modem opnieuw opstarten.'
    'Step.R6'           = 'Het USB-apparaat van de modem opnieuw starten.'
    'StepInline.R1'     = 'de netwerkadapter opnieuw configureren.'
    'StepInline.R2'     = 'de gegevensverbinding opnieuw starten.'
    'StepInline.R3'     = 'opnieuw registreren op het netwerk.'
    'StepInline.R4'     = 'de radio uit- en weer inschakelen.'
    'StepInline.R5'     = 'de modem opnieuw opstarten.'
    'StepInline.R6'     = 'het USB-apparaat van de modem opnieuw starten.'
    'Recovery.Waiting'  = '{0} De herstelstappen hebben niet geholpen: ze beginnen opnieuw om {1}.'
    'Recovery.Slow'     = '{0} Het herstel is {1} keer mislukt: de app probeert het opnieuw om {2}.'
    'Recovery.Withheld' = '{0} De app observeert alleen en voert de herstelstap dus niet uit: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Openen'
    'Tray.CheckNow'       = 'Nu controleren'
    'Tray.NetworkMode'    = 'Netwerkmodus'
    'Tray.NetworkModeNow' = 'Netwerkmodus: {0}'
    'Tray.Exit'           = 'Afsluiten'
    'Tray.Update'         = 'Versie {0} is beschikbaar...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = '{0} gebruiken, alle banden'
    'Blocker.SaveApn'       = 'APN opslaan'
    'Blocker.SavePassword'  = 'Wachtwoord opslaan'
    'Blocker.StorePin'      = 'PIN opslaan'
    'Blocker.EnableAdapter' = 'Adapter inschakelen'
    'Blocker.Unlock'        = 'Ontgrendelen...'
    'Blocker.InstallDriver' = 'Stuurprogramma installeren...'
    'Blocker.OpenSettings'  = 'Instellingen openen'
    'Blocker.ObserveOnly'   = 'De app observeert alleen en wijzigt niets.'
    'Blocker.NeedsAdmin'    = 'Inschakelen vereist administratorrechten.'
    'Blocker.UnlockNote'    = 'Ontgrendelen schrijft naar het niet-vluchtige geheugen van de modem: de app vraagt eerst om bevestiging.'
    'Blocker.AttemptsLeft'  = 'Resterende pogingen: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Gereed'
    'Sim.PinRequired'    = 'Wacht op de PIN'
    'Sim.PukRequired'    = 'Geblokkeerd: PUK nodig'
    'Sim.Absent'         = 'Geen SIM'
    'Sim.Busy'           = 'Bezet'
    'Sim.Failure'        = 'Werkt niet'
    'Sim.Other'          = 'Wacht op een andere code'
    'Sim.Unknown'        = 'Onbekend'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - resterende PIN-pogingen: {1}'
    'Sim.RequestOn'      = 'PIN-verzoek bij inschakelen: aan'
    'Sim.RequestOff'     = 'PIN-verzoek bij inschakelen: uit'
    'Sim.RequestUnknown' = 'PIN-verzoek bij inschakelen: onbekend'
    'Sim.Stored'         = 'Er is een PIN opgeslagen voor deze SIM.'
    'Sim.NotStored'      = 'Er is geen PIN opgeslagen.'
    'Sim.Rejected'       = 'De opgeslagen PIN is geweigerd en verwijderd: de app probeert hem nooit opnieuw.'

    # The network tab.
    'Bands.Every'       = 'alle banden'
    'Bands.EveryBut'    = 'alle banden behalve {0}'
    'Bands.None'        = 'geen'
    'Network.Current'   = 'De modem nu: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'De netwerkmodus van de modem is nog niet gelezen.'
    'Network.Trial'     = '{0} wordt uitgeprobeerd: als de modem er vóór {1} geen netwerk mee vindt, gaat hij terug naar wat hij had.'
    'Network.Reverted'  = 'Om {0} had de modem geen netwerk gevonden met {1}: hij is teruggegaan naar wat hij had.'
    'Network.Kept'      = 'Om {0} heeft de modem zich geregistreerd met {1}: die blijft behouden.'
    'Network.Missing'   = 'De modem laat {0} weg, hoewel daarom gevraagd is: hij gebruikt de andere gekozen banden.'
    'Network.ChooseBand' = 'Kies minstens één {0}-band, of alle banden.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Versleutelde DNS is niet beschikbaar in deze versie van Windows: DNS over HTTPS op één adapter vereist Windows 11.'
    'Dns.On'                   = 'Versleutelde DNS staat aan: {0}.'
    'Dns.Waiting'              = 'Versleutelde DNS wacht op het adres van de server: intussen is er geen DNS-server ingesteld.'
    'Dns.Off'                  = 'Versleutelde DNS staat uit.'
    'Dns.Advertised'           = 'Het netwerk geeft ook IPv6-DNS-servers op ({0}), die Windows onversleuteld kan gebruiken.'
    'Dns.LookupFailed'         = '{0} kan niet worden opgezocht; de app blijft het proberen.'
    'Dns.LookingUp'            = '{0} opzoeken...'
    'Dns.LookedUp'             = 'De server, {0}, is om {1} opgezocht.'
    'Dns.LookedUpNext'         = 'De server, {0}, is om {1} opgezocht; opnieuw om {2}.'
    'Dns.LookedUpOperator'     = 'De server, {0}, is om {1} onversleuteld opgezocht via de DNS van de provider.'
    'Dns.LookedUpOperatorNext' = 'De server, {0}, is om {1} onversleuteld opgezocht via de DNS van de provider; opnieuw om {2}.'
    'Dns.NotAvailableHere'     = 'Versleutelde DNS is niet beschikbaar in deze versie van Windows.'
    'Dns.NoTemplate'           = 'Windows kent geen DNS-over-HTTPS-sjabloon voor {0}: geef er een op.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; de standaardwaarde wordt gebruikt.'
    'Setting.Unknown'          = 'Onbekende instelling ''{0}'' wordt genegeerd.'
    'Setting.Unreadable'       = 'Het instellingenbestand kan niet worden gelezen; de standaardwaarden worden gebruikt.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps heeft DnsServers nodig, of een DohTemplate die de server noemt: de servers van de provider ondersteunen geen DoH, en er wordt geen DNS-server ingesteld zolang die er niet is.'
    'Setting.TemplateAddress'  = 'DohTemplate noemt het adres {0} en kan dus alleen die server bedienen; de standaardwaarde wordt gebruikt.'
    'Rule.Text'                = 'moet afdrukbare ASCII zijn, zonder dubbele aanhalingstekens of omringende spaties'
    'Rule.TextQuotes'          = 'moet afdrukbare ASCII zijn, zonder dubbele aanhalingstekens'
    'Rule.OneOf'               = 'moet een van {0} zijn'
    'Rule.EmptyOrOneOf'        = 'moet leeg of een van {0} zijn'
    'Rule.Addresses'           = 'moet een lijst met IP-adressen zijn'
    'Rule.Number'              = 'moet een geheel getal van {0} tot {1} zijn'
    'Rule.Minutes'             = 'moet een geheel aantal minuten van {0} tot {1} zijn'
    'Rule.Bool'                = 'moet true of false zijn'
    'Rule.Https'               = 'moet leeg of een https-adres zonder spaties, aanhalingstekens of aanmeldingsgegevens zijn'
    'Rule.Bands'               = 'moet een lijst met verschillende bandnummers van {0} tot {1} zijn'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'het bevat geen stuurprogramma (geen INF-bestand)'
    'DriverProblem.NotForModem'  = 'geen van de stuurprogramma''s is bedoeld voor de AT-poort van deze modem'
    'DriverProblem.NoCatalog'    = 'het stuurprogramma heeft geen handtekeningcatalogus'
    'DriverProblem.NotWhql'      = 'de catalogus is niet door Microsoft ondertekend (WHQL)'
    'DriverProblem.NotInCatalog' = 'het INF-bestand is niet het bestand waarvoor de catalogus instaat: het is gewijzigd of beschadigd'
    'DriverProblem.NotTrusted'   = 'de handtekening kan niet worden geverifieerd'
    'Driver.Present'             = 'De AT-poort van de modem heeft zijn stuurprogramma.'
    'Driver.PresentWhat'         = 'De AT-poort van de modem heeft zijn stuurprogramma: {0}.'
    'Driver.NoDriver'            = 'De AT-poort van de modem heeft geen stuurprogramma: de app kan niet met de modem communiceren.'
    'Driver.Problem'             = 'Windows meldt een probleem met de AT-poort van de modem: het stuurprogramma opnieuw installeren kan dit verhelpen.'
    'Driver.Absent'              = 'Geen modem op USB. Een stuurprogramma dat nu wordt geïnstalleerd, wordt gebruikt zodra de modem wordt aangesloten.'
    'Driver.NotLooked'           = 'De AT-poort van de modem is nog niet gecontroleerd.'
    'Driver.Source'              = 'De app wordt niet met het stuurprogramma van de modem geleverd: er is geen licentie om het opnieuw te distribueren. Download een kopie en kies die hier: de app controleert of Microsoft het voor deze modem heeft ondertekend (WHQL), en start nooit een programma uit het pakket.'
    'Driver.SourceCopy'          = 'De app wordt niet met het stuurprogramma van de modem geleverd: er is geen licentie om het opnieuw te distribueren. Een kopie van het stuurprogramma van MediaTek, {0}, wordt door een derde partij, {1}, gepubliceerd als {2}. Download het en kies het hier: de app controleert of Microsoft het voor deze modem heeft ondertekend (WHQL), en start nooit een programma uit het pakket.'
    'Driver.Checking'            = 'Stuurprogrammapakket controleren...'
    'Driver.Installing'          = 'Het stuurprogramma wordt geïnstalleerd: Windows kan er een minuut over doen.'
    'Driver.Uninstalling'        = 'Stuurprogramma verwijderen...'
    'Driver.Verified'            = '{0}: {1}, een versie die de app kent, door Microsoft ondertekend (WHQL) voor deze modem.'
    'Driver.Signed'              = '{0}: {1}, door Microsoft ondertekend (WHQL) voor deze modem, maar geen versie die de app kent: de app vraagt om bevestiging voordat het wordt geïnstalleerd.'
    'Driver.Refused'             = '{0} kan niet worden geïnstalleerd: {1}.'
    'Driver.ObserveOnly'         = 'De app observeert alleen en wijzigt niets.'
    'Driver.NeedsAdmin'          = 'Voor het installeren of verwijderen van een stuurprogramma zijn administratorrechten nodig: start de app als administrator.'
    'Driver.Trial'               = 'Er wordt een netwerkmodus uitgeprobeerd: het stuurprogramma kan worden verwijderd zodra de proef is afgelopen.'
    'Driver.Install'             = 'Installeren'
    'Driver.InstallConfirm'      = 'Installeren...'
    'Driver.ChooseTitle'         = 'Kies het gedownloade stuurprogrammapakket'
    'Driver.FileKind'            = 'Stuurprogrammapakket'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'De bewaking is gestopt en wordt opnieuw gestart. De verbinding wordt niet aangeraakt.'
    'Window.NotResponding'   = 'De bewaking reageert niet. De verbinding wordt niet aangeraakt.'
    'Window.Starting'        = 'Bezig met starten.'
    'Window.Simulated'       = 'Ontwikkelmodus: een gesimuleerde modem (scenario {0}).'
    'Window.ObserveOnly'     = 'De app observeert alleen en wijzigt niets aan de modem of het systeem.'
    'Window.SettingsPending' = 'De gegevensverbinding is actief met andere instellingen: de nieuwe gelden vanaf de volgende verbinding.'
    'Window.SettingsFile'    = 'Instellingenbestand: {0}'
    'Window.Modems'          = '{0} modems gevonden: de app gebruikt die op {1}.'
    'Window.Recovered'       = 'Hersteld om {0}: {1}'
    'Window.NrAvailable'     = '{0}, 5G beschikbaar'
    'Window.NothingMeasured' = 'Niets gemeten.'
    'Window.PasswordStored'  = 'Er is een wachtwoord opgeslagen.'
    'Window.NoPassword'      = 'Er is geen wachtwoord opgeslagen.'
    'Window.PinFirst'        = 'Typ eerst de PIN van de SIM: voor het verwijderen is de PIN nodig.'
    'Cell.Serving'           = 'Bedienend'
    'Cell.Neighbour'         = 'Naburig'
    'Carrier.Primary'        = 'Primair'
    'Carrier.Active'         = 'Actief'
    'Carrier.Inactive'       = 'Inactief'
    'Footer.Port'            = 'AT-poort {0}'
    'Footer.PortClosed'      = 'AT-poort gesloten'
    'Footer.Updated'         = 'bijgewerkt om {0}'
    'Footer.PathChecked'     = 'datapad gecontroleerd om {0}'
    'Footer.PathFailed'      = 'datapad mislukt om {0}'
    'Footer.PathPending'     = 'datapad om {0} nog niet gecontroleerd'
    'Footer.NotElevated'     = 'geen administratorrechten'
    'Footer.Version'         = 'versie {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'De modem ontgrendelen'
    'Confirm.Unlock'               = @'
De modem ontgrendelen?

Hiermee wordt naar het niet-vluchtige geheugen van de modem geschreven en wordt een beperking opgeheven die de fabrikant van de laptop heeft ingesteld voor de radiocertificering. Dit gebeurt op je eigen verantwoordelijkheid, en het werkt mogelijk niet op elke module.

De modem wordt daarna opnieuw opgestart.
'@
    'Confirm.DisablePinTitle'      = 'De PIN van de SIM verwijderen'
    'Confirm.DisablePin'           = @'
De PIN van de SIM verwijderen?

Dit wijzigt de SIM-kaart, niet de app: de SIM vraagt niet meer om de PIN, in deze modem of in welke telefoon dan ook. Een onjuiste PIN kost een van de pogingen.
'@
    'Confirm.UnknownDriverTitle'   = 'Een onbekende stuurprogrammaversie installeren'
    'Confirm.UnknownDriver'        = @'
Een stuurprogrammaversie installeren die de app niet kent?

Microsoft heeft dit pakket ondertekend (WHQL) voor de AT-poort van de modem, dus Windows accepteert het; maar het is geen versie die de app kent.

Windows installeert het voor elk apparaat waarvoor het geschikt is.
'@
    'Confirm.UninstallDriverTitle' = 'Het stuurprogramma verwijderen'
    'Confirm.UninstallDriver'      = @'
Het stuurprogramma van de AT-poort van de modem verwijderen?

Windows verwijdert het van de seriële poorten van de modem en uit de stuurprogrammaopslag. De gegevensverbinding blijft actief, maar de app kan niet met de modem communiceren en de verbinding niet bewaken, totdat het stuurprogramma opnieuw is geïnstalleerd.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Nu controleren'
    'Xaml.SignalTab'         = 'Signaal'
    'Xaml.Cells'             = 'Cellen'
    'Xaml.Cell'              = 'Cel'
    'Xaml.Band'              = 'Band'
    'Xaml.Channel'           = 'Kanaal'
    'Xaml.Bandwidth'         = 'Bandbreedte'
    'Xaml.CarrierAggregation' = 'Carrier-aggregatie'
    'Xaml.Carrier'           = 'Carrier'
    'Xaml.State'             = 'Status'
    'Xaml.BandwidthDlUl'     = 'Bandbreedte DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulatie DL/UL'
    'Xaml.StorePin'          = 'PIN opslaan'
    'Xaml.ForgetPin'         = 'Opgeslagen PIN vergeten'
    'Xaml.DisablePin'        = 'PIN van de SIM verwijderen...'
    'Xaml.PinNote'           = 'Een opgeslagen PIN wordt versleuteld bewaard voor je Windows-gebruiker, samen met de SIM waar hij bij hoort. De app voert hem één keer in wanneer die SIM erom vraagt - nooit twee keer, nooit als er nog maar één poging over is, en nooit een PUK.'
    'Xaml.NetworkTab'        = 'Netwerk'
    'Xaml.NetworkMode'       = 'Netwerkmodus'
    'Xaml.Apply'             = 'Toepassen'
    'Xaml.Undo'              = 'Wijzigingen ongedaan maken'
    'Xaml.ModeNote'          = 'De modem behoudt zijn netwerkmodus en banden, ook nadat de app is afgesloten. Een modus wordt eerst uitgeprobeerd: als de modem er geen netwerk mee vindt, gaat hij terug naar wat hij had.'
    'Xaml.LteAll'            = 'LTE: alle banden'
    'Xaml.NrAll'             = 'NR: alle banden'
    'Xaml.ConnectionTab'     = 'Verbinding'
    'Xaml.ApnTip'            = 'Leeg: die van je abonnement.'
    'Xaml.PdpType'           = 'PDP-type'
    'Xaml.Authentication'    = 'Verificatie'
    'Xaml.AuthNone'          = 'Geen'
    'Xaml.User'              = 'Gebruiker'
    'Xaml.Password'          = 'Wachtwoord'
    'Xaml.ClearPassword'     = 'Opgeslagen wachtwoord verwijderen'
    'Xaml.DnsServers'        = 'DNS-servers'
    'Xaml.DnsTip'            = 'Gescheiden door komma''s. Leeg: die van de provider.'
    'Xaml.EncryptedDns'      = 'Versleutelde DNS'
    'Xaml.Doh'               = 'DNS over HTTPS naar de servers hierboven, of naar die van het sjabloon - nooit onversleuteld'
    'Xaml.DohTemplate'       = 'DoH-sjabloon'
    'Xaml.DohTemplateTip'    = 'Leeg: het sjabloon dat Windows voor elke server kent. Anders één https-adres voor alle servers; zonder DNS-servers is de naam of het adres daarin de server.'
    'Xaml.RefreshBefore'     = 'De server elke'
    'Xaml.RefreshAfter'      = 'minuten opzoeken, als er geen DNS-server is opgegeven: de naam van het sjabloon is de server.'
    'Xaml.Metric'            = 'Interfacemetriek'
    'Xaml.MetricNote'        = 'Met 500 blijft de modem een back-upverbinding; met een lage waarde wordt hij de voorkeursverbinding.'
    'Xaml.Updates'           = 'Updates'
    'Xaml.UpdateCheck'       = 'Eén keer per start naar een nieuwere versie zoeken'
    'Xaml.Save'              = 'Opslaan'
    'Xaml.DriverTab'         = 'Stuurprogramma'
    'Xaml.OpenPage'          = 'Downloadpagina openen'
    'Xaml.ChoosePackage'     = 'Gedownload pakket kiezen...'
    'Xaml.Install'           = 'Installeren'
    'Xaml.UninstallDriver'   = 'Stuurprogramma verwijderen...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Opstarten'
    'Xaml.StartAtLogon'               = 'De app in het systeemvak starten wanneer je je aanmeldt bij Windows'
    'Startup.NotInstalled'            = 'Alleen de geïnstalleerde app kan starten wanneer je je aanmeldt bij Windows.'
    'Startup.NeedsAdmin'              = 'Voor deze wijziging zijn beheerdersrechten nodig.'
    'Startup.ObserveOnly'             = 'De app observeert alleen en wijzigt niets.'
    'Result.SetStartAtLogon.Enabled'  = 'De app start nu wanneer je je aanmeldt bij Windows.'
    'Result.SetStartAtLogon.Disabled' = 'De app start niet meer wanneer je je aanmeldt bij Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Alleen de geïnstalleerde app kan starten wanneer je je aanmeldt bij Windows: er is niets gewijzigd.'
}
