# The app's texts in Polish: every key of the English file, with the same placeholders.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Nie znaleziono modemu podłączonego przez USB.'
    'Reason.DeviceProblem'         = 'Windows zgłasza problem z portem AT modemu.'
    'Reason.PortInUse'             = 'Inny program używa portu AT modemu.'
    'Reason.BindFailed'            = 'Nie udało się przełączyć portu AT modemu na sterownik WinUSB systemu Windows: aplikacja spróbuje ponownie po kliknięciu „Sprawdź teraz” lub gdy modem zostanie ponownie podłączony.'
    'Reason.BindNotElevated'       = 'Przełączenie portu AT modemu na sterownik WinUSB systemu Windows wymaga uprawnień administratora: uruchom aplikację jako administrator.'
    'Reason.BindRestartNeeded'     = 'Port AT modemu zostanie przełączony na sterownik WinUSB systemu Windows przy następnym ponownym uruchomieniu systemu Windows.'
    'Reason.PortFailed'            = 'Nie można otworzyć portu AT modemu.'
    'Reason.SimUnknown'            = 'Odczytywanie karty SIM.'
    'Reason.NoPin'                 = 'Karta SIM czeka na kod PIN.'
    'Reason.PinForOtherSim'        = 'Zapisany kod PIN należy do innej karty SIM: wprowadź kod PIN tej karty SIM.'
    'Reason.SimNotIdentified'      = 'Nie można zidentyfikować karty SIM, więc zapisany kod PIN nie jest do niej wysyłany.'
    'Reason.PinUnconfirmed'        = 'Ostatnie wprowadzenie kodu PIN pozostało bez odpowiedzi, a aplikacja nigdy nie próbuje dwa razy: wprowadź kod PIN ponownie.'
    'Reason.LastAttempt'           = 'Została tylko jedna próba wprowadzenia kodu PIN i aplikacja jej nie wykorzysta: odblokuj kartę SIM w telefonie.'
    'Reason.PukRequired'           = 'Karta SIM jest zablokowana i wymaga kodu PUK: odblokuj ją w telefonie. Aplikacja nigdy nie wprowadza kodu PUK.'
    'Reason.NoSim'                 = 'Brak karty SIM w modemie.'
    'Reason.SimFailure'            = 'Karta SIM nie działa.'
    'Reason.SimOther'              = 'Karta SIM czeka na kod, którego aplikacja nie obsługuje.'
    'Reason.NoProfile'             = 'Na karcie eSIM nie włączono żadnego profilu.'
    'Reason.SimBusy'               = 'Karta SIM jest zajęta; oczekiwanie na nią.'
    'Reason.FccLocked'             = 'Modem jest zablokowany przez producenta laptopa (blokada FCC): jego radio pozostaje wyłączone.'
    'Reason.NotRegistered'         = 'Nie zarejestrowano w sieci.'
    'Reason.NotSearching'          = 'Nie zarejestrowano w sieci i nie trwa wyszukiwanie sieci.'
    'Reason.Searching'             = 'Wyszukiwanie sieci.'
    'Reason.Denied'                = 'Sieć odmówiła rejestracji.'
    'Reason.Unknown'               = 'Nie zarejestrowano w sieci; przyczyna jest nieznana.'
    'Reason.EmergencyOnly'         = 'Tylko połączenia alarmowe.'
    'Reason.ContextUnknown'        = 'Odczytywanie połączenia danych.'
    'Reason.ApnPasswordUnreadable' = 'Nie można odczytać zapisanego hasła APN: wprowadź je ponownie.'
    'Reason.ApnNeeded'             = 'Sieć nie dała dostępu do internetu przy pustym APN: wprowadź APN swojego operatora.'
    'Reason.NoAddress'             = 'Połączenie danych nie ma adresu IPv4.'
    'Reason.AdapterDisabled'       = 'Karta sieciowa modemu jest wyłączona.'
    'Reason.NoAdapter'             = 'Brak karty sieciowej modemu.'
    'Reason.NotElevated'           = 'Kartę sieciową można skonfigurować tylko z uprawnieniami administratora: uruchom aplikację jako administrator.'
    'Reason.DataPathFailed'        = 'Połączenie jest aktywne, ale ruch nie przechodzi.'
    'Reason.DohServerUnresolved'   = 'Adres serwera DNS over HTTPS nie został jeszcze wyszukany: aplikacja nadal próbuje, a do tego czasu pozostawia kartę sieciową w takim stanie, w jakim skonfigurował ją modem.'
    'Reason.DohNeedsServers'       = 'Szyfrowany DNS wymaga samodzielnie wybranych serwerów DNS: serwery operatora nie obsługują DNS over HTTPS. Do tego czasu karta sieciowa nie jest konfigurowana.'
    'Reason.DohUnavailable'        = 'Ta wersja systemu Windows nie może szyfrować DNS na pojedynczej karcie sieciowej - DNS over HTTPS wymaga systemu Windows 11: wyłącz szyfrowany DNS. Do tego czasu karta sieciowa nie jest konfigurowana.'
    'Reason.DohTemplateMissing'    = 'Windows nie zna szablonu DNS over HTTPS dla jednego z serwerów DNS z ustawień: podaj szablon lub wybierz serwery, które Windows zna. Do tego czasu karta sieciowa nie jest konfigurowana.'
    'Reason.Connected'             = 'Połączono.'
    'Reason.Other'                 = 'Nie zarejestrowano w sieci ({0}).'
    'Reason.Working'               = 'Trwa praca nad połączeniem.'
    'Reason.NoNetworkForMode'      = 'Nie znaleziono sieci w trybie {0}. Żaden reset jej nie znajdzie: wybierz szerszy tryb sieci.'
    'Reason.NoNetworkForModeBands' = 'Nie znaleziono sieci w trybie {0} w wybranych pasmach LTE. Żaden reset jej nie znajdzie: wybierz szerszy tryb sieci.'
    'Reason.Withheld'              = 'Aplikacja tylko obserwuje, więc nie wykonuje następnego kroku: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'Otwieranie portu AT modemu.'
    'Action.BindUsb'                 = 'Przełączanie portu AT modemu na sterownik WinUSB systemu Windows.'
    'Action.Initialize'              = 'Oczekiwanie na odpowiedź modemu.'
    'Action.EnterPin'                = 'Wprowadzanie zapisanego kodu PIN.'
    'Action.RadioOn'                 = 'Włączanie radia.'
    'Action.AutoRegister'            = 'Automatyczne wybieranie sieci.'
    'Action.DefineContext'           = 'Nawiązywanie połączenia danych.'
    'Action.ActivateContext'         = 'Nawiązywanie połączenia danych.'
    'Action.DeactivateContext'       = 'Nawiązywanie połączenia danych.'
    'Action.ConfigureAdapter'        = 'Konfigurowanie karty sieciowej.'
    'Action.ApplyNetworkMode'        = 'Ustawianie trybu sieci.'
    'ActionInline.OpenPort'          = 'otwieranie portu AT modemu.'
    'ActionInline.BindUsb'           = 'przełączanie portu AT modemu na sterownik WinUSB systemu Windows.'
    'ActionInline.Initialize'        = 'oczekiwanie na odpowiedź modemu.'
    'ActionInline.EnterPin'          = 'wprowadzanie zapisanego kodu PIN.'
    'ActionInline.RadioOn'           = 'włączanie radia.'
    'ActionInline.AutoRegister'      = 'automatyczne wybieranie sieci.'
    'ActionInline.DefineContext'     = 'nawiązywanie połączenia danych.'
    'ActionInline.ActivateContext'   = 'nawiązywanie połączenia danych.'
    'ActionInline.DeactivateContext' = 'nawiązywanie połączenia danych.'
    'ActionInline.ConfigureAdapter'  = 'konfigurowanie karty sieciowej.'
    'ActionInline.ApplyNetworkMode'  = 'ustawianie trybu sieci.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Tylko 4G'
    'Mode.NrOnly'                  = 'Tylko 5G (SA)'
    'Mode.NotManaged'              = 'Jak ustawiono w modemie'
    'Mode.Other'                   = 'tryb {0}'
    'ModeProblem.NotKept'          = 'Modem nie zachowuje trybu sieci w zapisanej postaci; aplikacja nie zapisuje go ponownie.'
    'ModeProblem.NoSupportedBand'  = 'Modem nie obsługuje żadnego z pasm wybranych dla jednej ze swoich technologii RAT.'
    'ModeProblem.ModeUnsupported'  = 'Modem nie obsługuje tego trybu sieci.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'Trwa sprawdzanie połączenia.'
    'Result.SaveSettings.Done'              = 'Zapisano ustawienia.'
    'Result.SaveSettings.NoSim'             = 'Żadna karta SIM nie jest gotowa: ustawień nie zapisano, ponieważ ustawienia APN należą do używanej karty SIM.'
    'Result.SaveSettings.SimChanged'        = 'Używana karta SIM się zmieniła: ustawień nie zapisano. Sprawdź jej ustawienia APN i zapisz ponownie.'
    'Result.SaveSimPin.Done'                = 'Zapisano kod PIN: aplikacja wprowadza go jeden raz, gdy karta SIM o niego poprosi.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Nie można zidentyfikować karty SIM: kod PIN nie został zapisany.'
    'Result.ForgetSimPin.Done'              = 'Usunięto zapisany kod PIN.'
    'Result.DisableSimPin.Disabled'         = 'Karta SIM nie żąda już kodu PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'Żądanie kodu PIN przez kartę SIM było już wyłączone.'
    'Result.DisableSimPin.PinRejected'      = 'Nieprawidłowy kod PIN: karta SIM nadal go żąda.'
    'Result.DisableSimPin.LastAttempt'      = 'Została tylko jedna próba wprowadzenia kodu PIN: nic nie zostało wysłane.'
    'Result.DisableSimPin.SimNotReady'      = 'Karta SIM nie jest gotowa: nic nie zostało wysłane.'
    'Result.DisableSimPin.Failed'           = 'Nie udało się zmienić żądania kodu PIN przez kartę SIM.'
    'Result.UnlockFcc.Restarted'            = 'Wysłano odblokowanie: modem jest uruchamiany ponownie.'
    'Result.UnlockFcc.NotLocked'            = 'Modem nie jest zablokowany: nic nie zostało zapisane.'
    'Result.UnlockFcc.Unknown'              = 'Nie można odczytać blokady: nic nie zostało zapisane.'
    'Result.UnlockFcc.Failed'               = 'Odblokowywanie zatrzymało się przed ponownym uruchomieniem.'
    'Result.UnlockFcc.PortLost'             = 'Modem odłączył się od USB podczas odblokowywania.'
    'Result.EnableAdapter.Done'             = 'Włączono kartę sieciową.'
    'Result.SetNetworkMode.Applied'         = 'Wysłano tryb sieci: modem ponownie rejestruje się w sieci. Tryb zostanie zachowany, gdy modem znajdzie w nim sieć.'
    'Result.SetNetworkMode.Unchanged'       = 'Modem ma już ten tryb sieci: zostaje on zachowany.'
    'Result.SetNetworkMode.Done'            = 'Aplikacja nie zarządza już trybem sieci: modem zachowuje obecny tryb.'
    'Result.SetNetworkMode.ModeUnsupported' = 'Modem nie obsługuje tego trybu sieci: nic nie zostało zapisane.'
    'Result.SetNetworkMode.NoSupportedBand' = 'Modem nie obsługuje żadnego z pasm wybranych dla jednej ze swoich technologii RAT: nic nie zostało zapisane.'
    'Result.SetNetworkMode.Unknown'         = 'Nie można odczytać trybu sieci modemu: nic nie zostało zapisane.'
    'Result.NotElevated'                    = 'To wymaga uprawnień administratora.'
    'Result.Refused'                        = 'Niedostępne, gdy aplikacja tylko obserwuje.'
    'Result.NoModem'                        = 'Modem nie jest podłączony.'
    'Result.PortLost'                       = 'Modem odłączył się od USB podczas wykonywania polecenia.'
    'Result.Failed'                         = 'Nie udało się.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Pozostałe próby: {0}.'
    'Result.Restarting'                     = 'Proces monitorujący jest uruchamiany ponownie: spróbuj ponownie za chwilę.'

    # The headline.
    'Tone.Online'         = 'Połączono'
    'Tone.Working'        = 'Łączenie'
    'Tone.Recovering'     = 'Przywracanie'
    'Tone.Attention'      = 'Wymagana akcja'
    'Tone.Offline'        = 'Brak modemu'
    'Tone.Stopped'        = 'Bez monitorowania'
    'Title.ConnectionLost' = 'Utracono połączenie'
    'Title.NoNetwork'     = 'Brak sieci'
    'Title.NotConnected'  = 'Nie połączono'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'Modem nie jest podłączony przez USB.'
    'Check.H2'          = 'Modem nie odpowiada.'
    'Check.H3'          = 'Karta SIM nie jest gotowa.'
    'Check.H4'          = 'Nie zarejestrowano w sieci.'
    'Check.H5'          = 'Połączenie danych jest nieaktywne.'
    'Check.H6'          = 'Karta sieciowa nie jest skonfigurowana.'
    'Check.H7'          = 'Ruch nie przechodzi.'
    'Check.Other'       = 'Połączenie jest nieaktywne.'
    'Step.R1'           = 'Ponowne konfigurowanie karty sieciowej.'
    'Step.R2'           = 'Ponowne uruchamianie połączenia danych.'
    'Step.R3'           = 'Ponowna rejestracja w sieci.'
    'Step.R4'           = 'Wyłączanie i włączanie radia.'
    'Step.R5'           = 'Ponowne uruchamianie modemu.'
    'Step.R6'           = 'Ponowne uruchamianie urządzenia USB modemu.'
    'StepInline.R1'     = 'ponowne konfigurowanie karty sieciowej.'
    'StepInline.R2'     = 'ponowne uruchamianie połączenia danych.'
    'StepInline.R3'     = 'ponowna rejestracja w sieci.'
    'StepInline.R4'     = 'wyłączanie i włączanie radia.'
    'StepInline.R5'     = 'ponowne uruchamianie modemu.'
    'StepInline.R6'     = 'ponowne uruchamianie urządzenia USB modemu.'
    'Recovery.Waiting'  = '{0} Kroki przywracania nie pomogły: zaczną się od nowa o {1}.'
    'Recovery.Slow'     = '{0} Nieudane próby przywrócenia: {1}. Aplikacja spróbuje ponownie o {2}.'
    'Recovery.Withheld' = '{0} Aplikacja tylko obserwuje, więc nie wykonuje kroku przywracania: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Otwórz'
    'Tray.CheckNow'       = 'Sprawdź teraz'
    'Tray.NetworkMode'    = 'Tryb sieci'
    'Tray.NetworkModeNow' = 'Tryb sieci: {0}'
    'Tray.Exit'           = 'Zakończ'
    'Tray.Update'         = 'Dostępna wersja {0}...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Użyj {0}, wszystkie pasma'
    'Blocker.SaveApn'       = 'Zapisz APN'
    'Blocker.SavePassword'  = 'Zapisz hasło'
    'Blocker.StorePin'      = 'Zapisz PIN'
    'Blocker.EnableAdapter' = 'Włącz kartę'
    'Blocker.Unlock'        = 'Odblokuj...'
    'Blocker.OpenSettings'  = 'Otwórz ustawienia'
    'Blocker.ObserveOnly'   = 'Aplikacja tylko obserwuje: niczego nie zmienia.'
    'Blocker.NeedsAdmin'    = 'Jej włączenie wymaga uprawnień administratora.'
    'Blocker.UnlockNote'    = 'Odblokowanie zapisuje dane w pamięci nieulotnej modemu: aplikacja najpierw pyta o zgodę.'
    'Blocker.AttemptsLeft'  = 'Pozostałe próby: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Gotowa'
    'Sim.PinRequired'    = 'Czeka na kod PIN'
    'Sim.PukRequired'    = 'Zablokowana: wymaga kodu PUK'
    'Sim.Absent'         = 'Brak karty SIM'
    'Sim.Busy'           = 'Zajęta'
    'Sim.Failure'        = 'Nie działa'
    'Sim.Other'          = 'Czeka na inny kod'
    'Sim.NoProfile'      = 'eSIM bez włączonego profilu'
    'Sim.Unknown'        = 'Stan nieznany'
    'Sim.State'          = 'Karta SIM: {0}'
    'Sim.StateAttempts'  = 'Karta SIM: {0} - pozostałe próby wprowadzenia kodu PIN: {1}'
    'Sim.RequestOn'      = 'Żądanie kodu PIN przy włączaniu: włączone'
    'Sim.RequestOff'     = 'Żądanie kodu PIN przy włączaniu: wyłączone'
    'Sim.RequestUnknown' = 'Żądanie kodu PIN przy włączaniu: nieznane'
    'Sim.Stored'         = 'Dla tej karty SIM zapisano kod PIN.'
    'Sim.NotStored'      = 'Nie zapisano kodu PIN.'
    'Sim.Rejected'       = 'Zapisany kod PIN został odrzucony i usunięty: aplikacja nigdy nie spróbuje go ponownie.'

    # The network tab.
    'Bands.Every'       = 'wszystkie pasma'
    'Bands.EveryBut'    = 'wszystkie pasma oprócz {0}'
    'Bands.None'        = 'brak'
    'Network.Current'   = 'Modem obecnie: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'Tryb sieci modemu nie został jeszcze odczytany.'
    'Network.Trial'     = 'Próba trybu {0}: jeśli modem nie znajdzie w nim sieci do {1}, wróci do poprzedniego ustawienia.'
    'Network.Reverted'  = 'O {0} modem nie znalazł sieci w trybie {1}: wrócił do poprzedniego ustawienia.'
    'Network.Kept'      = 'O {0} modem zarejestrował się w trybie {1}: tryb zostaje zachowany.'
    'Network.Missing'   = 'Modem pomija {0}, mimo że o to poproszono: używa pozostałych wybranych pasm.'
    'Network.ChooseBand' = 'Wybierz co najmniej jedno pasmo {0} lub wszystkie pasma.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'Szyfrowany DNS nie jest dostępny w tej wersji systemu Windows: DNS over HTTPS na pojedynczej karcie sieciowej wymaga systemu Windows 11.'
    'Dns.On'                   = 'Szyfrowany DNS jest włączony: {0}.'
    'Dns.Waiting'              = 'Szyfrowany DNS czeka na adres swojego serwera: do tego czasu nie jest ustawiony żaden serwer DNS.'
    'Dns.Off'                  = 'Szyfrowany DNS jest wyłączony.'
    'Dns.Advertised'           = 'Sieć podaje też serwery DNS IPv6 ({0}), których Windows może używać bez szyfrowania.'
    'Dns.LookupFailed'         = 'Nie można wyszukać adresu {0}; aplikacja nadal próbuje.'
    'Dns.LookingUp'            = 'Wyszukiwanie adresu {0}...'
    'Dns.LookedUp'             = 'Adres serwera {0} wyszukano o {1}.'
    'Dns.LookedUpNext'         = 'Adres serwera {0} wyszukano o {1}; następne wyszukiwanie o {2}.'
    'Dns.LookedUpOperator'     = 'Adres serwera {0} wyszukano o {1} przez DNS operatora, bez szyfrowania.'
    'Dns.LookedUpOperatorNext' = 'Adres serwera {0} wyszukano o {1} przez DNS operatora, bez szyfrowania; następne wyszukiwanie o {2}.'
    'Dns.NotAvailableHere'     = 'Szyfrowany DNS nie jest dostępny w tej wersji systemu Windows.'
    'Dns.NoTemplate'           = 'Windows nie zna szablonu DNS over HTTPS dla serwera {0}: podaj szablon.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; używana jest wartość domyślna.'
    'Setting.Unknown'          = 'Nieznane ustawienie „{0}” jest ignorowane.'
    'Setting.Unreadable'       = 'Nie można odczytać pliku ustawień; używane są wartości domyślne.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps wymaga DnsServers lub DohTemplate wskazującego serwer: serwery operatora nie obsługują DoH, a do tego czasu nie jest ustawiony żaden serwer DNS.'
    'Setting.TemplateAddress'  = 'DohTemplate wskazuje adres {0}, więc może obsługiwać tylko ten serwer; używana jest wartość domyślna.'
    'Rule.Text'                = 'musi składać się z drukowalnych znaków ASCII, bez cudzysłowów i bez odstępów na początku lub na końcu'
    'Rule.TextQuotes'          = 'musi składać się z drukowalnych znaków ASCII, bez cudzysłowów'
    'Rule.OneOf'               = 'musi mieć jedną z wartości: {0}'
    'Rule.EmptyOrOneOf'        = 'musi mieć pustą wartość lub jedną z wartości: {0}'
    'Rule.Addresses'           = 'musi być listą adresów IP'
    'Rule.Number'              = 'musi być liczbą całkowitą od {0} do {1}'
    'Rule.Minutes'             = 'musi być liczbą całkowitą minut od {0} do {1}'
    'Rule.Bool'                = 'musi mieć wartość true lub false'
    'Rule.Https'               = 'musi mieć pustą wartość lub być adresem https bez odstępów, cudzysłowów i poświadczeń'
    'Rule.Bands'               = 'musi być listą różnych numerów pasm od {0} do {1}'
    'Rule.Gigabytes'           = 'musi być liczbą gigabajtów od {0} do {1}, 0 oznacza brak'

    # The USB tab.
    'Usb.Present'                 = 'Port AT modemu działa na sterowniku WinUSB systemu Windows: nie trzeba instalować żadnego sterownika.'
    'Usb.Unbound'                 = 'Port AT modemu nie działa jeszcze na sterowniku WinUSB systemu Windows: aplikacja go przełącza.'
    'Usb.NotLooked'               = 'Funkcje modemu nie zostały jeszcze sprawdzone.'
    'Usb.FunctionName'            = '{0} (MI_{1})'
    'Usb.FunctionLine'            = '{0}: {1}'
    'Usb.Function.MdAt'           = 'Port AT'
    'Usb.Function.MdMeta'         = 'Port META modemu'
    'Usb.Function.ApMeta'         = 'Port META AP'
    'Usb.Function.ApLog'          = 'Port dziennika AP'
    'Usb.Function.ApGnss'         = 'Port GNSS'
    'Usb.Function.Npt'            = 'Port NPT'
    'Usb.Function.Debug'          = 'Port debugowania'
    'Usb.Function.Other'          = 'Funkcja'
    'Usb.OnWinUsb'                = 'WinUSB'
    'Usb.OtherDriver'             = 'inny sterownik'
    'Usb.NoDriver'                = 'brak sterownika'
    'Usb.ProblemCode'             = '{0}, kod problemu {1}'
    'Usb.LastChange'              = 'Ostatnie przełączenie o {0}:'
    'Usb.Bound'                   = '{0}: przełączono na WinUSB.'
    'Usb.Held'                    = '{0}: pozostawiono na dotychczasowym sterowniku, inny program używa portu.'
    'Usb.Failed'                  = '{0}: nie przełączono na WinUSB ({1}).'
    'Usb.RestartNeeded'           = '{0}: na WinUSB po następnym ponownym uruchomieniu systemu Windows.'
    'Usb.ObserveOnly'             = 'Aplikacja tylko obserwuje: nie przełącza żadnej funkcji na WinUSB.'
    'Usb.NeedsAdmin'              = 'Przełączenie funkcji modemu na WinUSB wymaga uprawnień administratora: uruchom aplikację jako administrator.'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'Proces monitorujący zatrzymał się i jest uruchamiany ponownie. Połączenie pozostaje nienaruszone.'
    'Window.NotResponding'   = 'Proces monitorujący nie odpowiada. Połączenie pozostaje nienaruszone.'
    'Window.Starting'        = 'Uruchamianie.'
    'Window.Simulated'       = 'Tryb deweloperski: symulowany modem (scenariusz {0}).'
    'Window.ObserveOnly'     = 'Aplikacja tylko obserwuje: niczego nie zmienia w modemie ani w systemie.'
    'Window.SettingsPending' = 'Połączenie danych działa z innymi ustawieniami: nowe zostaną zastosowane przy następnym połączeniu.'
    'Window.SettingsFile'    = 'Plik ustawień: {0}'
    'Window.Modems'          = 'Znalezione modemy: {0}. Aplikacja używa jednego z nich, zawsze tego samego.'
    'Window.Recovered'       = 'Przywrócono o {0}: {1}'
    'Window.NrAvailable'     = '{0}, dostępne 5G'
    'Window.NothingMeasured' = 'Brak pomiarów.'
    'Window.PasswordStored'  = 'Hasło jest zapisane.'
    'Window.NoPassword'      = 'Nie zapisano hasła.'
    'Window.ApnPerSim'       = 'Każda karta SIM ma własne ustawienia APN: to są ustawienia używanej karty SIM.'
    'Window.ApnNoSim'        = 'Każda karta SIM ma własne ustawienia APN: można je zmienić, gdy karta SIM będzie gotowa.'
    'Window.PinFirst'        = 'Najpierw wpisz kod PIN karty SIM: jego usunięcie wymaga kodu PIN.'
    'Cell.Serving'           = 'Obsługująca'
    'Cell.Neighbour'         = 'Sąsiednia'
    'Carrier.Primary'        = 'Podstawowa'
    'Carrier.Active'         = 'Aktywna'
    'Carrier.Inactive'       = 'Nieaktywna'
    'Footer.Port'            = 'Port AT przez {0}'
    'Footer.PortClosed'      = 'Port AT zamknięty'
    'Footer.Updated'         = 'zaktualizowano {0}'
    'Footer.PathChecked'     = 'ścieżka danych sprawdzona o {0}'
    'Footer.PathFailed'      = 'błąd ścieżki danych o {0}'
    'Footer.PathPending'     = 'ścieżka danych jeszcze niesprawdzona o {0}'
    'Footer.NotElevated'     = 'brak uprawnień administratora'
    'Footer.Version'         = 'wersja {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Odblokuj modem'
    'Confirm.Unlock'               = @'
Odblokować modem?

Spowoduje to zapis w pamięci nieulotnej modemu i zniesie ograniczenie, które producent laptopa ustawił na potrzeby certyfikacji radiowej. Odbywa się to na własną odpowiedzialność, a operacja może nie zadziałać na każdym module.

Następnie modem zostanie uruchomiony ponownie.
'@
    'Confirm.DisablePinTitle'      = 'Usuń kod PIN z karty SIM'
    'Confirm.DisablePin'           = @'
Usunąć kod PIN z karty SIM?

To zmienia kartę SIM, a nie aplikację: karta SIM przestanie żądać kodu PIN w tym modemie i w każdym telefonie. Nieprawidłowy kod PIN zużywa jedną z jej prób.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Sprawdź teraz'
    'Xaml.SignalTab'         = 'Sygnał'
    'Xaml.Cells'             = 'Komórki'
    'Xaml.Cell'              = 'Komórka'
    'Xaml.Band'              = 'Pasmo'
    'Xaml.Channel'           = 'Kanał'
    'Xaml.Bandwidth'         = 'Szerokość pasma'
    'Xaml.CarrierAggregation' = 'Agregacja nośnych'
    'Xaml.Carrier'           = 'Nośna'
    'Xaml.State'             = 'Stan'
    'Xaml.BandwidthDlUl'     = 'Szerokość pasma DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulacja DL/UL'
    'Xaml.StorePin'          = 'Zapisz PIN'
    'Xaml.ForgetPin'         = 'Zapomnij zapisany PIN'
    'Xaml.DisablePin'        = 'Usuń PIN z karty SIM...'
    'Xaml.PinNote'           = 'Zapisany kod PIN jest przechowywany w postaci zaszyfrowanej dla Twojego konta użytkownika Windows, wraz z informacją, do której karty SIM należy. Aplikacja wprowadza go jeden raz, gdy ta karta SIM o niego poprosi - nigdy dwa razy, nigdy przy ostatniej pozostałej próbie i nigdy nie wprowadza kodu PUK.'
    'Xaml.NetworkTab'        = 'Sieć'
    'Xaml.NetworkMode'       = 'Tryb sieci'
    'Xaml.Apply'             = 'Zastosuj'
    'Xaml.Undo'              = 'Cofnij zmiany'
    'Xaml.ModeNote'          = 'Modem zachowuje swój tryb sieci i pasma, również po zamknięciu aplikacji. Tryb jest najpierw testowany: jeśli modem nie znajdzie w nim sieci, wraca do poprzedniego ustawienia.'
    'Xaml.LteAll'            = 'LTE: wszystkie pasma'
    'Xaml.NrAll'             = 'NR: wszystkie pasma'
    'Xaml.ConnectionTab'     = 'Połączenie'
    'Xaml.ApnTip'            = 'Puste: APN z abonamentu.'
    'Xaml.PdpType'           = 'Typ PDP'
    'Xaml.Authentication'    = 'Uwierzytelnianie'
    'Xaml.AuthNone'          = 'Brak'
    'Xaml.User'              = 'Użytkownik'
    'Xaml.Password'          = 'Hasło'
    'Xaml.ClearPassword'     = 'Usuń zapisane hasło'
    'Xaml.DnsServers'        = 'Serwery DNS'
    'Xaml.DnsTip'            = 'Rozdzielone przecinkami. Puste: serwery operatora.'
    'Xaml.EncryptedDns'      = 'Szyfrowany DNS'
    'Xaml.Doh'               = 'DNS over HTTPS do powyższych serwerów lub do serwera z szablonu - nigdy bez szyfrowania'
    'Xaml.DohTemplate'       = 'Szablon DoH'
    'Xaml.DohTemplateTip'    = 'Puste: szablon znany systemowi Windows dla każdego serwera. W przeciwnym razie jeden adres https dla wszystkich; bez serwerów DNS serwerem jest jego nazwa lub adres.'
    'Xaml.RefreshBefore'     = 'Wyszukuj adres serwera co'
    'Xaml.RefreshAfter'      = 'min, gdy nie podano serwerów DNS: serwerem jest nazwa z szablonu.'
    'Xaml.Metric'            = 'Metryka interfejsu'
    'Xaml.MetricNote'        = '500 utrzymuje modem jako połączenie zapasowe; niska wartość czyni go połączeniem preferowanym.'
    'Xaml.Updates'           = 'Aktualizacje'
    'Xaml.UpdateCheck'       = 'Szukaj nowszej wersji raz przy każdym uruchomieniu'
    'Xaml.Save'              = 'Zapisz'
    'Xaml.UsbTab'            = 'USB'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Uruchamianie'
    'Xaml.StartAtLogon'               = 'Uruchamiaj aplikację w obszarze powiadomień po zalogowaniu do systemu Windows'
    'Startup.NotInstalled'            = 'Tylko zainstalowana aplikacja może się uruchamiać po zalogowaniu do systemu Windows.'
    'Startup.NeedsAdmin'              = 'Ta zmiana wymaga uprawnień administratora.'
    'Startup.ObserveOnly'             = 'Aplikacja tylko obserwuje: niczego nie zmienia.'
    'Result.SetStartAtLogon.Enabled'  = 'Aplikacja uruchamia się teraz po zalogowaniu do systemu Windows.'
    'Result.SetStartAtLogon.Disabled' = 'Aplikacja nie uruchamia się już po zalogowaniu do systemu Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Tylko zainstalowana aplikacja może się uruchamiać po zalogowaniu do systemu Windows: niczego nie zmieniono.'

    # The messages tab and data usage (M8).
    'Xaml.MessagesTab'              = 'Wiadomości'
    'Xaml.From'                     = 'Od'
    'Xaml.Time'                     = 'Czas'
    'Xaml.Message'                  = 'Wiadomość'
    'Xaml.DeleteMessage'            = 'Usuń...'
    'Xaml.NewMessage'               = 'Nowa wiadomość'
    'Xaml.To'                       = 'Do'
    'Xaml.Send'                     = 'Wyślij'
    'Xaml.SendNote'                 = 'Każda część to osobna wiadomość, za którą operator może pobrać opłatę. Część, której nie udało się wysłać, nigdy nie jest wysyłana ponownie automatycznie.'
    'Messages.TabNew'               = 'Wiadomości ({0})'
    'Messages.Storage'              = 'Zajęte miejsca na karcie SIM: {0} z {1}.'
    'Messages.Full'                 = 'Karta SIM jest pełna: nowych wiadomości nie można zapisać, dopóki część nie zostanie usunięta.'
    'Messages.Empty'                = 'Brak wiadomości na karcie SIM.'
    'Messages.Hidden'               = 'Wiadomości odebrane w innym profilu eSIM, widoczne, gdy jest on używany: {0}.'
    'Messages.ObserveOnly'          = 'Wiadomości nie są odczytywane, gdy aplikacja tylko obserwuje: odczyt oznacza je w modemie jako przeczytane.'
    'Messages.NoModem'              = 'Modem nie jest podłączony.'
    'Messages.NotReady'             = 'Wiadomości są odczytywane, gdy karta SIM będzie gotowa.'
    'Messages.Header'               = 'Od {0}, {1}'
    'Messages.Missing'              = 'Części (jeszcze) nieodebrane: {0}.'
    'Messages.Binary'               = 'Ta wiadomość zawiera dane, nie tekst.'
    'Messages.Compressed'           = 'Ta wiadomość jest skompresowana: aplikacja nie może jej pokazać.'
    'Messages.Malformed'            = 'Tej wiadomości nie można odczytać.'
    'Messages.NationalLanguage'     = 'Używa narodowej tabeli językowej, której aplikacja nie ma: niektóre znaki mogą być błędne.'
    'Messages.Silent'               = 'Cicha wiadomość: sieć poprosiła, aby nigdy jej nie pokazywać.'
    'Messages.SilentNote'           = 'Zajmuje miejsce na karcie SIM, dopóki nie zostanie usunięta.'
    'Messages.Sending'              = 'Wysyłanie wiadomości...'
    'Messages.From'                 = 'Wiadomość jest wysyłana z używanej karty SIM: modem używa jednej naraz. Aby wysłać z drugiej, włącz ją na karcie SIM lub eSIM.'
    'Messages.FromGoneProfile'      = 'Odebrano ją w profilu eSIM {0}, który nie jest teraz używany.'
    'Messages.FromOtherProfile'     = 'Odebrano ją w innym profilu eSIM, który nie jest teraz używany.'
    'Messages.FromOtherSim'         = 'Odebrano ją na innej karcie SIM, która nie jest teraz używana.'
    'Messages.Count'                = 'Znaki: {0} - części: {1}'
    'Messages.CountUnicode'         = 'Znaki: {0} - części: {1} (ze znakami specjalnymi {2} na część)'
    'Messages.TooLong'              = 'Za długa: wiadomość ma co najwyżej 255 części.'
    'Result.SendMessage.Sent'       = 'Wiadomość wysłana.'
    'Result.SendMessage.Failed'     = 'Wiadomość nie została wysłana w całości: wysłano {0} z {1} części.'
    'Result.SendMessage.Invalid'    = 'Wpisz numer telefonu i tekst.'
    'Result.DeleteMessage.Done'     = 'Wiadomość usunięta z karty SIM.'
    'Result.DeleteMessage.NotFound' = 'Wiadomości nie ma już na karcie SIM.'
    'Result.DeleteMessage.Failed'   = 'Nie udało się usunąć wiadomości.'
    'Result.NotReady'               = 'Karta SIM nie jest gotowa.'
    'Confirm.DeleteMessageTitle'    = 'Usuń wiadomość'
    'Confirm.DeleteMessage'         = @'
Usunąć tę wiadomość z karty SIM?

Tej operacji nie można cofnąć.
'@
    'Tray.NewMessage'               = 'Nowa wiadomość'
    'Tray.NewMessages'              = 'Nowe wiadomości: {0}'
    'Tray.MessageFrom'              = 'Od {0}'
    'Xaml.DataTab'                  = 'Dane'
    'Xaml.CycleDay'                 = 'Okres rozliczeniowy zaczyna się dnia'
    'Xaml.Quota'                    = 'Limit danych (GB)'
    'Xaml.QuotaNote'                = '0: brak. Przy 80% i 100% limitu obszar powiadomień o tym informuje, raz na okres; połączenie pozostaje aktywne.'
    'Xaml.UsageNote'                = 'Liczone na karcie sieciowej modemu: szacunek, który może się różnić od wyliczenia operatora.'
    'Usage.Today'                   = 'Dzisiaj: {0} (odebrano {1}, wysłano {2})'
    'Usage.Cycle'                   = 'Ten okres, od {0} do {1}: {2} (odebrano {3}, wysłano {4})'
    'Usage.Quota'                   = 'Limit: wykorzystano {0} z {1} ({2}%)'
    'Usage.NoQuota'                 = 'Nie ustawiono limitu.'
    'Usage.NotCounted'              = 'Jeszcze nic nie policzono: karta sieciowa modemu nie została odczytana.'
    'Tray.Usage'                    = 'Dane dzisiaj {0}, ten okres {1}'
    'Tray.UsageQuota'               = 'Dane dzisiaj {0}, ten okres {1} z {2}'
    'Tray.QuotaTitle'               = 'Limit danych'
    'Tray.Quota'                    = 'Wykorzystano {0}% limitu w tym okresie. Połączenie pozostaje aktywne.'

    # The eSIM tab and the SIM in use (M9).
    'Xaml.EsimTab'                              = 'eSIM'
    'Xaml.EsimProfiles'                         = 'Profile'
    'Xaml.EsimName'                             = 'Nazwa'
    'Xaml.EsimProvider'                         = 'Dostawca'
    'Xaml.EsimKind'                             = 'Rodzaj'
    'Xaml.EsimNickname'                         = 'Własna nazwa'
    'Xaml.EsimEnable'                           = 'Włącz...'
    'Xaml.EsimDisable'                          = 'Wyłącz...'
    'Xaml.EsimDelete'                           = 'Usuń...'
    'Xaml.EsimRename'                           = 'Zmień nazwę'
    'Xaml.EsimReadAgain'                        = 'Odczytaj ponownie'
    'Xaml.EsimCopy'                             = 'Kopiuj'
    'Xaml.EsimDownload'                         = 'Pobierz profil'
    'Xaml.EsimCode'                             = 'Kod aktywacyjny (LPA:1$...), taki jak podał dostawca'
    'Xaml.EsimReadQr'                           = 'Odczytaj kod QR...'
    'Xaml.EsimConfirmation'                     = 'Kod potwierdzenia, jeśli dostawca go podał'
    'Xaml.EsimDownloadButton'                   = 'Pobierz'
    'Xaml.EsimDownloadNote'                     = 'Pobieranie wysyła numer EID karty eSIM do serwera dostawcy wskazanego w kodzie. Profil jest pobierany jako wyłączony: włącz go, aby z niego korzystać.'
    'SimInUse.Physical'                         = 'Używana karta SIM: gniazdo {0}, fizyczna karta SIM.'
    'SimInUse.Esim'                             = 'Używana karta SIM: gniazdo {0}, eSIM - {1}.'
    'SimInUse.EsimEmpty'                        = 'Używana karta SIM: gniazdo {0}, eSIM bez włączonego profilu.'
    'SimInUse.EsimUnread'                       = 'Używana karta SIM: gniazdo {0}, eSIM.'
    'SimInUse.Slot'                             = 'Używana karta SIM: gniazdo {0}.'
    'Sim.UsePhysical'                           = 'Użyj fizycznej karty SIM (gniazdo {0})...'
    'Sim.PhysicalInUse'                         = 'W użyciu: fizyczna karta SIM (gniazdo {0})'
    'Esim.UseEsim'                              = 'Użyj karty eSIM (gniazdo {0})...'
    'Esim.EsimInUse'                            = 'W użyciu: karta eSIM (gniazdo {0})'
    'Sim.OneAtATime'                            = 'Modem używa jednej karty SIM naraz: fizycznej karty SIM (gniazdo {0}) albo karty eSIM (gniazdo {1}). Na karcie SIM włącza się fizyczną kartę SIM, na karcie eSIM kartę eSIM; zmiana na chwilę przerywa połączenie.'
    'Esim.Unnamed'                              = '(bez nazwy)'
    'Esim.NoModem'                              = 'Modem nie jest podłączony.'
    'Esim.NoSlot'                               = 'Używane gniazdo SIM nie zostało jeszcze odczytane.'
    'Esim.NotInUse'                             = 'Profilami karty eSIM można zarządzać tylko wtedy, gdy jej gniazdo jest używane.'
    'Esim.NoLpac'                               = 'lpac nie jest zainstalowany z aplikacją: nie można zarządzać profilami karty eSIM.'
    'Esim.ReadFailed'                           = 'Nie udało się odczytać karty eSIM: {0}'
    'Esim.NotRead'                              = 'Karta eSIM nie została jeszcze odczytana.'
    'Esim.NoProfiles'                           = 'Na karcie eSIM nie ma żadnego profilu.'
    'Esim.ObserveOnly'                          = 'Aplikacja tylko obserwuje: niczego nie zmienia.'
    'Esim.Chip'                                 = 'eUICC: SGP.22 {0}, oprogramowanie układowe {1}, wolne: {2}.'
    'Esim.Notifications'                        = 'Powiadomienia czekające na serwery dostawców: {0}. Zostaną wysłane przy następnym odczycie.'
    'Esim.Operation.ReadEsim'                   = 'Odczytywanie karty eSIM...'
    'Esim.Operation.SelectSimSlot'              = 'Zmiana gniazda SIM...'
    'Esim.Operation.EnableProfile'              = 'Włączanie profilu...'
    'Esim.Operation.DisableProfile'             = 'Wyłączanie profilu...'
    'Esim.Operation.SetProfileNickname'         = 'Zapisywanie nazwy...'
    'Esim.Operation.DeleteProfile'              = 'Usuwanie profilu...'
    'Esim.Operation.DownloadProfile'            = 'Pobieranie profilu: może to potrwać minutę...'
    'Esim.State.Enabled'                        = 'Włączony'
    'Esim.State.Disabled'                       = 'Wyłączony'
    'Esim.State.Unknown'                        = 'Nieznany'
    'Esim.Class.Operational'                    = 'Operator'
    'Esim.Class.Test'                           = 'Testowy'
    'Esim.Class.Provisioning'                   = 'Inicjujący'
    'Esim.Class.Unknown'                        = 'Nieznany'
    'Esim.QrTitle'                              = 'Wybierz obraz kodu QR'
    'Esim.QrKind'                               = 'Obrazy'
    'Esim.QrChosen'                             = 'Obraz kodu QR: {0}. Kod zostanie odczytany na początku pobierania.'
    'Esim.QrMissing'                            = 'Odczyt kodów QR nie jest zainstalowany z aplikacją: wpisz lub wklej kod.'
    'Esim.CodeFirst'                            = 'Najpierw wpisz lub wklej kod aktywacyjny albo wybierz obraz jego kodu QR.'
    'Esim.NicknameInvalid'                      = 'Własna nazwa zajmuje najwyżej 64 bajty - mniej z literami spoza A-Z - i nie zawiera znaków sterujących.'
    'Esim.CopyFailed'                           = 'Nie udało się skopiować numeru EID: zaznacz go i skopiuj klawiszami Ctrl+C.'
    'Blocker.OpenEsim'                          = 'Otwórz eSIM'
    'Confirm.SelectSlotTitle'                   = 'Zmień gniazdo SIM'
    'Confirm.SelectSlot'                        = @'
Użyć gniazda SIM {0}?

Modem zachowuje ten wybór, także po zamknięciu aplikacji i po ponownym uruchomieniu. Połączenie zostanie przerwane podczas zmiany karty SIM. Jeśli w gnieździe jest eSIM i żaden z jej profili nie jest włączony, sieć będzie niedostępna, dopóki nie włączysz któregoś z nich.
'@
    'Confirm.EnableProfileTitle'                = 'Włącz profil eSIM'
    'Confirm.EnableProfile'                     = @'
Włączyć profil "{0}"?

Karta SIM uruchomi się ponownie z tym profilem: połączenie zostanie przerwane na kilka sekund, a potem modem zarejestruje się z nowym profilem. Dotychczas włączony profil zostanie wyłączony.
'@
    'Confirm.DisableProfileTitle'               = 'Wyłącz profil eSIM'
    'Confirm.DisableProfile'                    = @'
Wyłączyć profil "{0}"?

Karta SIM uruchomi się ponownie bez niego: bez włączonego profilu sieć będzie niedostępna, dopóki nie włączysz któregoś z profili.
'@
    'Confirm.DeleteProfileTitle'                = 'Usuń profil eSIM'
    'Confirm.DeleteProfile'                     = @'
Usunąć profil "{0}" z karty eSIM?

Tego nie można cofnąć: aby go odzyskać, dostawca musi podać nowy kod aktywacyjny. Wpisz nazwę profilu, aby potwierdzić.
'@
    'Confirm.Delete'                            = 'Usuń'
    'Confirm.Cancel'                            = 'Anuluj'
    'Result.ReadEsim.Done'                      = 'Karta eSIM odczytana.'
    'Result.ReadEsim.Failed'                    = 'Nie udało się odczytać karty eSIM.'
    'Result.SelectSimSlot.Done'                 = 'Gniazdo SIM zmienione: modem je zachowuje.'
    'Result.SelectSimSlot.Unchanged'            = 'To gniazdo jest już używane.'
    'Result.SelectSimSlot.Failed'               = 'Nie udało się zmienić gniazda SIM.'
    'Result.EnableProfile.Done'                 = 'Profil włączony: karta SIM uruchamia się z nim ponownie.'
    'Result.EnableProfile.Unchanged'            = 'Ten profil jest już włączony.'
    'Result.EnableProfile.Failed'               = 'Nie udało się włączyć profilu.'
    'Result.DisableProfile.Done'                = 'Profil wyłączony: karta SIM uruchamia się ponownie bez niego.'
    'Result.DisableProfile.Unchanged'           = 'Ten profil nie jest włączony.'
    'Result.DisableProfile.Failed'              = 'Nie udało się wyłączyć profilu.'
    'Result.DeleteProfile.Done'                 = 'Profil usunięty.'
    'Result.DeleteProfile.ProfileEnabled'       = 'Włączonego profilu nie można usunąć: najpierw go wyłącz.'
    'Result.DeleteProfile.Failed'               = 'Nie udało się usunąć profilu.'
    'Result.SetProfileNickname.Done'            = 'Nazwa zapisana.'
    'Result.SetProfileNickname.Failed'          = 'Nie udało się zapisać nazwy.'
    'Result.DownloadProfile.Done'               = 'Profil pobrany: włącz go, aby z niego korzystać.'
    'Result.DownloadProfile.Failed'             = 'Nie udało się pobrać profilu.'
    'Result.DownloadProfile.ConfirmationNeeded' = 'Ten kod aktywacyjny wymaga kodu potwierdzenia: dostawca podaje go razem z kodem.'
    'Result.DownloadProfile.BadCode'            = 'To nie jest kod aktywacyjny eSIM.'
    'Result.DownloadProfile.BadCode.Empty'      = 'Najpierw wpisz lub wklej kod aktywacyjny.'
    'Result.DownloadProfile.BadCode.Format'     = 'To nie jest kod aktywacyjny eSIM: taki kod zaczyna się od LPA:1$.'
    'Result.DownloadProfile.BadCode.Address'    = 'Kod aktywacyjny nie wskazuje prawidłowego serwera.'
    'Result.DownloadProfile.BadCode.MatchingId' = 'Matching ID w kodzie aktywacyjnym zawiera niedozwolone znaki.'
    'Result.DownloadProfile.NoQrCode'           = 'Nie udało się odczytać kodu aktywacyjnego z obrazu.'
    'Result.DownloadProfile.NoQrCode.NotImage'  = 'Wybrany plik nie jest obrazem, który aplikacja potrafi odczytać.'
    'Result.DownloadProfile.NoQrCode.TooLarge'  = 'Obraz jest za duży: najwyżej 20 MB i 50 megapikseli.'
    'Result.DownloadProfile.NoQrCode.NoLibrary' = 'Odczyt kodów QR nie jest zainstalowany z aplikacją: wpisz lub wklej kod.'
    'Result.DownloadProfile.NoQrCode.NoCode'    = 'Na obrazie nie znaleziono kodu QR.'
    'Result.NotEuicc'                           = 'Karta eSIM nie jest używaną kartą SIM.'
    'Result.NoLpac'                             = 'lpac nie jest zainstalowany z aplikacją.'
    'Result.UnknownProfile'                     = 'Tego profilu nie ma już na karcie eSIM.'
    'Result.TrialOn'                            = 'Nie teraz: trwa próba trybu sieci.'
    'Result.Timeout'                            = 'Trwało to zbyt długo i zostało przerwane.'
}
