# The app's texts in Portuguese (European, also read by Brazilian users): the same keys as en.psd1.
# Placeholders {0}, {1}... are filled in that order; a translation keeps the same ones. Saved as
# UTF-8 with a byte order mark, as every language's file.
@{
    # Why the connection is where it is (Resolve-ConnectionState's reasons).
    'Reason.NoDevice'              = 'Não foi encontrado nenhum modem ligado por USB.'
    'Reason.NoDriver'              = 'A porta AT do modem não tem controlador: a aplicação não consegue comunicar com o modem até o controlador ser instalado.'
    'Reason.DeviceProblem'         = 'O Windows indica um problema com a porta AT do modem.'
    'Reason.PortInUse'             = 'Outro programa está a usar a porta AT do modem.'
    'Reason.PortFailed'            = 'Não é possível abrir a porta AT do modem.'
    'Reason.SimUnknown'            = 'A ler o SIM.'
    'Reason.NoPin'                 = 'O SIM aguarda o PIN.'
    'Reason.PinForOtherSim'        = 'O PIN guardado pertence a outro SIM: introduza o PIN deste SIM.'
    'Reason.SimNotIdentified'      = 'Não é possível identificar o SIM, por isso o PIN guardado não lhe é enviado.'
    'Reason.PinUnconfirmed'        = 'A última introdução do PIN ficou sem resposta, e a aplicação nunca tenta duas vezes: introduza o PIN novamente.'
    'Reason.LastAttempt'           = 'Resta apenas uma tentativa do PIN, e a aplicação não a usa: desbloqueie o SIM num telefone.'
    'Reason.PukRequired'           = 'O SIM está bloqueado e precisa do PUK: desbloqueie-o num telefone. A aplicação nunca introduz um PUK.'
    'Reason.NoSim'                 = 'Não há nenhum SIM no modem.'
    'Reason.SimFailure'            = 'O SIM não funciona.'
    'Reason.SimOther'              = 'O SIM aguarda um código que a aplicação não trata.'
    'Reason.SimBusy'               = 'O SIM está ocupado; a aplicação aguarda.'
    'Reason.FccLocked'             = 'O modem está bloqueado pelo fabricante do portátil (bloqueio FCC): o rádio fica desligado.'
    'Reason.NotRegistered'         = 'Não registado numa rede.'
    'Reason.NotSearching'          = 'Não registado e sem procurar uma rede.'
    'Reason.Searching'             = 'À procura de uma rede.'
    'Reason.Denied'                = 'A rede recusou o registo.'
    'Reason.Unknown'               = 'Não registado; o motivo é desconhecido.'
    'Reason.EmergencyOnly'         = 'Apenas chamadas de emergência.'
    'Reason.ContextUnknown'        = 'A ler a ligação de dados.'
    'Reason.ApnPasswordUnreadable' = 'Não é possível ler a palavra-passe do APN guardada: introduza-a novamente.'
    'Reason.ApnNeeded'             = 'A rede não deu acesso à internet com um APN vazio: introduza o APN do seu operador.'
    'Reason.NoAddress'             = 'A ligação de dados não tem endereço IPv4.'
    'Reason.AdapterDisabled'       = 'O adaptador de rede do modem está desativado.'
    'Reason.NoAdapter'             = 'O adaptador de rede do modem está em falta.'
    'Reason.NotElevated'           = 'O adaptador de rede só pode ser configurado com direitos de administrador: inicie a aplicação como administrador.'
    'Reason.DataPathFailed'        = 'A ligação está ativa, mas não passa tráfego.'
    'Reason.DohServerUnresolved'   = 'O nome do servidor DNS over HTTPS ainda não foi resolvido: a aplicação continua a tentar e, até lá, deixa o adaptador de rede como o modem o configurou.'
    'Reason.DohNeedsServers'       = 'O DNS cifrado precisa de servidores DNS à sua escolha: os do operador não suportam DNS over HTTPS. O adaptador de rede não é configurado até lá.'
    'Reason.DohUnavailable'        = 'Este Windows não consegue cifrar o DNS num só adaptador - o DNS over HTTPS requer o Windows 11: desative o DNS cifrado. O adaptador de rede não é configurado até lá.'
    'Reason.DohTemplateMissing'    = 'O Windows não conhece nenhum modelo DNS over HTTPS para um servidor DNS das definições: indique um, ou escolha servidores que ele conheça. O adaptador de rede não é configurado até lá.'
    'Reason.Connected'             = 'Ligado.'
    'Reason.Other'                 = 'Não registado ({0}).'
    'Reason.Working'               = 'A tratar da ligação.'
    'Reason.NoNetworkForMode'      = 'Nenhuma rede encontrada com {0}. Nenhum reinício vai encontrar uma: escolha um modo de rede mais amplo.'
    'Reason.NoNetworkForModeBands' = 'Nenhuma rede encontrada com {0} nas bandas LTE escolhidas. Nenhum reinício vai encontrar uma: escolha um modo de rede mais amplo.'
    'Reason.Withheld'              = 'A aplicação apenas observa, por isso não dá o passo seguinte: {0}'

    # What the next step does, while the connection is on its way; and the same after a colon.
    'Action.OpenPort'                = 'A abrir a porta AT do modem.'
    'Action.Initialize'              = 'A aguardar a resposta do modem.'
    'Action.EnterPin'                = 'A introduzir o PIN guardado.'
    'Action.RadioOn'                 = 'A ligar o rádio.'
    'Action.AutoRegister'            = 'A selecionar a rede automaticamente.'
    'Action.DefineContext'           = 'A configurar a ligação de dados.'
    'Action.ActivateContext'         = 'A configurar a ligação de dados.'
    'Action.DeactivateContext'       = 'A configurar a ligação de dados.'
    'Action.ConfigureAdapter'        = 'A configurar o adaptador de rede.'
    'Action.ApplyNetworkMode'        = 'A definir o modo de rede.'
    'ActionInline.OpenPort'          = 'abrir a porta AT do modem.'
    'ActionInline.Initialize'        = 'aguardar a resposta do modem.'
    'ActionInline.EnterPin'          = 'introduzir o PIN guardado.'
    'ActionInline.RadioOn'           = 'ligar o rádio.'
    'ActionInline.AutoRegister'      = 'selecionar a rede automaticamente.'
    'ActionInline.DefineContext'     = 'configurar a ligação de dados.'
    'ActionInline.ActivateContext'   = 'configurar a ligação de dados.'
    'ActionInline.DeactivateContext' = 'configurar a ligação de dados.'
    'ActionInline.ConfigureAdapter'  = 'configurar o adaptador de rede.'
    'ActionInline.ApplyNetworkMode'  = 'definir o modo de rede.'

    # The network modes.
    'Mode.Automatic'               = '4G + 5G'
    'Mode.LteOnly'                 = 'Apenas 4G'
    'Mode.NrOnly'                  = 'Apenas 5G (SA)'
    'Mode.NotManaged'              = 'Como está no modem'
    'Mode.Other'                   = 'modo {0}'
    'ModeProblem.NotKept'          = 'O modem não mantém o modo de rede tal como foi escrito; a aplicação não o volta a escrever.'
    'ModeProblem.NoSupportedBand'  = 'O modem não suporta nenhuma das bandas escolhidas para uma das suas RAT.'
    'ModeProblem.ModeUnsupported'  = 'O modem não suporta este modo de rede.'

    # The outcome of the user's commands: Result.<command>.<result>, or Result.<result> for any.
    'Result.ConnectNow.Done'                = 'A verificar a ligação agora.'
    'Result.SaveSettings.Done'              = 'Definições guardadas.'
    'Result.SaveSimPin.Done'                = 'PIN guardado: a aplicação introduz o PIN uma vez quando o SIM o pede.'
    'Result.SaveSimPin.SimNotIdentified'    = 'Não é possível identificar o SIM: o PIN não foi guardado.'
    'Result.ForgetSimPin.Done'              = 'O PIN guardado foi eliminado.'
    'Result.DisableSimPin.Disabled'         = 'O SIM já não pede o PIN.'
    'Result.DisableSimPin.AlreadyOff'       = 'O pedido de PIN do SIM já estava desativado.'
    'Result.DisableSimPin.PinRejected'      = 'PIN errado: o SIM continua a pedi-lo.'
    'Result.DisableSimPin.LastAttempt'      = 'Resta apenas uma tentativa do PIN: nada foi enviado.'
    'Result.DisableSimPin.SimNotReady'      = 'O SIM não está pronto: nada foi enviado.'
    'Result.DisableSimPin.Failed'           = 'Não foi possível alterar o pedido de PIN do SIM.'
    'Result.UnlockFcc.Restarted'            = 'Desbloqueio enviado: o modem está a reiniciar.'
    'Result.UnlockFcc.NotLocked'            = 'O modem não está bloqueado: nada foi escrito.'
    'Result.UnlockFcc.Unknown'              = 'Não é possível ler o bloqueio: nada foi escrito.'
    'Result.UnlockFcc.Failed'               = 'O desbloqueio parou antes do reinício.'
    'Result.UnlockFcc.PortLost'             = 'O modem desapareceu do USB durante o desbloqueio.'
    'Result.EnableAdapter.Done'             = 'Adaptador de rede ativado.'
    'Result.SetNetworkMode.Applied'         = 'Modo de rede enviado: o modem está a registar-se novamente. O modo é mantido assim que o modem encontrar uma rede com ele.'
    'Result.SetNetworkMode.Unchanged'       = 'O modem já tem este modo de rede: é mantido.'
    'Result.SetNetworkMode.Done'            = 'A aplicação deixou de gerir o modo de rede: o modem mantém o que tem.'
    'Result.SetNetworkMode.ModeUnsupported' = 'O modem não suporta este modo de rede: nada foi escrito.'
    'Result.SetNetworkMode.NoSupportedBand' = 'O modem não suporta nenhuma das bandas escolhidas para uma das suas RAT: nada foi escrito.'
    'Result.SetNetworkMode.Unknown'         = 'Não é possível ler o modo de rede do modem: nada foi escrito.'
    'Result.CheckDriverPackage.Verified'    = 'Pacote do controlador verificado: uma versão que a aplicação conhece.'
    'Result.CheckDriverPackage.Signed'      = 'Pacote do controlador verificado: assinado pela Microsoft, numa versão que a aplicação não conhece.'
    'Result.CheckDriverPackage.Refused'     = 'O pacote do controlador não pode ser instalado: o separador Controlador indica porquê.'
    'Result.CheckDriverPackage.NoPackage'   = 'Não foi escolhido nenhum pacote do controlador.'
    'Result.CheckDriverPackage.Failed'      = 'Não é possível ler o pacote do controlador.'
    'Result.InstallDriver.Done'             = 'Controlador instalado: a aplicação abre a porta AT do modem assim que o Windows a iniciar.'
    'Result.InstallDriver.RestartNeeded'    = 'Controlador instalado: o Windows precisa de reiniciar para concluir.'
    'Result.InstallDriver.NoDevice'         = 'Controlador adicionado ao Windows, mas nenhum dispositivo o adotou: é usado quando o modem for ligado, a menos que o Windows dê prioridade a outro controlador.'
    'Result.InstallDriver.Unconfirmed'      = 'Não instalado: uma versão que a aplicação não conhece precisa da sua confirmação.'
    'Result.InstallDriver.NoPackage'        = 'Escolha primeiro um pacote do controlador.'
    'Result.InstallDriver.DriverWorking'    = 'A porta AT já tem um controlador a funcionar: nada foi instalado.'
    'Result.InstallDriver.TimedOut'         = 'O Windows não concluiu a instalação do controlador a tempo: foi interrompida.'
    'Result.InstallDriver.Failed'           = 'O Windows não instalou o controlador.'
    'Result.UninstallDriver.Done'           = 'Controlador desinstalado: a aplicação não consegue comunicar com o modem até o controlador ser instalado novamente.'
    'Result.UninstallDriver.RestartNeeded'  = 'Controlador desinstalado: o Windows precisa de reiniciar para concluir.'
    'Result.UninstallDriver.NoDriver'       = 'A porta AT não tem nenhum controlador que a aplicação possa desinstalar.'
    'Result.UninstallDriver.TrialOn'        = 'Não desinstalado: há um modo de rede em teste, e só pela porta AT é possível repor o anterior.'
    'Result.UninstallDriver.TimedOut'       = 'O Windows não concluiu a desinstalação do controlador a tempo: foi interrompida.'
    'Result.UninstallDriver.Failed'         = 'O Windows não desinstalou o controlador.'
    'Result.NotElevated'                    = 'Isso requer direitos de administrador.'
    'Result.Refused'                        = 'Não disponível enquanto a aplicação apenas observa.'
    'Result.NoModem'                        = 'O modem não está ligado ao computador.'
    'Result.PortLost'                       = 'O modem desapareceu do USB durante o comando.'
    'Result.Failed'                         = 'Não funcionou.'
    'Result.Other'                          = '{0}: {1}.'
    'Result.AttemptsLeft'                   = 'Tentativas restantes: {0}.'
    'Result.Restarting'                     = 'O monitor está a reiniciar: tente novamente daqui a pouco.'

    # The headline.
    'Tone.Online'         = 'Ligado'
    'Tone.Working'        = 'A ligar'
    'Tone.Recovering'     = 'A recuperar'
    'Tone.Attention'      = 'Ação necessária'
    'Tone.Offline'        = 'Sem modem'
    'Tone.Stopped'        = 'Sem monitorização'
    'Title.ConnectionLost' = 'Ligação perdida'
    'Title.NoNetwork'     = 'Sem rede'
    'Title.NotConnected'  = 'Sem ligação'

    # Recovery: what fails, and what each step does - also after a colon.
    'Check.H1'          = 'O modem não está presente no USB.'
    'Check.H2'          = 'O modem não responde.'
    'Check.H3'          = 'O SIM não está pronto.'
    'Check.H4'          = 'Não registado numa rede.'
    'Check.H5'          = 'A ligação de dados está inativa.'
    'Check.H6'          = 'O adaptador de rede não está configurado.'
    'Check.H7'          = 'Não passa tráfego.'
    'Check.Other'       = 'A ligação está inativa.'
    'Step.R1'           = 'A configurar novamente o adaptador de rede.'
    'Step.R2'           = 'A reiniciar a ligação de dados.'
    'Step.R3'           = 'A registar o modem novamente na rede.'
    'Step.R4'           = 'A desligar e ligar o rádio.'
    'Step.R5'           = 'A reiniciar o modem.'
    'Step.R6'           = 'A reiniciar o dispositivo USB do modem.'
    'StepInline.R1'     = 'configurar novamente o adaptador de rede.'
    'StepInline.R2'     = 'reiniciar a ligação de dados.'
    'StepInline.R3'     = 'registar o modem novamente na rede.'
    'StepInline.R4'     = 'desligar e ligar o rádio.'
    'StepInline.R5'     = 'reiniciar o modem.'
    'StepInline.R6'     = 'reiniciar o dispositivo USB do modem.'
    'Recovery.Waiting'  = '{0} Os passos de recuperação não resultaram: recomeçam às {1}.'
    'Recovery.Slow'     = '{0} A recuperação falhou {1} vezes: a aplicação tenta novamente às {2}.'
    'Recovery.Withheld' = '{0} A aplicação apenas observa, por isso não dá o passo de recuperação: {1}'

    # The tray.
    'Tray.Tooltip'        = 'FM350-GL: {0}'
    'Tray.Open'           = 'Abrir'
    'Tray.CheckNow'       = 'Verificar agora'
    'Tray.NetworkMode'    = 'Modo de rede'
    'Tray.NetworkModeNow' = 'Modo de rede: {0}'
    'Tray.Exit'           = 'Sair'
    'Tray.Update'         = 'Versão {0} disponível...'

    # What unblocks the connection.
    'Blocker.UseAutomatic'  = 'Usar {0}, todas as bandas'
    'Blocker.SaveApn'       = 'Guardar APN'
    'Blocker.SavePassword'  = 'Guardar palavra-passe'
    'Blocker.StorePin'      = 'Guardar PIN'
    'Blocker.EnableAdapter' = 'Ativar adaptador'
    'Blocker.Unlock'        = 'Desbloquear...'
    'Blocker.InstallDriver' = 'Instalar o controlador...'
    'Blocker.OpenSettings'  = 'Abrir as definições'
    'Blocker.ObserveOnly'   = 'A aplicação apenas observa: não altera nada.'
    'Blocker.NeedsAdmin'    = 'Ativá-lo requer direitos de administrador.'
    'Blocker.UnlockNote'    = 'O desbloqueio escreve na memória não volátil do modem: a aplicação pergunta antes de o fazer.'
    'Blocker.AttemptsLeft'  = 'Tentativas restantes: {0}.'

    # The SIM tab.
    'Sim.Ready'          = 'Pronto'
    'Sim.PinRequired'    = 'Aguarda o PIN'
    'Sim.PukRequired'    = 'Bloqueado: precisa do PUK'
    'Sim.Absent'         = 'Sem SIM'
    'Sim.Busy'           = 'Ocupado'
    'Sim.Failure'        = 'Não funciona'
    'Sim.Other'          = 'Aguarda outro código'
    'Sim.Unknown'        = 'Desconhecido'
    'Sim.State'          = 'SIM: {0}'
    'Sim.StateAttempts'  = 'SIM: {0} - tentativas de PIN restantes: {1}'
    'Sim.RequestOn'      = 'Pedido de PIN ao ligar: ativado'
    'Sim.RequestOff'     = 'Pedido de PIN ao ligar: desativado'
    'Sim.RequestUnknown' = 'Pedido de PIN ao ligar: desconhecido'
    'Sim.Stored'         = 'Há um PIN guardado para este SIM.'
    'Sim.NotStored'      = 'Não há nenhum PIN guardado.'
    'Sim.Rejected'       = 'O PIN guardado foi rejeitado e eliminado: a aplicação nunca mais o tenta.'

    # The network tab.
    'Bands.Every'       = 'todas as bandas'
    'Bands.EveryBut'    = 'todas as bandas exceto {0}'
    'Bands.None'        = 'nenhuma'
    'Network.Current'   = 'O modem agora: {0}.'
    'Network.Lte'       = 'LTE: {0}.'
    'Network.Nr'        = 'NR: {0}.'
    'Network.NotRead'   = 'O modo de rede do modem ainda não foi lido.'
    'Network.Trial'     = 'A experimentar {0}: se o modem não encontrar nenhuma rede com ele até às {1}, volta ao que tinha.'
    'Network.Reverted'  = 'Às {0} o modem não tinha encontrado nenhuma rede com {1}: voltou ao que tinha.'
    'Network.Kept'      = 'Às {0} o modem registou-se com {1}: o modo é mantido.'
    'Network.Missing'   = 'O modem não inclui {0}, embora lhe tenha sido pedido: usa as outras bandas escolhidas.'
    'Network.ChooseBand' = 'Escolha pelo menos uma banda {0}, ou todas as bandas.'

    # Encrypted DNS, in the connection tab.
    'Dns.Unavailable'          = 'O DNS cifrado não está disponível neste Windows: o DNS over HTTPS num só adaptador requer o Windows 11.'
    'Dns.On'                   = 'O DNS cifrado está ativado: {0}.'
    'Dns.Waiting'              = 'O DNS cifrado aguarda o endereço do seu servidor: entretanto, não é definido nenhum servidor DNS.'
    'Dns.Off'                  = 'O DNS cifrado está desativado.'
    'Dns.Advertised'           = 'A rede também fornece servidores DNS IPv6 ({0}), que o Windows pode usar sem encriptação.'
    'Dns.LookupFailed'         = 'Não é possível resolver {0}; a aplicação continua a tentar.'
    'Dns.LookingUp'            = 'A resolver {0}...'
    'Dns.LookedUp'             = 'O seu servidor, {0}, foi resolvido às {1}.'
    'Dns.LookedUpNext'         = 'O seu servidor, {0}, foi resolvido às {1}; nova resolução às {2}.'
    'Dns.LookedUpOperator'     = 'O seu servidor, {0}, foi resolvido às {1} através do DNS do operador, em texto simples.'
    'Dns.LookedUpOperatorNext' = 'O seu servidor, {0}, foi resolvido às {1} através do DNS do operador, em texto simples; nova resolução às {2}.'
    'Dns.NotAvailableHere'     = 'O DNS cifrado não está disponível neste Windows.'
    'Dns.NoTemplate'           = 'O Windows não conhece nenhum modelo DNS over HTTPS para {0}: indique um.'

    # The settings: why a value is refused (ConvertTo-AppSetting's issues).
    'Setting.Rejected'         = '{0} {1}; é usado o valor predefinido.'
    'Setting.Unknown'          = 'A definição desconhecida «{0}» é ignorada.'
    'Setting.Unreadable'       = 'Não é possível ler o ficheiro de definições; são usados os valores predefinidos.'
    'Setting.DohNeedsServers'  = 'DnsOverHttps precisa de DnsServers, ou de um DohTemplate que indique o servidor: os servidores do operador não suportam DoH, e não é definido nenhum servidor DNS até haver um.'
    'Setting.TemplateAddress'  = 'DohTemplate indica o endereço {0}, por isso só pode servir esse servidor; é usado o valor predefinido.'
    'Rule.Text'                = 'deve ser ASCII imprimível, sem aspas duplas nem espaços no início ou no fim'
    'Rule.TextQuotes'          = 'deve ser ASCII imprimível, sem aspas duplas'
    'Rule.OneOf'               = 'deve ser um destes valores: {0}'
    'Rule.EmptyOrOneOf'        = 'deve estar vazio ou ser um destes valores: {0}'
    'Rule.Addresses'           = 'deve ser uma lista de endereços IP'
    'Rule.Number'              = 'deve ser um número inteiro de {0} a {1}'
    'Rule.Minutes'             = 'deve ser um número inteiro de minutos de {0} a {1}'
    'Rule.Bool'                = 'deve ser true ou false'
    'Rule.Https'               = 'deve estar vazio ou ser um endereço https sem espaços, aspas nem credenciais'
    'Rule.Bands'               = 'deve ser uma lista de números de banda distintos de {0} a {1}'

    # The Driver tab.
    'DriverProblem.NoInf'        = 'não contém nenhum controlador (nenhum ficheiro INF)'
    'DriverProblem.NotForModem'  = 'nenhum dos seus controladores se destina à porta AT deste modem'
    'DriverProblem.NoCatalog'    = 'o seu controlador não tem catálogo de assinatura'
    'DriverProblem.NotWhql'      = 'o seu catálogo não está assinado pela Microsoft (WHQL)'
    'DriverProblem.NotInCatalog' = 'o seu ficheiro INF não é o que o catálogo garante: foi alterado ou está danificado'
    'DriverProblem.NotTrusted'   = 'não é possível verificar a sua assinatura'
    'Driver.Present'             = 'A porta AT do modem tem o seu controlador.'
    'Driver.PresentWhat'         = 'A porta AT do modem tem o seu controlador: {0}.'
    'Driver.NoDriver'            = 'A porta AT do modem não tem controlador: a aplicação não consegue comunicar com o modem.'
    'Driver.Problem'             = 'O Windows indica um problema com a porta AT do modem: instalar novamente o controlador pode resolvê-lo.'
    'Driver.Absent'              = 'Nenhum modem no USB. Um controlador instalado agora é usado assim que o modem for ligado.'
    'Driver.NotLooked'           = 'A porta AT do modem ainda não foi examinada.'
    'Driver.Source'              = 'A aplicação não inclui o controlador do modem: não tem licença para o redistribuir. Transfira uma cópia e depois escolha-a aqui: a aplicação verifica que a Microsoft a assinou (WHQL) para este modem, e nunca executa nenhum programa que ela contenha.'
    'Driver.SourceCopy'          = 'A aplicação não inclui o controlador do modem: não tem licença para o redistribuir. Uma cópia do controlador da MediaTek, {0}, é publicada por um terceiro, {1}, como {2}. Transfira-a e depois escolha-a aqui: a aplicação verifica que a Microsoft a assinou (WHQL) para este modem, e nunca executa nenhum programa que ela contenha.'
    'Driver.Checking'            = 'A verificar o pacote do controlador...'
    'Driver.Installing'          = 'A instalar o controlador: o Windows pode demorar um minuto.'
    'Driver.Uninstalling'        = 'A desinstalar o controlador...'
    'Driver.Verified'            = '{0}: {1}, uma versão que a aplicação conhece, assinada pela Microsoft (WHQL) para este modem.'
    'Driver.Signed'              = '{0}: {1}, assinado pela Microsoft (WHQL) para este modem, mas numa versão que a aplicação não conhece: pergunta antes de o instalar.'
    'Driver.Refused'             = '{0} não pode ser instalado: {1}.'
    'Driver.ObserveOnly'         = 'A aplicação apenas observa: não altera nada.'
    'Driver.NeedsAdmin'          = 'Instalar ou desinstalar um controlador requer direitos de administrador: inicie a aplicação como administrador.'
    'Driver.Trial'               = 'Há um modo de rede em teste: o controlador pode ser desinstalado quando o teste terminar.'
    'Driver.Install'             = 'Instalar'
    'Driver.InstallConfirm'      = 'Instalar...'
    'Driver.ChooseTitle'         = 'Escolha o pacote do controlador transferido'
    'Driver.FileKind'            = 'Pacote do controlador'

    # The window: the connection, its notes, the signal, the footer.
    'Window.Restarting'      = 'O monitor parou e está a reiniciar. A ligação fica como está.'
    'Window.NotResponding'   = 'O monitor não responde. A ligação fica como está.'
    'Window.Starting'        = 'A iniciar.'
    'Window.Simulated'       = 'Modo de desenvolvimento: um modem simulado (cenário {0}).'
    'Window.ObserveOnly'     = 'A aplicação apenas observa: não altera nada no modem nem no sistema.'
    'Window.SettingsPending' = 'A ligação de dados está ativa com outras definições: as novas aplicam-se na próxima ligação.'
    'Window.SettingsFile'    = 'Ficheiro de definições: {0}'
    'Window.Modems'          = '{0} modems encontrados: a aplicação usa o que está em {1}.'
    'Window.Recovered'       = 'Ligação recuperada às {0}, depois de {1}'
    'Window.NrAvailable'     = '{0}, 5G disponível'
    'Window.NothingMeasured' = 'Nada medido.'
    'Window.PasswordStored'  = 'Há uma palavra-passe guardada.'
    'Window.NoPassword'      = 'Não há nenhuma palavra-passe guardada.'
    'Window.PinFirst'        = 'Introduza primeiro o PIN do SIM: para o remover é preciso o PIN.'
    'Cell.Serving'           = 'Servidora'
    'Cell.Neighbour'         = 'Vizinha'
    'Carrier.Primary'        = 'Primária'
    'Carrier.Active'         = 'Ativa'
    'Carrier.Inactive'       = 'Inativa'
    'Footer.Port'            = 'Porta AT {0}'
    'Footer.PortClosed'      = 'Porta AT fechada'
    'Footer.Updated'         = 'atualizado às {0}'
    'Footer.PathChecked'     = 'caminho de dados verificado às {0}'
    'Footer.PathFailed'      = 'caminho de dados falhou às {0}'
    'Footer.PathPending'     = 'caminho de dados ainda não verificado às {0}'
    'Footer.NotElevated'     = 'sem direitos de administrador'
    'Footer.Version'         = 'versão {0}'

    # The confirmations: their titles, and what they say.
    'Confirm.UnlockTitle'          = 'Desbloquear o modem'
    'Confirm.Unlock'               = @'
Desbloquear o modem?

Isto escreve na memória não volátil do modem e levanta uma restrição que o fabricante do portátil definiu para a certificação do rádio. É feito sob a sua responsabilidade, e pode não funcionar em todos os módulos.

O modem reinicia a seguir.
'@
    'Confirm.DisablePinTitle'      = 'Remover o PIN do SIM'
    'Confirm.DisablePin'           = @'
Remover o PIN do SIM?

Isto altera o cartão SIM, não a aplicação: o SIM deixa de pedir o PIN, neste modem ou em qualquer telefone. Um PIN errado gasta uma das suas tentativas.
'@
    'Confirm.UnknownDriverTitle'   = 'Instalar uma versão desconhecida do controlador'
    'Confirm.UnknownDriver'        = @'
Instalar uma versão do controlador que a aplicação não conhece?

A Microsoft assinou este pacote (WHQL) para a porta AT do modem, por isso o Windows aceita-o; mas não é uma versão que a aplicação conheça.

O Windows instala-o em todos os dispositivos a que se aplica.
'@
    'Confirm.UninstallDriverTitle' = 'Desinstalar o controlador'
    'Confirm.UninstallDriver'      = @'
Desinstalar o controlador da porta AT do modem?

O Windows remove-o das portas série do modem e do arquivo de controladores. A ligação de dados mantém-se ativa, mas a aplicação não consegue comunicar com o modem, nem vigiar a ligação, até o controlador ser instalado novamente.
'@

    # The window's fixed texts (MainWindow.xaml).
    'Xaml.CheckNow'          = 'Verificar agora'
    'Xaml.SignalTab'         = 'Sinal'
    'Xaml.Cells'             = 'Células'
    'Xaml.Cell'              = 'Célula'
    'Xaml.Band'              = 'Banda'
    'Xaml.Channel'           = 'Canal'
    'Xaml.Bandwidth'         = 'Largura de banda'
    'Xaml.CarrierAggregation' = 'Agregação de portadoras'
    'Xaml.Carrier'           = 'Portadora'
    'Xaml.State'             = 'Estado'
    'Xaml.BandwidthDlUl'     = 'Largura de banda DL/UL'
    'Xaml.ModulationDlUl'    = 'Modulação DL/UL'
    'Xaml.StorePin'          = 'Guardar PIN'
    'Xaml.ForgetPin'         = 'Esquecer o PIN guardado'
    'Xaml.DisablePin'        = 'Remover o PIN do SIM...'
    'Xaml.PinNote'           = 'Um PIN guardado fica cifrado para o seu utilizador do Windows, associado ao SIM a que pertence. A aplicação introduz o PIN uma vez quando esse SIM o pede - nunca duas vezes, nunca com uma só tentativa restante, e nunca um PUK.'
    'Xaml.NetworkTab'        = 'Rede'
    'Xaml.NetworkMode'       = 'Modo de rede'
    'Xaml.Apply'             = 'Aplicar'
    'Xaml.Undo'              = 'Desfazer alterações'
    'Xaml.ModeNote'          = 'O modem mantém o modo de rede e as bandas, também depois de a aplicação terminar. Um modo é primeiro experimentado: se o modem não encontrar nenhuma rede com ele, volta ao que tinha.'
    'Xaml.LteAll'            = 'LTE: todas as bandas'
    'Xaml.NrAll'             = 'NR: todas as bandas'
    'Xaml.ConnectionTab'     = 'Ligação'
    'Xaml.ApnTip'            = 'Vazio: o da sua subscrição.'
    'Xaml.PdpType'           = 'Tipo de PDP'
    'Xaml.Authentication'    = 'Autenticação'
    'Xaml.AuthNone'          = 'Nenhuma'
    'Xaml.User'              = 'Utilizador'
    'Xaml.Password'          = 'Palavra-passe'
    'Xaml.ClearPassword'     = 'Eliminar a palavra-passe guardada'
    'Xaml.DnsServers'        = 'Servidores DNS'
    'Xaml.DnsTip'            = 'Separados por vírgulas. Vazio: os do operador.'
    'Xaml.EncryptedDns'      = 'DNS cifrado'
    'Xaml.Doh'               = 'DNS over HTTPS para os servidores acima, ou para o do modelo - nunca em texto simples'
    'Xaml.DohTemplate'       = 'Modelo DoH'
    'Xaml.DohTemplateTip'    = 'Vazio: o modelo que o Windows conhece para cada servidor. Caso contrário, um endereço https para todos; sem servidores DNS, o seu nome ou endereço é o servidor.'
    'Xaml.RefreshBefore'     = 'Resolver o seu servidor a cada'
    'Xaml.RefreshAfter'      = 'minutos, quando não é indicado nenhum servidor DNS: o nome do modelo é o servidor.'
    'Xaml.Metric'            = 'Métrica da interface'
    'Xaml.MetricNote'        = '500 mantém o modem como ligação de reserva; um valor baixo torna-o a ligação preferida.'
    'Xaml.Updates'           = 'Atualizações'
    'Xaml.UpdateCheck'       = 'Procurar uma versão mais recente uma vez em cada arranque'
    'Xaml.Save'              = 'Guardar'
    'Xaml.DriverTab'         = 'Controlador'
    'Xaml.OpenPage'          = 'Abrir a página de transferência'
    'Xaml.ChoosePackage'     = 'Escolher o pacote transferido...'
    'Xaml.Install'           = 'Instalar'
    'Xaml.UninstallDriver'   = 'Desinstalar o controlador...'

    # Starting the app at sign-in, in the connection tab.
    'Xaml.Startup'                    = 'Arranque'
    'Xaml.StartAtLogon'               = 'Iniciar a aplicação na área de notificação ao iniciar sessão no Windows'
    'Startup.NotInstalled'            = 'Só a aplicação instalada pode iniciar ao iniciar sessão no Windows.'
    'Startup.NeedsAdmin'              = 'Para o alterar são necessários direitos de administrador.'
    'Startup.ObserveOnly'             = 'A aplicação apenas observa: não altera nada.'
    'Result.SetStartAtLogon.Enabled'  = 'A aplicação passa a iniciar ao iniciar sessão no Windows.'
    'Result.SetStartAtLogon.Disabled' = 'A aplicação deixa de iniciar ao iniciar sessão no Windows.'
    'Result.SetStartAtLogon.NoTask'   = 'Só a aplicação instalada pode iniciar ao iniciar sessão no Windows: nada foi alterado.'
}
