@{
    RootModule           = 'FibocomFm350.psm1'
    ModuleVersion        = '0.1.0'
    GUID                 = '5b026e47-4ab2-42df-b52d-b3b1f15999d8'
    Author               = 'Francesco Stimola'
    Copyright            = '(c) 2026 Francesco Stimola. Licensed under AGPL-3.0-or-later.'
    Description          = 'Core library of fibocom-fm350-gl-windows-gui: AT protocol, parsing and connection logic for the Fibocom FM350-GL 5G modem.'
    PowerShellVersion    = '7.6'
    CompatiblePSEditions = @('Core')
    FunctionsToExport    = @(
        'Close-AtChannel'
        'ConvertFrom-AtCarrierAggregation'
        'ConvertFrom-AtCellInfo'
        'ConvertFrom-AtContextActivation'
        'ConvertFrom-AtContextAddress'
        'ConvertFrom-AtContextAuthentication'
        'ConvertFrom-AtContextDefinition'
        'ConvertFrom-AtContextParameter'
        'ConvertFrom-AtDnsServer'
        'ConvertFrom-AtFacilityLock'
        'ConvertFrom-AtFccLock'
        'ConvertFrom-AtIccid'
        'ConvertFrom-AtIdentity'
        'ConvertFrom-AtOperator'
        'ConvertFrom-AtPinRetry'
        'ConvertFrom-AtPinCounter'
        'ConvertFrom-AtRegistration'
        'ConvertFrom-AtSignalQuality'
        'ConvertFrom-AtSimState'
        'ConvertFrom-AtTemperature'
        'ConvertFrom-Earfcn'
        'ConvertFrom-GtactBandCode'
        'ConvertFrom-MeasurementIndex'
        'ConvertFrom-NrArfcn'
        'ConvertTo-AppSetting'
        'ConvertTo-GtactBandCode'
        'ConvertTo-RedactedText'
        'Disable-SimPin'
        'Export-AppSetting'
        'Get-ApnPassword'
        'Get-AtCommandTimeout'
        'Get-ModemAdapterState'
        'Get-ModemObservation'
        'Get-ModemPnpRecord'
        'Get-SimPin'
        'Import-AppSetting'
        'Import-AtFixture'
        'Initialize-AtChannel'
        'Invoke-AtCommand'
        'Invoke-FccUnlock'
        'Invoke-ModemConnect'
        'New-AtChannel'
        'New-SimulatedModem'
        'Open-SerialAtTransport'
        'Receive-AtUrc'
        'Remove-ApnPassword'
        'Remove-SimPin'
        'Resolve-AdapterConfiguration'
        'Resolve-AtLine'
        'Resolve-ConnectionState'
        'Resolve-FccLock'
        'Resolve-ModemUsbDevice'
        'Resolve-SimPinAction'
        'Save-ApnPassword'
        'Save-SimPin'
        'Set-ModemAdapterConfiguration'
        'Set-SimPinAttempt'
        'Split-AtText'
        'Write-AppLog'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('Fibocom', 'FM350', '5G', 'LTE', 'Modem', 'Windows')
            LicenseUri = 'https://github.com/francesco-stimola/fibocom-fm350-gl-windows-gui/blob/main/LICENSE'
            ProjectUri = 'https://github.com/francesco-stimola/fibocom-fm350-gl-windows-gui'
        }
    }
}
