@{
    RootModule           = 'FibocomFm350.psm1'
    ModuleVersion        = '1.1.0'
    GUID                 = '5b026e47-4ab2-42df-b52d-b3b1f15999d8'
    Author               = 'Francesco Stimola'
    Copyright            = '(c) 2026 Francesco Stimola. Licensed under AGPL-3.0-or-later.'
    Description          = 'Core library of fibocom-fm350-gl-windows-gui: AT protocol, parsing and connection logic for the Fibocom FM350-GL 5G modem.'
    PowerShellVersion    = '7.6'
    CompatiblePSEditions = @('Core')
    FunctionsToExport    = @(
        'Close-AtChannel'
        'Close-ModemWorker'
        'Close-ModemWorkerLink'
        'ConvertFrom-AtCarrierAggregation'
        'ConvertFrom-AtCellInfo'
        'ConvertFrom-AtContextActivation'
        'ConvertFrom-AtContextAddress'
        'ConvertFrom-AtContextAuthentication'
        'ConvertFrom-AtContextDefinition'
        'ConvertFrom-AtContextParameter'
        'ConvertFrom-AtDnsServer'
        'ConvertFrom-AtFacilityLock'
        'ConvertFrom-AtFccLock'
        'ConvertFrom-AtIccid'
        'ConvertFrom-AtIdentity'
        'ConvertFrom-AtMessageList'
        'ConvertFrom-AtMessageStorage'
        'ConvertFrom-AtNetworkMode'
        'ConvertFrom-AtNetworkModeSupport'
        'ConvertFrom-AtNewMessage'
        'ConvertFrom-AtOperator'
        'ConvertFrom-AtPinCounter'
        'ConvertFrom-AtPinRetry'
        'ConvertFrom-AtRegistration'
        'ConvertFrom-AtSignalQuality'
        'ConvertFrom-AtSimState'
        'ConvertFrom-AtTemperature'
        'ConvertFrom-DriverInf'
        'ConvertFrom-Earfcn'
        'ConvertFrom-GtactBandCode'
        'ConvertFrom-MeasurementIndex'
        'ConvertFrom-NrArfcn'
        'ConvertFrom-SmsPdu'
        'ConvertTo-AppSetting'
        'ConvertTo-AtNetworkModeCommand'
        'ConvertTo-GtactBandCode'
        'ConvertTo-RedactedText'
        'ConvertTo-SmsPdu'
        'Copy-DriverPackage'
        'Disable-SimPin'
        'Enable-ModemAdapter'
        'Export-AppSetting'
        'Export-DataUsage'
        'Export-SmsUnread'
        'Get-ApnPassword'
        'Get-AtCommandTimeout'
        'Get-AppLogonTask'
        'Get-DohKnownServer'
        'Get-DriverPackageFact'
        'Get-InterfaceDoh'
        'Get-KnownDriverPackage'
        'Get-ModemAdapterCounter'
        'Get-ModemAdapterState'
        'Get-ModemObservation'
        'Get-ModemPnpRecord'
        'Get-ModemRadioStatus'
        'Get-SimPin'
        'Get-SmsFingerprint'
        'Get-UsageCycleStart'
        'Import-AppSetting'
        'Import-AtFixture'
        'Import-DataUsage'
        'Import-SmsUnread'
        'Initialize-AtChannel'
        'Install-ModemDriver'
        'Invoke-AtCommand'
        'Invoke-FccUnlock'
        'Invoke-ModemConnect'
        'Invoke-ModemWorker'
        'Invoke-ModemWorkerCycle'
        'Invoke-RecoveryStep'
        'Join-SmsPart'
        'Measure-DataUsage'
        'Measure-SmsText'
        'New-AtChannel'
        'New-DriverStagingFolder'
        'New-ModemSnapshot'
        'New-ModemWorker'
        'New-ModemWorkerLink'
        'New-SimulatedDevice'
        'New-SimulatedModem'
        'Open-MaintenanceWindow'
        'Open-SerialAtTransport'
        'Receive-AtUrc'
        'Receive-DohNameLookup'
        'Receive-UpdateCheck'
        'Remove-ApnPassword'
        'Remove-DriverStagingLeftover'
        'Remove-SimPin'
        'Resolve-AdapterClearing'
        'Resolve-AdapterConfiguration'
        'Resolve-AtLine'
        'Resolve-ConnectionState'
        'Resolve-DataPathHealth'
        'Resolve-DohServer'
        'Resolve-DriverPackage'
        'Resolve-FccLock'
        'Resolve-HealthCheck'
        'Resolve-ModemPresence'
        'Resolve-ModemUsbDevice'
        'Resolve-NetworkMode'
        'Resolve-NetworkModeTrial'
        'Resolve-RadioStatus'
        'Resolve-RecoveryAction'
        'Resolve-SimPinAction'
        'Resolve-UpdateNotice'
        'Resolve-UpdateRedirect'
        'Resolve-UsageWarning'
        'Resolve-WorkerSchedule'
        'Restart-ModemUsbDevice'
        'Save-ApnPassword'
        'Save-SimPin'
        'Send-AtMessagePdu'
        'Send-ModemCommand'
        'Set-InterfaceDoh'
        'Set-ModemAdapterConfiguration'
        'Set-SimPinAttempt'
        'Split-AtText'
        'Start-DohNameLookup'
        'Start-UpdateCheck'
        'Set-AppLogonTask'
        'Stop-DohNameLookup'
        'Stop-UpdateCheck'
        'Test-ModemDataPath'
        'Uninstall-ModemDriver'
        'Update-DataUsage'
        'Update-SmsUnread'
        'Write-AppLog'
    )
    CmdletsToExport      = @()
    VariablesToExport    = @()
    AliasesToExport      = @()
    PrivateData          = @{
        PSData = @{
            Tags       = @('Fibocom', 'FM350', '5G', 'LTE', 'Modem', 'Windows')
            LicenseUri = 'https://github.com/francesco-stimola/fibocom-fm350-gl-windows-gui/blob/main/LICENSE'
            ProjectUri = 'https://github.com/francesco-stimola/fibocom-fm350-gl-windows-gui'
        }
    }
}
